export const procedureExampleData = [
	'Cắt lọc - khâu vết thương da đầu mang tóc',
	'che phủ vết thương khuyết da đầu mang tóc bằng vạt tại chỗ',
	'che phủ vết thương khuyết da đầu mang tóc bằng vạt lân cận',
	'che phủ vết thương khuyết da đầu mang tóc bằng vạt tự do',
	'điều trị lột da đầu bán phần',
	'điều trị da đầu đứt rời không sử dụng kỹ thuật vi phẫu',
	'cắt bỏ u da lành tính vùng da đầu từ 2cm trở lên',
	'cắt bỏ ung thư da vùng da đầu dưới 2cm',
	'cắt bỏ ung thư da vùng da đầu từ 2cm trở lên',
	'Tạo hình khuyết da đầu bằng ghép da mỏng',
	'Tạo hình khuyết da đầu bằng ghép da dày',
	'tạo vạt da lân cận che phủ các khuyết da đầu',
	'tạo vạt da tự do che phủ các khuyết da đầu',
	'tạo hình che phủ khuyết phức hợp vùng đầu bằng vạt da cân xương có cuống nuôi',
	'tạo hình che phủ khuyết phức hợp vùng đầu bằng vạt da cân xương tự do',
	'đặt túi giãn da vùng da đầu',
	'bơm túi giãn da vùng da đầu',
	'tạo vạt giãn da vùng da đầu',
	'giãn da cấp tính vùng da đầu',
	'ghép mỡ trung bì vùng trán',
	'độn khuyết xương sọ bằng sụn tự thân',
	'độn khuyết xương sọ bằng xương tự thân',
	'độn khuyết xương sọ bằng chất liệu nhân tạo',
	'ghép mỡ tự thân coleman vùng trán',
	'tái tạo trán lõm bằng xi măng xương',
	'lấy mảnh xương sọ hoại tử',
	'ghép bộ phận mũi đứt rời không sử dụng vi phẫu',
	'tạo hình môi toàn bộ bằng vạt tại chỗ',
	'tạo hình môi toàn bộ bằng vạt tự do',
	'tạo hình môi từng phần bằng vạt tại chỗ',
	'tạo hình môi từng phần bằng vạt lân cận',
	'tạo hình môi từng phần bằng vạt từ xa',
	'tạo hình môi kết hợp các bộ phận xung quanh bằng kỹ thuật vi phẫu',
	'chỉnh sửa lệch miệng do liệt thần kinh VII',
	'phục hồi, tái tạo dây thần kinh VII (đoạn ngoài sọ)',
	'khâu vết thương thấu má và ống tuyến nước bọt',
	'khâu vết thương ống tuyến nước bọt',
	'khâu vết thương thần kinh',
	'ghép lại mảnh da mặt đứt rời không bằng vi phẫu',
	'vết thương vùng hàm mặt do hỏa khí',
	'tạo hình khe hở sọ mặt số 7',
	'tạo hình khe hở sọ mặt số 8',
	'tạo hình khe hở sọ mặt 2 bên',
	'tạo hình thiểu sản bẩm sinh nửa mặt bằng ghép mỡ coleman',
	'tạo hình thiểu sản bẩm sinh toàn bộ mặt bằng ghép mỡ coleman',
	'sửa sẹo vùng cổ, mặt bằng vạt da tại chỗ',
	'sửa sẹo vùng cổ, mặt bằng vạt da lân cận',
	'Ghép da dầy toàn bộ, diện tích dưới 10cm2',
	'Ghép da dầy toàn bộ, diện tích trên 10cm2',
	'Cắt u máu vùng đầu mặt cổ',
	'Cắt dị dạng bạch mạch đầu mặt cổ',
	'Cắt dị dạng tĩnh mạch đầu mặt cổ',
	'Tiêm xơ dị dạng tĩnh mạch đầu mặt cổ',
	'cắt ung thư da vùng cổ mặt dưới 5cm và tạo hình bằng ghép da tự thân',
	'cắt ung thư da vùng cổ mặt dưới 5cm và tạo hình bằng vạt da tại chỗ',
	'cắt ung thư da vùng cổ mặt trên 5cm và tạo hình bằng vạt da lân cận',
	'cắt ung thư da vùng cổ mặt trên 5cm và tạo hình bằng vạt da bằng kỹ thuật vi phẫu',
	'Cắt u mỡ hệ thống lan tỏa vùng hàm mặt',
	'lấy bỏ chất silicon lỏng vùng mặt cổ',
	'lấy bỏ chất liệu độn vùng mặt cổ',
	'thu nhỏ vú phì đại',
	'Cắt bỏ khối u da lành tính dưới 5cm',
	'Cắt bỏ khối u da lành tính trên 5cm',
	'ghép da tự thân các khuyết phần mềm cánh tay',
	'ghép da tự thân các khuyết phần mềm cẳng tay',
	'tạo hình các khuyết phần mềm phức tạp cánh tay bằng vạt tại chỗ',
	'tạo hình các khuyết phần mềm phức tạp cẳng tay bằng vạt tại chỗ',
	'tạo hình các khuyết phần mềm phức tạp cẳng tay bằng vạt lân cận',
	'tạo hình các khuyết phần mềm phức tạp cánh tay bằng vạt da có sử dụng vi phẫu thuật',
	'điều trị vết thương bàn tay bằng ghép da tự thân',
	'điều trị vết thương bàn tay bằng các vạt da tại chỗ',
	'điều trị vết thương bàn tay bằng các vạt da lân cận',
	'điều trị vết thương bàn tay bằng các vạt da từ xa',
	'điều trị vết thương bàn tay bằng vạt có sử dụng vi phẫu thuật',
	'điều trị vết thương ngón tay bằng ghép da tự thân',
	'điều trị vết thương ngón tay bằng các vạt da tại chỗ',
	'điều trị vết thương ngón tay bằng các vạt da lân cận',
	'điều trị vết thương ngón tay bằng các vạt da từ xa',
	'điều trị vết thương ngón tay bằng vạt có sử dụng vi phẫu thuật',
	'Nối gân gấp',
	'ghép gân gấp không sử dụng vi phẫu thuật',
	'ghép gân gấp có sử dụng vi phẫu thuật',
	'Nối gân duỗi',
	'Gỡ dính gân',
	'Khâu nối thần kinh không sử dụng vi phẫu thuật',
	'Khâu nối thần kinh sử dụng vi phẫu thuật',
	'Gỡ dính thần kinh',
	'tái tạo ngón cái bằng kỹ thuật vi phẫu',
	'cái hóa',
	'Chuyển ngón có cuống mạch nuôi',
	'tạo hình kẽ ngón cái',
	'Rút nẹp vít và các dụng cụ khác sau phẫu thuật',
	'Thay khớp bàn tay',
	'Thay khớp liên đốt các ngón tay',
	'tách dính 2 ngón tay',
	'tách dính 3 ngón tay',
	'tách dính 4 ngón tay',
	'cắt ngón tay thừa',
	'cắt bỏ ngón tay cái thừa',
	'tạo hình ngón tay cái xẻ đôi',
	'sửa sẹo co nách bằng ghép da tự thân',
	'sửa sẹo co khuỷu bằng ghép da tự thân',
	'sửa sẹo co nách bằng vạt da tại chỗ',
	'sửa sẹo co khuỷu bằng vạt tại chỗ',
	'sửa sẹo co nách bằng vạt da cơ lân cận',
	'sửa sẹo co khuỷu bằng vạt da từ xa',
	'sửa sẹo co nách bằng vạt da có sử dụng vi phẫu thuật',
	'sửa sẹo co khuỷu bằng vạt da có sử dụng vi phẫu thuật',
	'sửa sẹo co cổ bàn tay bằng tạo hình chữ Z',
	'sửa sẹo co ngón tay bằng tạo hình chữ Z',
	'sửa sẹo co cổ bàn tay bằng ghép da tự thân',
	'sửa sẹo co ngón tay bằng ghép da tự thân',
	'vi phẫu tích làm mỏng vạt tạo hình bàn ngón tay',
	'tạo vạt trì hoãn cho bàn ngón tay',
	'tạo vạt tĩnh mạch cho khuyết phần mềm bàn ngón tay',
	'ghép móng',
	'giãn da cho vùng cánh cẳng tay',
	'giãn da điều trị dính ngón bẩm sinh',
	'tạo hình các khuyết da vùng đùi bằng ghép da tự thân',
	'tạo hình các khuyết da vùng khoeo bằng ghép da tự thân',
	'tạo hình các khuyết da vùng cẳng bằng ghép da tự thân',
	'tạo hình các khuyết da vùng cổ chân bằng ghép da tự thân',
	'tạo hình các khuyết da vùng bàn chân bằng ghép da tự thân',
	'tạo hình các khuyết da vùng đùi bằng vạt da tại chỗ',
	'tạo hình các khuyết da vùng khoeo bằng vạt da tại chỗ',
	'tạo hình các khuyết da vùng cẳng chân bằng vạt da tại chỗ',
	'tạo hình các khuyết da vùng đùi bằng vạt da lân cận',
	'tạo hình các khuyết da vùng khoeo bằng vạt da lân cận',
	'tạo hình các khuyết da vùng cẳng chân bằng vạt da lân cận',
	'tạo hình các khuyết da vùng bàn chân bằng ghép da lân cận',
	'tạo hình các khuyết da vùng cẳng chân bằng vạt da có sử dụng kỹ thuật vi phẫu',
	'tạo hình các khuyết da vùng bàn chân bằng ghép da có sử dụng kỹ thuật vi phẫu',
	'Khâu nối thần kinh ngoại biên vùng cổ',
	'khâu vết thương thấu má',
	'Điều trị gãy xương chỉnh mũi bằng nắn chỉnh',
	'Điều trị gãy xương chỉnh mũi bằng nắn chỉnh',
	'chỉnh sửa góc hàm xương hàm dưới',
	'chỉnh sửa góc hàm xương hàm dưới',
	'cắt chỉnh cằm',
	'chỉnh sửa thân xương hàm dưới',
	'tạo hình thiểu sản bẩm sinh nửa mặt bằng chất làm đầy',
	'tạo hình thiểu sản bẩm sinh nửa mặt bằng chất làm đầy',
	'cắt bỏ u da mặt lành tính',
	'khâu đóng trực tiếp sẹo vùng cổ, mặt (dưới 3cm)',
	'khâu đóng trực tiếp sẹo vùng cổ, mặt (trên 3cm)',
	'sửa sẹo vùng cổ, mặt bằng vạt da từ xa',
	'ghép xương tự thân tức thì sau đoạn xương hàm trên',
	'ghép xương bằng vật liệu thay thế tức thì sau cắt đoạn xương hàm trên',
	'Tạo hình hộp sọ trong dị tật hẹp hộp sọ',
	'Tạo hình không âm đạo bằng (tạo khoang và) nong giãn',
	'Tạo hình dị tật ngắn âm đạo bằng nong giãn',
	'cắt bỏ tổ chức hoại tử trong ổ loét tỳ đè',
	'ghép sụn mi mắt',
	'ghép da tự thân vùng mi mắt',
	'tạo hình mi mắt kết hợp các bộ phận xung quanh',
	'ghép mỡ tự thân coleman điều trị lõm mắt',
	'ghép mỡ trung bì tự thân điều trị lõm mắt',
	'Đặt sụn sườn vào dưới màng xương điều trị lõm mắt',
	'Đặt bản silicon trong điều trị lõm mắt',
	'Nâng sàn hốc mắt',
	'Tạo hình hốc mắt trong tật không nhãn cầu để lắp mắt giả',
	'Tái tạo toàn bộ mi bằng vạt có cuống mạch',
	'Tái tạo toàn bộ mi và cùng đồ bằng vạt có cuống mạch',
	'Tái tạo toàn bộ mi và cùng đồ bằng vạt tự do',
	'Điều trị chứng co giật mi trên bằng botox',
	'Tái tạo cung mày bằng vật có cuống mạch nuôi',
	'Tái tạo cung mày bằng ghép da đầu mang tóc',
	'Khâu và cắt lọc vết thương vùng mũi',
	'tạo hình mũi toàn bộ',
	'tạo hình mũi một phần',
	'tạo hình tháp mũi bằng vạt có cuống mạch nuôi',
	'tạo hình tháp mũi bằng vạt da kế cận',
	'tạo hình tháp mũi bằng vạt da từ xa',
	'tạo hình cánh mũi bằng các vạt có cuống mạch nuôi',
	'tạo hình cánh mũi bằng ghép phức hợp vành tai',
	'cắt bỏ u lành tính vùng mũi (dưới 2cm)',
	'cắt bỏ u lành tính vùng mũi (trên 2cm)',
	'tạo hình mũi sư tử',
	'sửa cánh mũi trong sẹo khe hở môi đơn',
	'treo cung mày bằng chỉ',
	'tạo hình thiểu năng vòm hầu bằng tiêm chất làm đầy',
	'Hút mỡ vùng hông',
	'Hút mỡ vùng lưng',
	'Hút mỡ tạo bụng 6 múi',
	'chỉnh sửa các biến chứng sau hút mỡ',
	'cấy mỡ tạo dáng cơ thể',
	'cấy mỡ nâng mũi',
	'cấy mỡ làm đầy vùng mặt',
	'cấy mỡ bàn tay',
	'cấy mỡ vùng mông',
	'làm to mông bằng túi độn mông',
	'nâng vú bằng túi độn ngực',
	'nâng vú bằng chất làm đầy',
	'chỉnh sửa các biến chứng sau mổ nâng vú',
	'căng da bụng không cắt rời và di chuyển rốn',
	'căng da bụng có cắt rời và di chuyển rốn',
	'tái tạo thành bụng đơn giản',
	'tái tạo thành bụng phức tạp',
	'tạo hình thành bụng toàn phần kết hợp hút mỡ bụng',
	'chỉnh sửa các biến chứng sau mổ tạo hình thẩm mỹ bụng',
	'độn cằm',
	'chỉnh hình cằm bằng cấy mỡ',
	'chỉnh hình cằm bằng tiêm chất làm đầy',
	'chỉnh sửa các biến chứng sau mổ chỉnh hình cằm',
	'thẩm mỹ cơ quan sinh dục ngoài nữ',
	'thu nhỏ âm đạo',
	'Laser điều trị u da',
	'Laser điều trị nám da',
	'Laser điều trị đồi mồi',
	'Laser điều trị nếp nhăn                       ',
	'Tiêm botulium điều trị nếp nhăn',
	'Tiêm chất làm đầy xóa nếp nhăn',
	'Tiêm chất làm đầy nâng mũi',
	'Tiêm chất làm đầy độn mô',
	'cắt xương điều trị nhô cằm',
	'điều trị hoại tử mô do tia xạ bằng vạt có cuống mạch nuôi',
	'điều trị hoại tử xương hàm do tia xạ',
	'điều trị hoại tử xương và phần mềm vùng hàm mặt do tia xạ',
	'đặt túi bơm giãn da',
	'Nút động mạch dị dạng động tĩnh mạch ở vùng đầu và hàm mặt',
	'Cắt u phần mềm vùng cổ',
	'Cắt nơvi sắc tố vùng hàm mặt',
	'ghép lại mảnh da mặt đứt rời bằng vi phẫu',
]
