version: '3.3'

networks:
  mh_network:
    driver: bridge

services:
  nginx:
    container_name: mhc_nginx
    image: nginx:1.23.3-alpine
    restart: unless-stopped
    networks:
      - mh_network
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/adminer.d/:/etc/nginx/adminer.d/
      - ./nginx/ssl/:/etc/nginx/ssl/
    ports:
      - "80:80"
      - "443:443"
      - "23080:23080"
