version: "3.3"

networks:
  mh_network:
    driver: bridge

services:
  api-public:
    container_name: mhc_api-public
    image: mhi_nestjs_production:1.0.0
    restart: unless-stopped
    networks:
      - mh_network
    build:
      dockerfile: Dockerfile
      context: "./"
      target: production
    command: node dist/apps/api-public/main
    environment:
      - NODE_ENV=production
