version: "3.3"

networks:
  mh_network:
    driver: bridge

services:
  zookeeper:
    container_name: mhc_zookeeper
    image: "bitnami/zookeeper:3.6.4"
    networks:
      - mh_network
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: mhc_kafka
    image: "bitnami/kafka:3.3.2"
    networks:
      - mh_network
    depends_on:
      - zookeeper
    # volumes:
    #   - ./data/kafka:/bitnami/kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT

  kafka-ui:
    container_name: mhc_kafka-ui
    image: provectuslabs/kafka-ui
    depends_on:
      - kafka
    networks:
      - mh_network
    ports:
      - "9090:8080"
    restart: unless-stopped
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
