import { Global, Module } from '@nestjs/common'
import { TypeOrmModule } from '@nestjs/typeorm'
import {
    CustomerPaymentRepository,
    CustomerRepository,
    DistributorPaymentRepository,
    DistributorRepository,
    InvoiceItemRepository,
    InvoiceProcessRepository,
    InvoiceRepository,
    OrganizationRepository,
    ProcedureRepository,
    ProductBatchRepository,
    ProductMovementRepository,
    ProductRepository,
    ReceiptProcessRepository,
    ReceiptRepository,
    StatisticRepository,
    UserRepository,
} from '.'
import {
    Customer,
    CustomerPayment,
    Distributor,
    DistributorPayment,
    Employee,
    Invoice,
    InvoiceExpense,
    InvoiceItem,
    InvoiceSurcharge,
    Organization,
    OrganizationSetting,
    Procedure,
    Product,
    ProductBatch,
    ProductMovement,
    Receipt,
    ReceiptItem,
} from '../entities'

@Global()
@Module({
    imports: [
        TypeOrmModule.forFeature([
            Customer,
            CustomerPayment,
            Distributor,
            DistributorPayment,
            Employee,
            Invoice,
            InvoiceItem,
            InvoiceSurcharge,
            InvoiceExpense,
            Organization,
            OrganizationSetting,
            Procedure,
            Product,
            ProductBatch,
            ProductMovement,
            Receipt,
            ReceiptItem,
        ]),
    ],
    providers: [
        CustomerRepository,
        CustomerPaymentRepository,
        DistributorRepository,
        DistributorPaymentRepository,
        UserRepository,
        InvoiceRepository,
        InvoiceProcessRepository,
        InvoiceItemRepository,
        OrganizationRepository,
        ProcedureRepository,
        ProductRepository,
        ProductBatchRepository,
        ProductMovementRepository,
        ReceiptRepository,
        ReceiptProcessRepository,
        StatisticRepository,
    ],
    exports: [
        CustomerRepository,
        CustomerPaymentRepository,
        DistributorRepository,
        DistributorPaymentRepository,
        UserRepository,
        InvoiceRepository,
        InvoiceProcessRepository,
        InvoiceItemRepository,
        OrganizationRepository,
        ProductRepository,
        ProcedureRepository,
        ProductBatchRepository,
        ProductMovementRepository,
        ReceiptRepository,
        ReceiptProcessRepository,
        StatisticRepository,
    ],
})
export class RepositoryModule {}
