export * from './ticket-clinic-change-consumable.body'
export * from './ticket-clinic-change-items-money.body'
export * from './ticket-clinic-change-prescription.body'
export * from './ticket-clinic-change-procedure-list.body'
export * from './ticket-clinic-change-radiology-list.body'
export * from './ticket-clinic-register.body'
export * from './ticket-clinic-update-diagnosis.body'
export * from './ticket-clinic-upsert-ticket-radiology.body'
