export * from './ticket-change-laboratory.params'
export * from './ticket-update-priority-ticket-laboratory.body'
export * from './ticket-update-request-ticket-laboratory.body'
export * from './ticket-update-result-laboratory-group.body'
export * from './ticket-upsert-ticket-ticket-laboratory-group.body'
