export const productGroupExampleData = {
	1: 'Kháng sinh - Kháng Virus',
	2: 'Dị ứng',
	3: 'Thần Kinh',
	4: 'Tiêu Hóa',
	5: 'Cơ Xương Khớp',
	6: 'Giảm Đau - Hạ Sốt - NSAID',
	7: 'Corticoid',
	8: 'Thực Phẩm Chức Năng',
	9: 'Dinh Dưỡng',
	10: 'Hô hấp',
	11: 'Tim Mạch',
	12: 'Da Liễu',
}

export const productExampleData = [
	{
		brandName: 'AMK 457/5ml',
		substance: 'Amoxicilin 400mg + Acid Clavulanic 57mg',
		unit: 'Lọ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Thái Lan',
		costPrice: 95,
		expiryDate: 1638921600000,
		retailPrice: 170,
	},
	{
		brandName: 'akudinir 250mg/5ml',
		substance: 'cefdinir ',
		unit: 'Lọ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'ấn độ',
		costPrice: 100,
		expiryDate: 1670803200000,
		retailPrice: 150,
	},
	{
		brandName: 'Fleming 457mg/5ml',
		substance: 'Amoxicilin 400mg + Acid Clavulanic 57mg',
		unit: 'Lọ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Ấn Độ',
		costPrice: 110,
		expiryDate: null,
		retailPrice: 160,
	},
	{
		brandName: 'Fleming 1g',
		substance: 'Amoxicilin 875mg + Acid Clavulanic 125mg',
		unit: 'Vỉ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Ấn Độ',
		costPrice: 80,
		expiryDate: null,
		retailPrice: 130,
	},
	{
		brandName: 'Klacid 125mg/5ml',
		substance: 'Clarythromycin 125mg/5ml',
		unit: 'Lọ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'indonesia',
		costPrice: 105,
		expiryDate: 1635724800000,
		retailPrice: 160,
	},
	{
		brandName: 'Novafex 37,5ml',
		substance: 'cefixime 100mg/5ml',
		unit: 'Lọ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Australia',
		costPrice: 62,
		expiryDate: 1665705600000,
		retailPrice: 110,
	},
	{
		brandName: 'Cefpivoxime 50mg',
		substance: 'cefditoren 50mg',
		unit: 'Viên',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'CPDP Hà Tây',
		costPrice: 7.5,
		expiryDate: 1641168000000,
		retailPrice: 13,
	},
	{
		brandName: 'Glencinone 125mg',
		substance: 'cefdinir 125mg',
		unit: 'Viên',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'VN',
		costPrice: 3.5,
		expiryDate: 1670803200000,
		retailPrice: 7,
	},
	{
		brandName: 'Glencinone 250mg',
		substance: 'cefdinir 250mg',
		unit: 'Viên',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Vn',
		costPrice: 5,
		expiryDate: 1647216000000,
		retailPrice: 11,
	},
	{
		brandName: 'Aziphar',
		substance: 'azithromycin 200mg/5ml',
		unit: 'Lọ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'mekophar',
		costPrice: 65,
		expiryDate: 1636761600000,
		retailPrice: 130,
	},
	{
		brandName: 'Tolsus',
		substance: 'Trimethoprime 40mg+ sulfamethosazonle 200mg',
		unit: 'Lọ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Thái Lan',
		costPrice: 30,
		expiryDate: 1654646400000,
		retailPrice: 70,
	},
	{
		brandName: 'Bactirid 30ml',
		substance: 'cefixime 100mg/5ml',
		unit: 'Lọ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'pakistan',
		costPrice: 45,
		expiryDate: 1625875200000,
		retailPrice: 80,
	},
	{
		brandName: 'Qincef ',
		substance: 'cefuroxime 125mg/5ml',
		unit: 'Lọ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'VN',
		costPrice: 36,
		expiryDate: 1692489600000,
		retailPrice: 70,
	},
	{
		brandName: 'Zinnat 125mg/5ml',
		substance: 'cefuroxime 125mg/5ml',
		unit: 'Lọ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Anh',
		costPrice: 115,
		expiryDate: 1634947200000,
		retailPrice: 160,
	},
	{
		brandName: 'Zinnat 125mg',
		substance: 'cefuroxime 125mg/gói',
		unit: 'Gói',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Anh',
		costPrice: 14.1,
		expiryDate: 1670198400000,
		retailPrice: 18,
	},
	{
		brandName: 'Curam 60ml ,250mg/5ml ',
		substance: 'Amoxicilin 250mg + Acid Clavulanic 62,5mg',
		unit: 'Lọ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Australia',
		costPrice: 72,
		expiryDate: 1673740800000,
		retailPrice: 140,
	},
	{
		brandName: 'Verzat 60ml',
		substance: 'cefaclor 125mg/5ml',
		unit: 'Lọ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'philipin',
		costPrice: 65,
		expiryDate: 1641859200000,
		retailPrice: 110,
	},
	{
		brandName: 'clamoxyl 250mg',
		substance: 'amoxicilin 250mg',
		unit: 'Gói',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Pháp',
		costPrice: 5,
		expiryDate: 1639267200000,
		retailPrice: 6,
	},
	{
		brandName: 'Azismile ',
		substance: 'azithromycin 200mg/5ml',
		unit: 'Lọ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Hàn quốc',
		costPrice: 61,
		expiryDate: 1675468800000,
		retailPrice: 110,
	},
	{
		brandName: 'Claminat 500mg/62,5mg',
		substance: 'Amoxicilin 500mg + Acid Clavulanic 62,5mg',
		unit: 'Gói',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'VN',
		costPrice: 6,
		expiryDate: 1671840000000,
		retailPrice: 12,
	},
	{
		brandName: 'Ceclor 60ml',
		substance: 'cefaclor 125mg/5ml',
		unit: 'Lọ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Italia',
		costPrice: 95,
		expiryDate: 1634342400000,
		retailPrice: 160,
	},
	{
		brandName: 'azithromycin 500mg',
		substance: 'azithromycin 500mg',
		unit: 'Viên',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Hậu Giang',
		costPrice: 2,
		expiryDate: 1684454400000,
		retailPrice: 6,
	},
	{
		brandName: 'Augmentin 250mg',
		substance: 'Amoxicilin 200mg + Acid Clavulanic 31,25mg',
		unit: 'Gói',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Pháp',
		costPrice: 10,
		expiryDate: 1653782400000,
		retailPrice: 12,
	},
	{
		brandName: 'Augmentin 500mg',
		substance: 'Amoxicilin 500mg + Acid Clavulanic 62,5mg',
		unit: 'Gói',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Pháp',
		costPrice: 14,
		expiryDate: 1643328000000,
		retailPrice: 18,
	},
	{
		brandName: 'Cardiroxime 500mg',
		substance: 'cefuroxime 500mg',
		unit: 'Viên',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'VN',
		costPrice: 12,
		expiryDate: 1632960000000,
		retailPrice: 6,
	},
	{
		brandName: 'Hagimox 500mg',
		substance: 'amoxicilin 500mg',
		unit: 'Vỉ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Hậu Giang',
		costPrice: 10,
		expiryDate: 1702339200000,
		retailPrice: 20,
	},
	{
		brandName: 'Mebicefpo 200mg',
		substance: 'cefpodoxime 200mg',
		unit: 'Viên',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'VN',
		costPrice: 3,
		expiryDate: null,
		retailPrice: 7,
	},
	{
		brandName: 'flagyl 250mg',
		substance: 'metronidazole 250mg',
		unit: 'Vỉ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'VN',
		costPrice: 10.5,
		expiryDate: 1656028800000,
		retailPrice: 25,
	},
	{
		brandName: 'Hohallis',
		substance: 'Thảo dược',
		unit: 'Vỉ',
		group: 'Khác',
		route: 'Khác',
		source: 'VN',
		costPrice: 10,
		expiryDate: null,
		retailPrice: 20,
	},
	{
		brandName: 'fexolergic 60mg',
		substance: 'fexofenadin 60mg',
		unit: 'Vỉ',
		group: 'Dị ứng',
		route: 'Uống',
		source: 'VN',
		costPrice: 16,
		expiryDate: 1620950400000,
		retailPrice: 30,
	},
	{
		brandName: 'nootropil 800mg',
		substance: 'piracetam 800mg',
		unit: 'Viên',
		group: 'Thần Kinh',
		route: 'Uống',
		source: 'singapore',
		costPrice: 3.6,
		expiryDate: 1670803200000,
		retailPrice: 6,
	},
	{
		brandName: 'sorbitol 5g',
		substance: 'sorbitol',
		unit: 'Gói',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'VN',
		costPrice: 0.6,
		expiryDate: 1676592000000,
		retailPrice: 2,
	},
	{
		brandName: 'Viatril S',
		substance: 'glucosamin 1500mg',
		unit: 'Gói',
		group: 'Cơ Xương Khớp',
		route: 'Uống',
		source: 'Ailen',
		costPrice: 15,
		expiryDate: 1668124800000,
		retailPrice: 19,
	},
	{
		brandName: 'magie B6 Corbiere',
		substance: 'magie 470mg, vitamin b6 5mg',
		unit: 'Vỉ',
		group: 'Thần Kinh',
		route: 'Uống',
		source: 'VN',
		costPrice: 16,
		expiryDate: 1658361600000,
		retailPrice: 30,
	},
	{
		brandName: 'Mobic 7,5mg',
		substance: 'meloxicam 7,5mg',
		unit: 'Viên',
		group: 'Giảm Đau - Hạ Sốt - NSAID',
		route: 'Uống',
		source: 'Hy Lạp',
		costPrice: 8,
		expiryDate: 1638921600000,
		retailPrice: 10,
	},
	{
		brandName: 'Betamethasone 30g',
		substance: 'Betamethasone',
		unit: 'Tuýp',
		group: 'Corticoid',
		route: 'Bôi',
		source: 'VN',
		costPrice: 40,
		expiryDate: 1665619200000,
		retailPrice: 50,
	},
	{
		brandName: 'Myonal 50mg',
		substance: 'eperison 50mg',
		unit: 'Vỉ',
		group: 'Cơ Xương Khớp',
		route: 'Uống',
		source: 'Thái Lan',
		costPrice: 39,
		expiryDate: 1653609600000,
		retailPrice: 50,
	},
	{
		brandName: 'Primperam 10mg',
		substance: 'metoclopramid 10mg',
		unit: 'Viên',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'Pháp',
		costPrice: 1,
		expiryDate: 1651708800000,
		retailPrice: 5,
	},
	{
		brandName: 'Allopurinon 300mg',
		substance: 'Allopurinon 300mg',
		unit: 'Vỉ',
		group: 'Cơ Xương Khớp',
		route: 'Uống',
		source: 'VN',
		costPrice: 9.5,
		expiryDate: 1715731200000,
		retailPrice: 20,
	},
	{
		brandName: 'Tanganil 500mg',
		substance: 'acetil leucine',
		unit: 'Viên',
		group: 'Thần Kinh',
		route: 'Uống',
		source: 'Pháp',
		costPrice: 4,
		expiryDate: 1670803200000,
		retailPrice: 6,
	},
	{
		brandName: 'Debridat 100mg',
		substance: 'trimebutinhe 100mg',
		unit: 'Viên',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'Pháp',
		costPrice: 2,
		expiryDate: 1642896000000,
		retailPrice: 5,
	},
	{
		brandName: 'Arcorxia 60mg',
		substance: 'etoricoxib 60mg',
		unit: 'Viên',
		group: 'Giảm Đau - Hạ Sốt - NSAID',
		route: 'Uống',
		source: 'Anh',
		costPrice: 13,
		expiryDate: 1658880000000,
		retailPrice: 17,
	},
	{
		brandName: 'salonpas gel 15mg',
		substance: 'methyl salicilat 15g',
		unit: 'Tuýp',
		group: 'Giảm Đau - Hạ Sốt - NSAID',
		route: 'Bôi',
		source: 'VN',
		costPrice: 21,
		expiryDate: 1698364800000,
		retailPrice: 30,
	},
	{
		brandName: 'ameflu',
		substance: 'acetaminophen, phenyl ephrine, vit C, Guaifenesin, dextromethorphan',
		unit: 'Viên',
		group: 'Giảm Đau - Hạ Sốt - NSAID',
		route: 'Uống',
		source: 'VN',
		costPrice: 0.9,
		expiryDate: 1653868800000,
		retailPrice: 1.5,
	},
	{
		brandName: 'ginkobiloba 2000',
		substance: 'ginko 2000',
		unit: 'Lọ',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'Australia',
		costPrice: 135,
		expiryDate: 1701388800000,
		retailPrice: 230,
	},
	{
		brandName: 'Ostelin kids Calcium vit D3',
		substance: 'calcium 350mg+D3 300UI',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Australia',
		costPrice: 50,
		expiryDate: null,
		retailPrice: 290,
	},
	{
		brandName: 'Bioisland Lysine Step Up',
		substance: 'Lysine 250mg',
		unit: 'Lọ',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'Australia',
		costPrice: 225,
		expiryDate: 1690761600000,
		retailPrice: 320,
	},
	{
		brandName: 'Bioisland ZinC',
		substance: 'zinc 3mg',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Australia',
		costPrice: 225,
		expiryDate: 1700611200000,
		retailPrice: 320,
	},
	{
		brandName: 'Bioisland DHA',
		substance: 'DHA 100mg',
		unit: 'Lọ',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'Australia',
		costPrice: 235,
		expiryDate: 1638921600000,
		retailPrice: 350,
	},
	{
		brandName: 'pediakid sommeil',
		substance: 'bé ngủ ngon',
		unit: 'Lọ',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'Pháp',
		costPrice: 180,
		expiryDate: 1683244800000,
		retailPrice: 240,
	},
	{
		brandName: 'Prospan',
		substance: 'cao khô lá thường xuân',
		unit: 'Lọ',
		group: 'Hô hấp',
		route: 'Uống',
		source: 'Đức',
		costPrice: 150,
		expiryDate: 1638921600000,
		retailPrice: 220,
	},
	{
		brandName: 'anaferon siro',
		substance: 'anaferon',
		unit: 'Lọ',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'Nga',
		costPrice: 130,
		expiryDate: 1638921600000,
		retailPrice: 190,
	},
	{
		brandName: 'anaferon viên',
		substance: 'anaferon',
		unit: 'Vỉ',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'Nga',
		costPrice: 90,
		expiryDate: 1635292800000,
		retailPrice: 140,
	},
	{
		brandName: 'maxclary 250mg',
		substance: 'Clarythromycin 250mg',
		unit: 'Viên',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'VN',
		costPrice: 4.5,
		expiryDate: 1670803200000,
		retailPrice: 7,
	},
	{
		brandName: 'Clavuraem 625mg',
		substance: 'Amoxicilin 500mg + Acid Clavulanic 125mg',
		unit: 'Viên',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'CH Séc',
		costPrice: 7.5,
		expiryDate: 1662681600000,
		retailPrice: 12,
	},
	{
		brandName: 'Cool-Flu',
		substance: 'Thảo dược',
		unit: 'Lọ',
		group: 'Hô hấp',
		route: 'Uống',
		source: 'VN',
		costPrice: 30,
		expiryDate: 1638921600000,
		retailPrice: 70,
	},
	{
		brandName: 'Mekotricin',
		substance: 'tyrothycin',
		unit: 'Túi',
		group: 'Hô hấp',
		route: 'Ngậm',
		source: 'VN',
		costPrice: 8,
		expiryDate: null,
		retailPrice: 20,
	},
	{
		brandName: 'Hapacol 80mg',
		substance: 'paracetamol 80mg',
		unit: 'Gói',
		group: 'Giảm Đau - Hạ Sốt - NSAID',
		route: 'Uống',
		source: 'Hậu Giang',
		costPrice: 1,
		expiryDate: 1702339200000,
		retailPrice: 5,
	},
	{
		brandName: 'Hapacol 150mg',
		substance: 'paracetamol 150mg',
		unit: 'Gói',
		group: 'Giảm Đau - Hạ Sốt - NSAID',
		route: 'Uống',
		source: 'Hậu Giang',
		costPrice: 1.25,
		expiryDate: 1699747200000,
		retailPrice: 5,
	},
	{
		brandName: 'Hapacol 250mg',
		substance: 'paracetamol 250mg',
		unit: 'Gói',
		group: 'Giảm Đau - Hạ Sốt - NSAID',
		route: 'Uống',
		source: 'Hậu Giang',
		costPrice: 1.5,
		expiryDate: 1702339200000,
		retailPrice: 5,
	},
	{
		brandName: 'efferalgan 80mg',
		substance: 'paracetamol 80mg',
		unit: 'Viên',
		group: 'Giảm Đau - Hạ Sốt - NSAID',
		route: 'Khác',
		source: 'Hậu Giang',
		costPrice: 2.2,
		expiryDate: 1670803200000,
		retailPrice: 5,
	},
	{
		brandName: 'efferalgan 150mg',
		substance: 'paracetamol 150mg',
		unit: 'Viên',
		group: 'Giảm Đau - Hạ Sốt - NSAID',
		route: 'Khác',
		source: 'Hậu Giang',
		costPrice: 2.5,
		expiryDate: 1680912000000,
		retailPrice: 5,
	},
	{
		brandName: 'Multipro',
		substance: 'vitamin',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Anh',
		costPrice: 153,
		expiryDate: 1645401600000,
		retailPrice: 250,
	},
	{
		brandName: 'Medibest',
		substance: 'Vitamin D3 400Ui+ K2 2,5mcg',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Italia',
		costPrice: 165,
		expiryDate: 1719619200000,
		retailPrice: 260,
	},
	{
		brandName: 'Immunoglucan C',
		substance: 'betagluca+ vit C',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Italia',
		costPrice: 175,
		expiryDate: -55131753600000,
		retailPrice: 250,
	},
	{
		brandName: 'Bone cal',
		substance: 'Calcium 500mg+ D3 200Ui+k2 10mcg',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Italia',
		costPrice: 200,
		expiryDate: 1653955200000,
		retailPrice: 280,
	},
	{
		brandName: 'multivitamin mini drop natures aid',
		substance: '9 vitamin',
		unit: 'Chai',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Natures aid- Anh',
		costPrice: 40,
		expiryDate: null,
		retailPrice: 250,
	},
	{
		brandName: 'Imunoglukan P4H',
		substance: 'betagluca+ vit C',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: '',
		costPrice: 100,
		expiryDate: null,
		retailPrice: 320,
	},
	{
		brandName: 'Pedia Iron Drops',
		substance: 'sắt 15mg/ml',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'mỹ',
		costPrice: 157,
		expiryDate: 1651104000000,
		retailPrice: 250,
	},
	{
		brandName: 'Blackmores prenancy iron',
		substance: 'sắt 24mg',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Australia',
		costPrice: 145,
		expiryDate: 1653955200000,
		retailPrice: 200,
	},
	{
		brandName: 'BioGaia _ Balan',
		substance: 'lactobacillus reuteri',
		unit: 'Lọ',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'balan',
		costPrice: 265,
		expiryDate: 1696982400000,
		retailPrice: 350,
	},
	{
		brandName: 'Ostelin Calcium vit D3 infant',
		substance: 'calcium 600mg+D3 500UI',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Australia',
		costPrice: 195,
		expiryDate: 1638921600000,
		retailPrice: 350,
	},
	{
		brandName: 'Ferrotamin syrup',
		substance: 'sắt 7mg/5ml + vitamin',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'hungary',
		costPrice: 110,
		expiryDate: 1718841600000,
		retailPrice: 180,
	},
	{
		brandName: 'Zinc plex',
		substance: 'kẽm 15mg/5ml+ lysin 10mg+selenium',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Italia',
		costPrice: 175,
		expiryDate: 1718841600000,
		retailPrice: 270,
	},
	{
		brandName: 'Kids Smart drops DHA ',
		substance: 'DHA',
		unit: 'Lọ',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'Nature\'s Way - Australia',
		costPrice: 160,
		expiryDate: 1702339200000,
		retailPrice: 260,
	},
	{
		brandName: 'Kids high strength DHA ',
		substance: 'DHA 100mg',
		unit: 'Lọ',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'Australia',
		costPrice: 145,
		expiryDate: 1693353600000,
		retailPrice: 220,
	},
	{
		brandName: 'Broncho-Vaxom children',
		substance: 'lyophilized bacterial lysates 3,5mg',
		unit: 'Vỉ',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'Thuỵ sĩ',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 170,
	},
	{
		brandName: 'zinofa',
		substance: 'kẽm',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'VN',
		costPrice: 38,
		expiryDate: 1697414400000,
		retailPrice: 100,
	},
	{
		brandName: 'Bioisland Milk Calcium for kids',
		substance: 'calcium 78mg',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Australia',
		costPrice: 295,
		expiryDate: 1699920000000,
		retailPrice: 390,
	},
	{
		brandName: 'Dutimol',
		substance: 'vitamin+ acid amin',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'VN',
		costPrice: 85,
		expiryDate: 1719619200000,
		retailPrice: 180,
	},
	{
		brandName: 'vita gold',
		substance: 'vitamin+ tâm sen',
		unit: 'Lọ',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'VN',
		costPrice: 140,
		expiryDate: 1719619200000,
		retailPrice: 220,
	},
	{
		brandName: 'Laforin bạc hà',
		substance: 'nước súc miệng',
		unit: 'Chai',
		group: 'Khác',
		route: 'Khác',
		source: 'VN',
		costPrice: 92,
		expiryDate: 1678752000000,
		retailPrice: 115,
	},
	{
		brandName: 'Laforin đào',
		substance: 'nước súc miệng',
		unit: 'Chai',
		group: 'Khác',
		route: 'Khác',
		source: 'VN',
		costPrice: 92,
		expiryDate: 1678752000000,
		retailPrice: 115,
	},
	{
		brandName: 'Blackmores glucosamine ',
		substance: 'glucosamin 1500mg',
		unit: 'Lọ',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'Australia',
		costPrice: 515,
		expiryDate: 1673395200000,
		retailPrice: 670,
	},
	{
		brandName: 'Phacoter',
		substance: 'Codein 10mg + Terpin Hydrat 100mg',
		unit: 'Viên',
		group: 'Hô hấp',
		route: 'Uống',
		source: 'vn',
		costPrice: 0.5,
		expiryDate: 1671062400000,
		retailPrice: 1.5,
	},
	{
		brandName: 'Spydmax ',
		substance: 'Spiramycin 1.500.000 IU',
		unit: 'Gói',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'VN',
		costPrice: 4.9,
		expiryDate: 1629590400000,
		retailPrice: 8,
	},
	{
		brandName: 'Lopran',
		substance: 'Loperamide BP 2mg',
		unit: 'Viên',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'Ấn Độ',
		costPrice: 0.1,
		expiryDate: null,
		retailPrice: 0.3,
	},
	{
		brandName: 'Spasmaverine',
		substance: 'Alverine citrate 60mg',
		unit: 'Viên',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'VN',
		costPrice: 0.7,
		expiryDate: 1616544000000,
		retailPrice: 1,
	},
	{
		brandName: 'Colchicin',
		substance: 'Colchicin 1mg',
		unit: 'Vỉ',
		group: 'Cơ Xương Khớp',
		route: 'Uống',
		source: 'VN',
		costPrice: 18,
		expiryDate: 1692230400000,
		retailPrice: 40,
	},
	{
		brandName: 'Medrol 16',
		substance: 'Methyprednisolone 16mg',
		unit: 'Viên',
		group: 'Corticoid',
		route: 'Uống',
		source: 'Italia',
		costPrice: 3.733,
		expiryDate: 1697932800000,
		retailPrice: 5,
	},
	{
		brandName: 'Modom\'S',
		substance: 'Domperidon 10mg',
		unit: '',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'VN',
		costPrice: 0.5,
		expiryDate: null,
		retailPrice: 1,
	},
	{
		brandName: 'SOSCough',
		substance: 'Cetirizin 5mg + Guaifenesin 100mg + Dextromethorphan 15mg',
		unit: 'Vỉ',
		group: 'Hô hấp',
		route: 'Uống',
		source: 'VN',
		costPrice: 12.667,
		expiryDate: 1700092800000,
		retailPrice: 20,
	},
	{
		brandName: 'Hagizin',
		substance: 'Flunarizine 5mg',
		unit: 'Viên',
		group: 'Thần Kinh',
		route: 'Uống',
		source: 'VN',
		costPrice: 0.88,
		expiryDate: 1664841600000,
		retailPrice: 2.5,
	},
	{
		brandName: 'Medlicet',
		substance: 'Ceftirizine BP 10mg',
		unit: 'Viên',
		group: 'Dị ứng',
		route: 'Uống',
		source: 'VN',
		costPrice: 0.2,
		expiryDate: 1649030400000,
		retailPrice: 0.5,
	},
	{
		brandName: ' Cenfast 120',
		substance: 'Fexofenadin 120mg',
		unit: 'Viên',
		group: 'Dị ứng',
		route: 'Uống',
		source: 'VN',
		costPrice: 1.55,
		expiryDate: 1657584000000,
		retailPrice: 5,
	},
	{
		brandName: 'Brexin',
		substance: 'Piroxicam 20mg',
		unit: 'Viên',
		group: 'Giảm Đau - Hạ Sốt - NSAID',
		route: 'Uống',
		source: 'Italia',
		costPrice: 7.8,
		expiryDate: 1644624000000,
		retailPrice: 9.5,
	},
	{
		brandName: 'Panangin',
		substance: 'Mg 11,8mg + K 36,2 mg',
		unit: 'Viên',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Hungary',
		costPrice: 1.56,
		expiryDate: 1643155200000,
		retailPrice: 2.5,
	},
	{
		brandName: 'Strepsils ',
		substance: 'ngậm',
		unit: 'Vỉ',
		group: 'Khác',
		route: 'Khác',
		source: 'Thái Lan',
		costPrice: 15,
		expiryDate: 1638921600000,
		retailPrice: 20,
	},
	{
		brandName: 'Zebacef 300',
		substance: 'Cefdinir 300mg',
		unit: 'Viên',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Thổ Nhĩ Kỳ',
		costPrice: 7.2,
		expiryDate: 1648598400000,
		retailPrice: 12,
	},
	{
		brandName: 'Akugabalin',
		substance: 'Pregabalin 75mg',
		unit: 'Viên',
		group: 'Thần Kinh',
		route: 'Uống',
		source: 'Ấn Độ',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 9,
	},
	{
		brandName: 'Difelene',
		substance: 'Diclofenac 50mg',
		unit: 'Viên',
		group: 'Giảm Đau - Hạ Sốt - NSAID',
		route: 'Uống',
		source: 'Thái Lan',
		costPrice: 1,
		expiryDate: 1707955200000,
		retailPrice: 2,
	},
	{
		brandName: 'Clorpheniramin 4mg',
		substance: 'Clorpheniramin 4mg',
		unit: 'Vỉ',
		group: 'Dị ứng',
		route: 'Uống',
		source: 'VN',
		costPrice: 2,
		expiryDate: 1679702400000,
		retailPrice: 5,
	},
	{
		brandName: 'AluGold Gel',
		substance: 'Magie + Nhôm + Thảo dược',
		unit: 'Gói',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'VN',
		costPrice: 4.5,
		expiryDate: 1682985600000,
		retailPrice: 9,
	},
	{
		brandName: 'Gastropulgite',
		substance: 'Aluminium + Magnesium',
		unit: 'Gói',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'singapore',
		costPrice: 3.1,
		expiryDate: 1655769600000,
		retailPrice: 5,
	},
	{
		brandName: 'Postan_eight',
		substance: 'Bromelain 50mg + Papain 20mg + Rutin 5mg',
		unit: 'Vỉ',
		group: 'Khác',
		route: 'Uống',
		source: 'vn',
		costPrice: 10,
		expiryDate: 1649548800000,
		retailPrice: 30,
	},
	{
		brandName: 'Tanganil 500mg/ 5ml',
		substance: 'acetil leucine',
		unit: 'Ống',
		group: 'Thần Kinh',
		route: 'Tiêm',
		source: 'Pháp',
		costPrice: 30,
		expiryDate: 1686009600000,
		retailPrice: 45,
	},
	{
		brandName: 'Adrenalin 1mg/1ml',
		substance: 'Adrenalin',
		unit: 'Ống',
		group: 'Tim Mạch',
		route: 'Tiêm',
		source: 'vn',
		costPrice: 2,
		expiryDate: 1661558400000,
		retailPrice: 10,
	},
	{
		brandName: 'Nifephabaco',
		substance: 'Nifedipin',
		unit: 'Vỉ',
		group: 'Tim Mạch',
		route: 'Uống',
		source: 'vn',
		costPrice: 9,
		expiryDate: 1685404800000,
		retailPrice: 10,
	},
	{
		brandName: 'Vincomid',
		substance: 'Metocloramid 10mg/2ml',
		unit: 'Ống',
		group: 'Tiêu Hóa',
		route: 'Tiêm',
		source: 'vn',
		costPrice: 20,
		expiryDate: 1690934400000,
		retailPrice: 30,
	},
	{
		brandName: 'Mejybes Vitamin C',
		substance: 'Vitamin C',
		unit: 'Vỉ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'vn',
		costPrice: 5,
		expiryDate: 1672531200000,
		retailPrice: 10,
	},
	{
		brandName: 'Medi X',
		substance: 'Bromelain 30mg + Papain 50mg + Rutin 40mg',
		unit: 'Viên',
		group: 'Hô hấp',
		route: 'Uống',
		source: 'vn',
		costPrice: 1.58,
		expiryDate: 1678233600000,
		retailPrice: 2.5,
	},
	{
		brandName: '3B - Medi',
		substance: 'Vitamin B1 125mg + B6 125mg + B12 250mg',
		unit: 'Vỉ',
		group: 'Thần Kinh',
		route: 'Uống',
		source: 'vn',
		costPrice: 9.4,
		expiryDate: 1671753600000,
		retailPrice: 15,
	},
	{
		brandName: 'Betaserc ',
		substance: 'Betahistine 16mg',
		unit: 'Viên',
		group: 'Thần Kinh',
		route: 'Uống',
		source: 'Hà Lan',
		costPrice: 3.217,
		expiryDate: 1625011200000,
		retailPrice: 6,
	},
	{
		brandName: 'PrazoPro',
		substance: 'Esomeprazol 40mg',
		unit: 'Vỉ',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'vn',
		costPrice: 36,
		expiryDate: 1630713600000,
		retailPrice: 55,
	},
	{
		brandName: 'Levo DHG',
		substance: 'Levofloxacin 500mg',
		unit: 'Viên',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'vn',
		costPrice: 4.567,
		expiryDate: 1655164800000,
		retailPrice: 6,
	},
	{
		brandName: 'Cefdinir 300',
		substance: 'Cefdinir 300mg',
		unit: 'Viên',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'vn',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 13,
	},
	{
		brandName: 'MedSkin Clovir 800',
		substance: 'Acyclovir 800mg',
		unit: 'Viên',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'vn',
		costPrice: 3.333,
		expiryDate: 1670803200000,
		retailPrice: 6,
	},
	{
		brandName: 'Amlodipin 5mg',
		substance: 'Amlodipin 5mg',
		unit: 'Vỉ',
		group: 'Tim Mạch',
		route: 'Uống',
		source: 'vn',
		costPrice: 9,
		expiryDate: 1675728000000,
		retailPrice: 10,
	},
	{
		brandName: 'Daitos ',
		substance: 'Ketorolac 30mg/1ml',
		unit: 'Ống',
		group: 'Giảm Đau - Hạ Sốt - NSAID',
		route: 'Tiêm',
		source: 'Hàn Quốc',
		costPrice: 15,
		expiryDate: 1626652800000,
		retailPrice: 30,
	},
	{
		brandName: 'Vinsolon',
		substance: 'Methylprednisolone 40mg',
		unit: 'Ống',
		group: 'Corticoid',
		route: 'Tiêm',
		source: 'vn',
		costPrice: 10,
		expiryDate: 1676592000000,
		retailPrice: 30,
	},
	{
		brandName: 'Solu-Medrol',
		substance: 'Methylprednisolone 40 mg',
		unit: 'Ống',
		group: 'Corticoid',
		route: 'Tiêm',
		source: 'Bỉ',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 80,
	},
	{
		brandName: 'Midasol',
		substance: 'Bromo camphor 20mg + Methylene 20mg',
		unit: 'Vỉ',
		group: 'Khác',
		route: 'Uống',
		source: 'VN',
		costPrice: 5.5,
		expiryDate: 1690416000000,
		retailPrice: 10,
	},
	{
		brandName: 'Lodegald - Cipro',
		substance: 'Ciprofloxacin 500mg',
		unit: 'Vỉ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'vn',
		costPrice: 18.5,
		expiryDate: 1656374400000,
		retailPrice: 30,
	},
	{
		brandName: 'panadol extra',
		substance: 'paracetamol 500mg + Caffeine 65 mg',
		unit: 'Vỉ',
		group: 'Giảm Đau - Hạ Sốt - NSAID',
		route: 'Uống',
		source: 'vn',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 20,
	},
	{
		brandName: 'Daflon 500',
		substance: 'Diosmine ',
		unit: 'Vỉ',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'Pháp',
		costPrice: 52.5,
		expiryDate: 1703980800000,
		retailPrice: 75,
	},
	{
		brandName: 'Diacerein ',
		substance: 'Diacerein 50mg',
		unit: 'Viên',
		group: 'Cơ Xương Khớp',
		route: 'Uống',
		source: 'vn',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 2.5,
	},
	{
		brandName: 'MedSkin Clovir 400',
		substance: 'Acyclovir 400mg',
		unit: 'Viên',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'vn',
		costPrice: 1.85,
		expiryDate: 1657929600000,
		retailPrice: 5,
	},
	{
		brandName: 'Herperax 200',
		substance: 'Acyclovir 200mg',
		unit: 'Viên',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Ấn Độ',
		costPrice: 1.3,
		expiryDate: 1651104000000,
		retailPrice: 2,
	},
	{
		brandName: 'Hapacol Extra 650',
		substance: 'paracetamol 650mg + Caffeine 65 mg',
		unit: 'Vỉ',
		group: 'Giảm Đau - Hạ Sốt - NSAID',
		route: 'Uống',
		source: 'vn',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 10,
	},
	{
		brandName: 'Lodegald - Levo',
		substance: 'Levofloxacin 500mg',
		unit: 'Viên',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'vn',
		costPrice: 4,
		expiryDate: 1679011200000,
		retailPrice: 8,
	},
	{
		brandName: 'Pyme Azi 250',
		substance: 'azithromycin 250mg',
		unit: 'Viên',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'vn',
		costPrice: 17.5,
		expiryDate: 1649721600000,
		retailPrice: 3.5,
	},
	{
		brandName: 'Tiarutundin',
		substance: 'Thảo dược',
		unit: 'Vỉ',
		group: 'Thần Kinh',
		route: 'Uống',
		source: 'vn',
		costPrice: 5,
		expiryDate: 1646870400000,
		retailPrice: 10,
	},
	{
		brandName: 'Cifataze DT 100',
		substance: 'Cefixime 100mg',
		unit: 'Viên',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Ấn độ',
		costPrice: 1.4,
		expiryDate: 1646438400000,
		retailPrice: 5,
	},
	{
		brandName: 'Keatabs',
		substance: 'Roxithromycin 150mg',
		unit: 'Viên',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'vn',
		costPrice: 55,
		expiryDate: 1654819200000,
		retailPrice: 3.5,
	},
	{
		brandName: 'Sanlein 0.1',
		substance: 'Natri hyaluronat 0,1%',
		unit: 'Ống',
		group: 'Khác',
		route: 'Nhỏ Giọt',
		source: 'Nhật Bản',
		costPrice: 61,
		expiryDate: 1638921600000,
		retailPrice: 80,
	},
	{
		brandName: 'Candid',
		substance: 'Clotrimazole',
		unit: 'Ống',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Nhỏ Giọt',
		source: 'Ấn độ',
		costPrice: 75,
		expiryDate: 1660953600000,
		retailPrice: 90,
	},
	{
		brandName: 'Daktarin Oral gel',
		substance: 'Miconazole',
		unit: 'Tuýp',
		group: 'Da Liễu',
		route: 'Bôi',
		source: 'Thái Lan',
		costPrice: 42.5,
		expiryDate: 1685923200000,
		retailPrice: 55,
	},
	{
		brandName: 'Subạc',
		substance: 'Nano bạc',
		unit: 'Tuýp',
		group: 'Da Liễu',
		route: 'Bôi',
		source: 'VN',
		costPrice: 140,
		expiryDate: 1759622400000,
		retailPrice: 150,
	},
	{
		brandName: 'Metrogyl Denta',
		substance: 'Metronidazole gel 10mg/g',
		unit: 'Tuýp',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Bôi',
		source: 'Ấn Độ',
		costPrice: 29,
		expiryDate: 1640649600000,
		retailPrice: 55,
	},
	{
		brandName: 'Bactronil',
		substance: 'Mỡ Mupirocin 2%',
		unit: 'Tuýp',
		group: 'Da Liễu',
		route: 'Bôi',
		source: 'Ấn Độ',
		costPrice: 32,
		expiryDate: 1633910400000,
		retailPrice: 60,
	},
	{
		brandName: 'Tobrex',
		substance: 'Tobramycin 3mg/ml',
		unit: 'Ống',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Nhỏ Giọt',
		source: 'vn',
		costPrice: 40,
		expiryDate: 1635724800000,
		retailPrice: 55,
	},
	{
		brandName: 'Oflovid',
		substance: 'Ofloxacin 0,3%',
		unit: 'Ống',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Nhỏ Giọt',
		source: 'Nhật Bản',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 70,
	},
	{
		brandName: 'Plenmoxin',
		substance: 'Moxifloxacin',
		unit: 'Ống',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Nhỏ Giọt',
		source: 'Ấn Độ',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 60,
	},
	{
		brandName: 'Cinepark',
		substance: 'Ofloxacin 15mg + Dexamethason 5,5mg',
		unit: 'Ống',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Nhỏ Giọt',
		source: 'vn',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 50,
	},
	{
		brandName: 'Phenergan',
		substance: 'Promethazine',
		unit: 'Tuýp',
		group: 'Dị ứng',
		route: 'Bôi',
		source: 'VN',
		costPrice: 13,
		expiryDate: 1649721600000,
		retailPrice: 25,
	},
	{
		brandName: 'Elossy',
		substance: 'Xylometazoline 0,05%',
		unit: 'Ống',
		group: 'Hô hấp',
		route: 'Nhỏ Giọt',
		source: 'vn',
		costPrice: 5.3,
		expiryDate: 1650931200000,
		retailPrice: 10,
	},
	{
		brandName: 'Dermovate 15g',
		substance: 'Clobeasol propionate 0,05%',
		unit: 'Tuýp',
		group: 'Da Liễu',
		route: 'Bôi',
		source: 'Anh',
		costPrice: 45,
		expiryDate: 1634947200000,
		retailPrice: 65,
	},
	{
		brandName: 'Tatracyclin 1%',
		substance: 'Tatracyclin 1%',
		unit: 'Tuýp',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Bôi',
		source: 'vn',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 10,
	},
	{
		brandName: 'Zytee',
		substance: 'Cholin salicylat + Clorua Benzalkonium',
		unit: 'Tuýp',
		group: 'Khác',
		route: 'Bôi',
		source: 'Ấn Độ',
		costPrice: 23,
		expiryDate: 1657929600000,
		retailPrice: 35,
	},
	{
		brandName: 'Kamistad - Gel N',
		substance: 'Lidocain',
		unit: 'Tuýp',
		group: 'Khác',
		route: 'Bôi',
		source: 'Germany',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 45,
	},
	{
		brandName: 'Eumovate cream',
		substance: 'Clobetasone',
		unit: 'Tuýp',
		group: 'Corticoid',
		route: 'Bôi',
		source: 'Anh',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 35,
	},
	{
		brandName: 'Dipolac ',
		substance: 'Betamethasone 9,6mg + Gentamycin 15mg + Clotrimazole 150mg',
		unit: 'Tuýp',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Bôi',
		source: 'usa',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 30,
	},
	{
		brandName: 'Tamiflu',
		substance: 'Osetamivir 75mg',
		unit: 'Viên',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'ý',
		costPrice: 75,
		expiryDate: 1724803200000,
		retailPrice: 100,
	},
	{
		brandName: 'ACC Cylin',
		substance: 'N - Acetyl -L- Cystein 200mg',
		unit: 'Lọ',
		group: 'Hô hấp',
		route: 'Uống',
		source: 'vn',
		costPrice: 30,
		expiryDate: 1704326400000,
		retailPrice: 70,
	},
	{
		brandName: 'Babycanyl',
		substance: 'Terbutalin sulfat 1,5mg + Guaifenesin',
		unit: 'Lọ',
		group: 'Hô hấp',
		route: 'Uống',
		source: 'vn',
		costPrice: 28,
		expiryDate: 1680307200000,
		retailPrice: 60,
	},
	{
		brandName: 'Legomux',
		substance: 'Ambroxol 6mg/ml',
		unit: 'Lọ',
		group: 'Hô hấp',
		route: 'Nhỏ Giọt',
		source: 'Banglades',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 60,
	},
	{
		brandName: 'Delopedil 60ml',
		substance: 'Desloratadine 0,5mg',
		unit: 'Lọ',
		group: 'Dị ứng',
		route: 'Uống',
		source: 'VN',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 60,
	},
	{
		brandName: 'Nhiệt Smile',
		substance: 'Vitamin c 1000mg + Vitamin PP, B1, B2,B6',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'vn',
		costPrice: 21.5,
		expiryDate: 1640649600000,
		retailPrice: 70,
	},
	{
		brandName: 'OLESOM 100ml',
		substance: 'Ambroxol 30mg/5ml',
		unit: 'Lọ',
		group: 'Hô hấp',
		route: 'Uống',
		source: 'Ấn Độ',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 60,
	},
	{
		brandName: 'Halixol siro100ml',
		substance: 'Ambroxol 15mg/5ml',
		unit: 'Lọ',
		group: 'Hô hấp',
		route: 'Uống',
		source: 'hungary',
		costPrice: 34,
		expiryDate: 1638921600000,
		retailPrice: 70,
	},
	{
		brandName: 'Best GSV 60ml',
		substance: 'Betamethason 3mg + Desclorpheniramin maleat 24mg',
		unit: 'Lọ',
		group: 'Dị ứng',
		route: 'Uống',
		source: 'vn',
		costPrice: 30,
		expiryDate: 1666310400000,
		retailPrice: 60,
	},
	{
		brandName: 'HIDRASEC ',
		substance: 'Racecadotril 10mg',
		unit: 'Gói',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'Pháp',
		costPrice: 4.688,
		expiryDate: 1639267200000,
		retailPrice: 6,
	},
	{
		brandName: 'CLANOZ',
		substance: 'Loratadin 10mg',
		unit: 'Viên',
		group: 'Dị ứng',
		route: 'Uống',
		source: 'vn',
		costPrice: 0.55,
		expiryDate: 1634947200000,
		retailPrice: 1,
	},
	{
		brandName: 'Theralene',
		substance: 'Alimemazine 5mg',
		unit: 'Viên',
		group: 'Dị ứng',
		route: 'Uống',
		source: 'vn',
		costPrice: 0.3,
		expiryDate: -55781308800000,
		retailPrice: 1,
	},
	{
		brandName: 'MEKOCETIN',
		substance: 'Betamethasone 0,5 mg',
		unit: 'Viên',
		group: 'Corticoid',
		route: 'Uống',
		source: 'vn',
		costPrice: 0.175,
		expiryDate: 1638921600000,
		retailPrice: 1,
	},
	{
		brandName: 'Duphalac 15ml/1 gói',
		substance: 'Lactulose 10g',
		unit: 'Gói',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'Hà lan',
		costPrice: 4.65,
		expiryDate: 1651276800000,
		retailPrice: 7,
	},
	{
		brandName: 'PROGERMILA',
		substance: 'Bacillus clausii (TB lợi khuẩn)',
		unit: 'Ống',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'vn',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 7,
	},
	{
		brandName: 'Frazin 10ml',
		substance: 'Thymomodulin 800mg + Zn gluconate 400mg',
		unit: 'Ống',
		group: 'Hô hấp',
		route: 'Uống',
		source: 'vn',
		costPrice: 4.583,
		expiryDate: -55100217600000,
		retailPrice: 8.5,
	},
	{
		brandName: 'Colibasi - BM 5ml',
		substance: 'Bacillus clausii (TB lợi khuẩn)',
		unit: 'Ống',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'vn',
		costPrice: 4.25,
		expiryDate: 1670803200000,
		retailPrice: 7,
	},
	{
		brandName: 'ZENTEL',
		substance: 'Albendazole 200mg',
		unit: 'Gói',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'vn',
		costPrice: 11,
		expiryDate: 1671753600000,
		retailPrice: 20,
	},
	{
		brandName: 'Unafen 100ml',
		substance: 'Ibuprofen 100mg/5ml',
		unit: 'Lọ',
		group: 'Giảm Đau - Hạ Sốt - NSAID',
		route: 'Uống',
		source: 'Ấn độ',
		costPrice: 45,
		expiryDate: 1652140800000,
		retailPrice: 80,
	},
	{
		brandName: 'Bobotic 30ml',
		substance: 'Simeticonum 66,66mg/ml',
		unit: 'Lọ',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'Ba lan',
		costPrice: 53,
		expiryDate: 1657238400000,
		retailPrice: 100,
	},
	{
		brandName: 'Ibupain 100mg/50ml',
		substance: 'Ibuprofen ',
		unit: 'Lọ',
		group: 'Giảm Đau - Hạ Sốt - NSAID',
		route: 'Uống',
		source: 'vn',
		costPrice: 35,
		expiryDate: 1639526400000,
		retailPrice: 70,
	},
	{
		brandName: 'PARACETAMOL - 120',
		substance: 'paracetamol 120mg/60ml',
		unit: 'Lọ',
		group: '',
		route: 'Uống',
		source: 'Malaisia',
		costPrice: 32,
		expiryDate: 1632960000000,
		retailPrice: 52,
	},
	{
		brandName: 'Centrum Kids',
		substance: 'Vitamin + A.Folic + Zn, Mg, P, Ca',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Australia',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 270,
	},
	{
		brandName: 'ORACORTIA',
		substance: 'Triamcinolone 0,1%',
		unit: 'Gói',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Bôi',
		source: 'Thái Lan',
		costPrice: 8.7,
		expiryDate: 1685664000000,
		retailPrice: 15,
	},
	{
		brandName: 'BULOXDINE ',
		substance: 'Ibuprofen 100mg/5ml',
		unit: 'Gói',
		group: 'Giảm Đau - Hạ Sốt - NSAID',
		route: 'Uống',
		source: 'Hàn Quốc',
		costPrice: 4.5,
		expiryDate: 1629331200000,
		retailPrice: 65,
	},
	{
		brandName: 'ORESOL 5,58g',
		substance: 'Glucose 4g + Natri Clorid 0,7g + Natricitrat 0,58g + Kaki clorid 0,3g',
		unit: 'Gói',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'vn',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 1,
	},
	{
		brandName: 'Ibumed 400',
		substance: 'Ibuprofen 400mg',
		unit: 'Vỉ',
		group: 'Giảm Đau - Hạ Sốt - NSAID',
		route: 'Uống',
		source: 'singapore',
		costPrice: 3,
		expiryDate: 1635724800000,
		retailPrice: 10,
	},
	{
		brandName: 'Xitmos',
		substance: 'Thảo dược',
		unit: 'Lọ',
		group: 'Da Liễu',
		route: 'Khác',
		source: 'vn',
		costPrice: 25,
		expiryDate: 1645401600000,
		retailPrice: 50,
	},
	{
		brandName: 'Liver KIDS Siro',
		substance: 'Thảo dược',
		unit: 'Ống',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'VN',
		costPrice: 5,
		expiryDate: -27080352000000,
		retailPrice: 150,
	},
	{
		brandName: 'Redmulti _ Sủi',
		substance: 'Vitamin C + a.Folic + PP, E, B1, B2, B6',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'vn',
		costPrice: 25,
		expiryDate: 1657411200000,
		retailPrice: 40,
	},
	{
		brandName: 'ZoZo _ chanh',
		substance: 'Điện giải',
		unit: 'Chai',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'VN',
		costPrice: 7.5,
		expiryDate: 1638921600000,
		retailPrice: 10,
	},
	{
		brandName: 'ZoZo _ cam',
		substance: 'Điện giải',
		unit: 'Chai',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'vn',
		costPrice: 7.5,
		expiryDate: 1636761600000,
		retailPrice: 10,
	},
	{
		brandName: 'OMSERGY ',
		substance: 'Omeprazole 20mg',
		unit: 'Vỉ',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'Ấn Độ',
		costPrice: 2.85,
		expiryDate: 1656633600000,
		retailPrice: 10,
	},
	{
		brandName: 'Rovanten 50ml',
		substance: 'Cefpodi 40mg/5ml',
		unit: 'Lọ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Banglades',
		costPrice: 78,
		expiryDate: 1626739200000,
		retailPrice: 140,
	},
	{
		brandName: 'AZALOVIR 5g',
		substance: 'Acyclovir 5g',
		unit: 'Tuýp',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Bôi',
		source: 'Ấn Độ',
		costPrice: 6,
		expiryDate: 1702339200000,
		retailPrice: 10,
	},
	{
		brandName: 'HURAZOL ',
		substance: 'Esomeprazole 40mg',
		unit: 'Vỉ',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'vn',
		costPrice: 60,
		expiryDate: 1631750400000,
		retailPrice: 120,
	},
	{
		brandName: 'FEMALTO 30ml',
		substance: 'sắt hữu cơ dạng lỏng',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'vn',
		costPrice: 138,
		expiryDate: 1714780800000,
		retailPrice: 200,
	},
	{
		brandName: 'SAFVEX ',
		substance: 'Bacillus clausii (TB lợi khuẩn)',
		unit: 'Gói',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'VN',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 150,
	},
	{
		brandName: 'HISU Gold _ yến sào',
		substance: 'Vitamin + dinh dưỡng ',
		unit: 'Ống',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'vn',
		costPrice: 2.5,
		expiryDate: 1636761600000,
		retailPrice: 6,
	},
	{
		brandName: 'Monte H4',
		substance: 'Montelukast 4mg',
		unit: 'Vỉ',
		group: 'Hô hấp',
		route: 'Uống',
		source: 'Ấn Độ',
		costPrice: 20,
		expiryDate: 1640908800000,
		retailPrice: 50,
	},
	{
		brandName: 'Acemuc 100',
		substance: 'Acetylcystein 100mg',
		unit: 'Gói',
		group: 'Hô hấp',
		route: 'Uống',
		source: 'vn',
		costPrice: 1.833,
		expiryDate: 1638921600000,
		retailPrice: 4,
	},
	{
		brandName: 'Acemuc 200',
		substance: 'Acetylcystein 200mg',
		unit: 'Gói',
		group: 'Hô hấp',
		route: 'Uống',
		source: 'vn',
		costPrice: 2.5,
		expiryDate: 1638921600000,
		retailPrice: 5,
	},
	{
		brandName: 'AT Fexofenadin 30ml',
		substance: 'Fexofenadin 30mg/5ml',
		unit: 'Lọ',
		group: 'Dị ứng',
		route: 'Uống',
		source: 'vn',
		costPrice: 28,
		expiryDate: 1635724800000,
		retailPrice: 80,
	},
	{
		brandName: 'Stervy Baby 70ml',
		substance: 'Nano bạc + Benzalkonium',
		unit: 'Chai',
		group: 'Hô hấp',
		route: 'Khác',
		source: 'vn',
		costPrice: 18,
		expiryDate: 1698796800000,
		retailPrice: 30,
	},
	{
		brandName: 'An Thanh',
		substance: 'Thảo dược',
		unit: 'Viên',
		group: 'Hô hấp',
		route: 'Ngậm',
		source: 'vn',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 2,
	},
	{
		brandName: 'Vitamin C plus',
		substance: 'vitamin C 100mg',
		unit: 'Ống',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'vn',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 6,
	},
	{
		brandName: 'Erolin 120ml',
		substance: 'Loratadin 1mg/ml',
		unit: 'Lọ',
		group: 'Dị ứng',
		route: 'Uống',
		source: 'hungary',
		costPrice: 18,
		expiryDate: 1634947200000,
		retailPrice: 60,
	},
	{
		brandName: 'Natri clorid 0,9% 10ml',
		substance: 'NaCl ',
		unit: 'Lọ',
		group: 'Khác',
		route: 'Nhỏ Giọt',
		source: 'vn',
		costPrice: 3,
		expiryDate: 1666137600000,
		retailPrice: 5,
	},
	{
		brandName: 'STIPROL 9g',
		substance: 'Glycerol',
		unit: 'Tuýp',
		group: 'Tiêu Hóa',
		route: 'Thụt Hậu Môn',
		source: 'vn',
		costPrice: 5,
		expiryDate: 1687132800000,
		retailPrice: 10,
	},
	{
		brandName: 'STIPROL 4g',
		substance: 'Glycerol',
		unit: 'Tuýp',
		group: 'Tiêu Hóa',
		route: 'Thụt Hậu Môn',
		source: 'vn',
		costPrice: 4,
		expiryDate: 1653868800000,
		retailPrice: 10,
	},
	{
		brandName: 'Baby Balsam',
		substance: 'Nha đam, dầu Dừa, nước hoa Oải Hương',
		unit: 'Lọ',
		group: 'Da Liễu',
		route: 'Bôi',
		source: 'Australia',
		costPrice: 135,
		expiryDate: 1635724800000,
		retailPrice: 200,
	},
	{
		brandName: 'Studex _ Hoa tai bấm tự động',
		substance: '',
		unit: '',
		group: 'Khác',
		route: 'Khác',
		source: 'Mexico',
		costPrice: 130,
		expiryDate: 1634342400000,
		retailPrice: 230,
	},
	{
		brandName: 'Microlife _ Bấm trán',
		substance: 'Nhiệt kế điện tử',
		unit: 'Chiếc',
		group: 'Khác',
		route: 'Khác',
		source: 'thuỵ điển',
		costPrice: 0,
		expiryDate: -27080352000000,
		retailPrice: 870,
	},
	{
		brandName: 'Dr.Frei _ kẹp nách',
		substance: 'Nhiệt kế điện tử',
		unit: 'Chiếc',
		group: 'Khác',
		route: 'Khác',
		source: 'Đức',
		costPrice: 55,
		expiryDate: -27080352000000,
		retailPrice: 100,
	},
	{
		brandName: 'Nebusal spray Baby',
		substance: 'Nước muối biển ưu trương',
		unit: 'Lọ',
		group: 'Hô hấp',
		route: 'Xịt',
		source: 'vn',
		costPrice: 80,
		expiryDate: 1632960000000,
		retailPrice: 100,
	},
	{
		brandName: 'Cetaphil baby _ sữa tắm và gội',
		substance: ' Calendula hữu cơ',
		unit: 'Chai',
		group: 'Da Liễu',
		route: 'Khác',
		source: 'Đức',
		costPrice: 0,
		expiryDate: -27080352000000,
		retailPrice: 200,
	},
	{
		brandName: 'bình rửa mũi NASAL COLL',
		substance: 'Nước muối biển ưu trương',
		unit: 'Lọ',
		group: 'Khác',
		route: 'Khác',
		source: 'vn',
		costPrice: 50,
		expiryDate: 1739923200000,
		retailPrice: 100,
	},
	{
		brandName: 'Jack N\'Jill',
		substance: 'kem đánh răng',
		unit: 'Tuýp',
		group: 'Khác',
		route: 'Khác',
		source: 'USA',
		costPrice: 80,
		expiryDate: 1688860800000,
		retailPrice: 150,
	},
	{
		brandName: 'Intima _ Ziaja (Lan Chuông)',
		substance: 'Dung dịch VSPN',
		unit: 'Lọ',
		group: 'Khác',
		route: 'Khác',
		source: 'Ba lan',
		costPrice: 70,
		expiryDate: 1651276800000,
		retailPrice: 150,
	},
	{
		brandName: 'Intima _ Ziaja (Viêm nhẹ)',
		substance: 'Dung dịch VSPN _ hồng',
		unit: 'Lọ',
		group: 'Khác',
		route: 'Khác',
		source: 'Ba lan',
		costPrice: 85,
		expiryDate: 1638921600000,
		retailPrice: 150,
	},
	{
		brandName: 'Intima _ Ziaja (Viêm nặng)',
		substance: 'Dung dịch VSPN _ Xanh nhạt',
		unit: 'Lọ',
		group: 'Khác',
		route: 'Khác',
		source: 'Ba lan',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 150,
	},
	{
		brandName: 'Intima _ Ziaja (Dưỡng ẩm)',
		substance: 'Dung dịch VSPN _ Xanh đậm',
		unit: 'Lọ',
		group: 'Khác',
		route: 'Khác',
		source: 'Ba lan',
		costPrice: 85,
		expiryDate: 1638921600000,
		retailPrice: 150,
	},
	{
		brandName: 'Intima _ Ziaja (chống viêm)',
		substance: 'Dung dịch VSPN _ Da cam',
		unit: 'Lọ',
		group: 'Khác',
		route: 'Khác',
		source: 'Ba lan',
		costPrice: 70,
		expiryDate: 1651276800000,
		retailPrice: 150,
	},
	{
		brandName: 'Intima _ Ziaja (Cúc la mã)',
		substance: 'Dung dịch VSPN',
		unit: 'Lọ',
		group: 'Khác',
		route: 'Khác',
		source: 'Ba lan',
		costPrice: 70,
		expiryDate: 1651276800000,
		retailPrice: 150,
	},
	{
		brandName: 'Nhũ tương dưỡng ẩm _ Ziaja',
		substance: 'Urea 1%',
		unit: 'Chai',
		group: 'Da Liễu',
		route: 'Bôi',
		source: 'Ba lan',
		costPrice: 200,
		expiryDate: 1638921600000,
		retailPrice: 350,
	},
	{
		brandName: 'Kem dưỡng ẩm _ Mocznik 3% _ Ziaja',
		substance: 'Urea 3%',
		unit: 'Tuýp',
		group: 'Da Liễu',
		route: 'Bôi',
		source: 'Ba lan',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 280,
	},
	{
		brandName: 'Kem dưỡng ẩm _ Mocznik 15% _ Ziaja',
		substance: 'Urea 15%',
		unit: 'Tuýp',
		group: 'Da Liễu',
		route: 'Bôi',
		source: 'Ba lan',
		costPrice: 135,
		expiryDate: 1638921600000,
		retailPrice: 230,
	},
	{
		brandName: 'Kem dưỡng ẩm _ AZS 5% _ Ziaja',
		substance: 'Urea 5%',
		unit: 'Tuýp',
		group: 'Da Liễu',
		route: 'Bôi',
		source: 'Ba lan',
		costPrice: 130,
		expiryDate: 1638921600000,
		retailPrice: 270,
	},
	{
		brandName: 'Kem phục hồi da _ Bioderma',
		substance: '',
		unit: 'Tuýp',
		group: 'Da Liễu',
		route: 'Bôi',
		source: 'Pháp',
		costPrice: 180,
		expiryDate: 1680134400000,
		retailPrice: 300,
	},
	{
		brandName: 'xịt muỗi _ Vape Skin',
		substance: '',
		unit: 'Chai',
		group: 'Da Liễu',
		route: 'Xịt',
		source: 'Nhật Bản',
		costPrice: 125,
		expiryDate: -27080352000000,
		retailPrice: 160,
	},
	{
		brandName: 'Kem dưỡng ẩm _ Vaseline',
		substance: '',
		unit: 'Lọ',
		group: 'Da Liễu',
		route: 'Bôi',
		source: 'USA',
		costPrice: 0,
		expiryDate: -27080352000000,
		retailPrice: 80,
	},
	{
		brandName: 'Kem bôi hăm _ Sudocrem',
		substance: 'ZinC oxide, Benzyl alcohol, Banzyl benzoate, Benzyl cinamate',
		unit: 'Lọ',
		group: 'Da Liễu',
		route: 'Bôi',
		source: 'Ailen',
		costPrice: 70,
		expiryDate: 1680825600000,
		retailPrice: 100,
	},
	{
		brandName: 'Meiact _ Fine Granules',
		substance: 'Cefditoren 50mg',
		unit: 'Gói',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Nhật Bản',
		costPrice: 20.095,
		expiryDate: 1685491200000,
		retailPrice: 27,
	},
	{
		brandName: 'Test Cúm A & B',
		substance: '',
		unit: 'Cái',
		group: 'Khác',
		route: 'Khác',
		source: 'Hàn Quốc',
		costPrice: 75,
		expiryDate: 1643587200000,
		retailPrice: 120,
	},
	{
		brandName: 'Laforin ỔI',
		substance: 'nước súc miệng',
		unit: 'Chai',
		group: 'Khác',
		route: 'Khác',
		source: 'vn',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 115,
	},
	{
		brandName: 'ZENSALBU 2,5mg/2,5ml',
		substance: 'Salbutamol ',
		unit: 'Ống',
		group: 'Hô hấp',
		route: 'Xịt',
		source: 'vn',
		costPrice: 4.41,
		expiryDate: 1636761600000,
		retailPrice: 8,
	},
	{
		brandName: 'ZENSONID 0,5mg/2ml',
		substance: 'Budesonid',
		unit: 'Ống',
		group: 'Hô hấp',
		route: 'Xịt',
		source: 'vn',
		costPrice: 12.6,
		expiryDate: 1636761600000,
		retailPrice: 16,
	},
	{
		brandName: 'Combartrin _ tẩy giun',
		substance: 'pyrantel',
		unit: 'Vỉ',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'Australia',
		costPrice: 66,
		expiryDate: 1651276800000,
		retailPrice: 90,
	},
	{
		brandName: 'TheKatadexan',
		substance: 'Neomycin + Dexamethason',
		unit: 'Ống',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Nhỏ Giọt',
		source: 'vn',
		costPrice: 15,
		expiryDate: 1672963200000,
		retailPrice: 30,
	},
	{
		brandName: 'Zitromax 200mg/5ml',
		substance: 'azithromicin',
		unit: 'Lọ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'ý',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 140,
	},
	{
		brandName: 'Smecta',
		substance: 'Diosmectite',
		unit: 'Gói',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'Pháp',
		costPrice: 3.4,
		expiryDate: 1664582400000,
		retailPrice: 5,
	},
	{
		brandName: 'Medilices ',
		substance: 'Ceftirizine BP 10mg',
		unit: 'Viên',
		group: 'Dị ứng',
		route: 'Uống',
		source: 'Ấn Độ',
		costPrice: 0.2,
		expiryDate: 1649030400000,
		retailPrice: 0.5,
	},
	{
		brandName: 'Paracetamol Kabi 1000mg',
		substance: 'Paracetamol',
		unit: 'Lọ',
		group: 'Giảm Đau - Hạ Sốt - NSAID',
		route: 'Tiêm',
		source: 'VN',
		costPrice: 30,
		expiryDate: 1647129600000,
		retailPrice: 50,
	},
	{
		brandName: 'Clabact 500',
		substance: 'Clarythromycin 500mg',
		unit: 'Viên',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'VN',
		costPrice: 4.8,
		expiryDate: 1658966400000,
		retailPrice: 8,
	},
	{
		brandName: 'Doliprame 2,4% 100ml',
		substance: 'paracetamol 2,4g',
		unit: 'Lọ',
		group: 'Giảm Đau - Hạ Sốt - NSAID',
		route: 'Uống',
		source: 'Pháp',
		costPrice: 95,
		expiryDate: 1682812800000,
		retailPrice: 160,
	},
	{
		brandName: 'D - Fluoretten 50 I.E.',
		substance: 'Vitamin D3 + Florua',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Đức',
		costPrice: 130,
		expiryDate: 1719619200000,
		retailPrice: 200,
	},
	{
		brandName: 'Mini Drops DHA 50ml',
		substance: 'DHA',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'UK',
		costPrice: 205,
		expiryDate: 1635724800000,
		retailPrice: 300,
	},
	{
		brandName: 'BioCare Nutrisorb ZinC 30ml',
		substance: 'Kẽm',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'UK',
		costPrice: 225,
		expiryDate: 1643587200000,
		retailPrice: 320,
	},
	{
		brandName: 'Ginkgo 6000 THOMPSON\'S',
		substance: 'ginko 6000',
		unit: 'Lọ',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'Australia',
		costPrice: 280,
		expiryDate: 1638921600000,
		retailPrice: 400,
	},
	{
		brandName: 'chíp chíp',
		substance: 'vintamin D',
		unit: 'Túi',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'VN',
		costPrice: 5,
		expiryDate: -27080352000000,
		retailPrice: 10,
	},
	{
		brandName: 'Doromax 200',
		substance: 'azithromycin 200mg',
		unit: 'Gói',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'VN',
		costPrice: 4,
		expiryDate: 1682553600000,
		retailPrice: 10,
	},
	{
		brandName: 'Lấy ráy tai - phát sáng',
		substance: '',
		unit: '',
		group: 'Khác',
		route: 'Khác',
		source: 'VN',
		costPrice: 6,
		expiryDate: 1623196800000,
		retailPrice: 15,
	},
	{
		brandName: 'Mask khí dung',
		substance: '',
		unit: 'Chiếc',
		group: 'Khác',
		route: 'Khác',
		source: 'VN',
		costPrice: 15,
		expiryDate: 1636761600000,
		retailPrice: 20,
	},
	{
		brandName: 'Máy khí dung _ Respizer',
		substance: '',
		unit: 'Chiếc',
		group: 'Khác',
		route: 'Khác',
		source: 'Đài Loan',
		costPrice: 0.1,
		expiryDate: -27080352000000,
		retailPrice: 550,
	},
	{
		brandName: 'efferalgan 500 _ Sủi',
		substance: 'paracetamol 500mg',
		unit: 'Viên',
		group: 'Giảm Đau - Hạ Sốt - NSAID',
		route: 'Khác',
		source: 'Pháp',
		costPrice: 2.813,
		expiryDate: 1670803200000,
		retailPrice: 5,
	},
	{
		brandName: 'BioGaia _ Pháp',
		substance: 'lactobacillus ',
		unit: 'Tuýp',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'Pháp',
		costPrice: 230,
		expiryDate: 1635724800000,
		retailPrice: 320,
	},
	{
		brandName: 'Laxdokid- ăn ngon',
		substance: 'Vitamin',
		unit: 'Hộp',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Vn',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 120,
	},
	{
		brandName: 'Biogaia - nga',
		substance: 'Lactobacillus reuteri',
		unit: 'Ống',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'Nga',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 360,
	},
	{
		brandName: 'Lucas',
		substance: 'Chiết xuất đu đủ',
		unit: 'Tuýp',
		group: 'Da Liễu',
		route: 'Bôi',
		source: 'Australia',
		costPrice: 68,
		expiryDate: 1703980800000,
		retailPrice: 150,
	},
	{
		brandName: 'Xịt tan ráy clean ears',
		substance: 'Tan ráy tai',
		unit: 'Lọ',
		group: 'Khác',
		route: 'Xịt',
		source: 'Australia',
		costPrice: 195,
		expiryDate: 1702339200000,
		retailPrice: 270,
	},
	{
		brandName: 'Trị nứt đầu ti',
		substance: 'Mỡ cừu',
		unit: 'Tuýp',
		group: 'Khác',
		route: '',
		source: 'Newzelan',
		costPrice: 80,
		expiryDate: 1690761600000,
		retailPrice: 130,
	},
	{
		brandName: 'Calcium milk kid HTC',
		substance: 'Calci ngto 65mg+D3 100UI',
		unit: 'Lọ',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'Australia',
		costPrice: 150,
		expiryDate: 1693440000000,
		retailPrice: 230,
	},
	{
		brandName: 'Vita gummies- nature\'s way',
		substance: 'Calcium phosphat 100mg+D3 200UI',
		unit: 'Lọ',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'Australia',
		costPrice: 165,
		expiryDate: 1638921600000,
		retailPrice: 240,
	},
	{
		brandName: 'Verni flour',
		substance: 'Flour',
		unit: 'Chiếc',
		group: 'Khác',
		route: 'Bôi',
		source: 'Anh',
		costPrice: 50,
		expiryDate: -27080352000000,
		retailPrice: 80,
	},
	{
		brandName: 'Sữa tắm thảo dược ',
		substance: 'Thảo dược',
		unit: 'Lọ',
		group: 'Khác',
		route: 'Khác',
		source: 'VN',
		costPrice: 95,
		expiryDate: 1665705600000,
		retailPrice: 140,
	},
	{
		brandName: 'Sữa tắm thảo dược gói',
		substance: 'Thảo dược',
		unit: 'Gói',
		group: 'Khác',
		route: 'Khác',
		source: 'VN',
		costPrice: 4.75,
		expiryDate: 1648512000000,
		retailPrice: 8,
	},
	{
		brandName: 'Osteocare Calci',
		substance: 'Calci, magie, Zn',
		unit: 'Lọ',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'Anh',
		costPrice: 165,
		expiryDate: 1635724800000,
		retailPrice: 290,
	},
	{
		brandName: 'Oralcortia',
		substance: 'Triamcinolone',
		unit: 'Tuýp',
		group: 'Khác',
		route: 'Bôi',
		source: '',
		costPrice: 30,
		expiryDate: 1695772800000,
		retailPrice: 60,
	},
	{
		brandName: 'Elevit bầu',
		substance: 'Vitamin',
		unit: 'Lọ',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: '',
		costPrice: 1040,
		expiryDate: 1707350400000,
		retailPrice: 1200,
	},
	{
		brandName: 'Bioisland DHA bầu',
		substance: 'Dha',
		unit: 'Viên',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: '',
		costPrice: 340,
		expiryDate: 1682208000000,
		retailPrice: 450,
	},
	{
		brandName: 'Motilium',
		substance: 'Domperidom',
		unit: 'Lọ',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'Thái lan',
		costPrice: 26,
		expiryDate: 1685664000000,
		retailPrice: 50,
	},
	{
		brandName: 'Rinofil',
		substance: 'Desloratandin',
		unit: 'Lọ',
		group: 'Dị ứng',
		route: 'Uống',
		source: 'Chile',
		costPrice: 25,
		expiryDate: 1639526400000,
		retailPrice: 50,
	},
	{
		brandName: 'Heathy plex ',
		substance: 'D3400ui ,k2 10ucg',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Italia',
		costPrice: 175,
		expiryDate: 1719619200000,
		retailPrice: 280,
	},
	{
		brandName: 'Claminat',
		substance: 'Amoxicilin 500mg,clavulanic 62,5mg',
		unit: 'Gói',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Việt nam',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 12,
	},
	{
		brandName: 'Sữa tắm buchen',
		substance: 'Thảo dược',
		unit: 'Lọ',
		group: 'Khác',
		route: 'Khác',
		source: 'Đức',
		costPrice: 70,
		expiryDate: 1651017600000,
		retailPrice: 140,
	},
	{
		brandName: 'Lăn khử mùi etiaxil',
		substance: 'K',
		unit: 'Lọ',
		group: 'Da Liễu',
		route: 'Bôi',
		source: 'Pháp',
		costPrice: 170,
		expiryDate: 1685836800000,
		retailPrice: 220,
	},
	{
		brandName: 'Menevit',
		substance: 'Vitamin',
		unit: 'Hộp',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'Bayer',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 1150,
	},
	{
		brandName: 'Bostocef',
		substance: 'Cefdinir 25mg/ml',
		unit: 'Lọ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Vn liên doanh mỹ',
		costPrice: 90,
		expiryDate: 1670803200000,
		retailPrice: 150,
	},
	{
		brandName: 'Kefodime',
		substance: 'Cefotaxime',
		unit: '',
		group: 'Kháng sinh - Kháng Virus',
		route: '',
		source: '',
		costPrice: 45,
		expiryDate: 1656633600000,
		retailPrice: 90,
	},
	{
		brandName: 'Noviceftrin 2g',
		substance: 'Ceftriaxone 2g',
		unit: 'Lọ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Tiêm',
		source: 'Thụy điển',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 85,
	},
	{
		brandName: 'Vitsball',
		substance: '',
		unit: 'Ống',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Vn',
		costPrice: 3,
		expiryDate: 1702339200000,
		retailPrice: 5,
	},
	{
		brandName: 'Novozinc',
		substance: 'Kẽm gluconat ( <=> 20g/ml)',
		unit: 'Viên',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Việt nam',
		costPrice: 85,
		expiryDate: 1632873600000,
		retailPrice: 150,
	},
	{
		brandName: 'Elevit bú',
		substance: 'Vitamin',
		unit: 'Viên',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'Bayer',
		costPrice: 450,
		expiryDate: 1688083200000,
		retailPrice: 550,
	},
	{
		brandName: 'Prospan gói',
		substance: 'Cao khô lá thường xuân',
		unit: 'Gói',
		group: 'Hô hấp',
		route: 'Uống',
		source: 'Đức',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 230,
	},
	{
		brandName: 'Black more zinc',
		substance: 'Zinc 25mg,',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Australia',
		costPrice: 220,
		expiryDate: 1688860800000,
		retailPrice: 360,
	},
	{
		brandName: 'Pregnacare bú ',
		substance: 'Vitamin cho phụ nữ sau sinh',
		unit: 'Hộp',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Anh',
		costPrice: 300,
		expiryDate: 1634342400000,
		retailPrice: 450,
	},
	{
		brandName: 'Black more tinh dầu hoa anh thảo',
		substance: 'Tinh dầu hoa anh thảo',
		unit: 'Lọ',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'Australia',
		costPrice: 440,
		expiryDate: 1638921600000,
		retailPrice: 580,
	},
	{
		brandName: 'Bio marine collagen',
		substance: 'Collagen 2000',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Australia',
		costPrice: 350,
		expiryDate: 1717113600000,
		retailPrice: 550,
	},
	{
		brandName: 'Fenano',
		substance: 'Sắt 4omg',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Vn',
		costPrice: 110,
		expiryDate: 1713571200000,
		retailPrice: 210,
	},
	{
		brandName: 'Sancoba',
		substance: 'Vitaminb',
		unit: 'Lọ',
		group: 'Khác',
		route: 'Nhỏ Giọt',
		source: 'Nhật',
		costPrice: 51.5,
		expiryDate: 1638921600000,
		retailPrice: 90,
	},
	{
		brandName: 'Sữa tắm Penaten',
		substance: 'Sữa tắm cảm cúm',
		unit: 'Lọ',
		group: 'Da Liễu',
		route: 'Khác',
		source: 'Gree',
		costPrice: 0,
		expiryDate: -27080352000000,
		retailPrice: 210,
	},
	{
		brandName: 'Arginin',
		substance: 'Aspartat, orginin',
		unit: 'Hộp',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'Vn',
		costPrice: 30,
		expiryDate: 1719619200000,
		retailPrice: 60,
	},
	{
		brandName: 'Vitamin e',
		substance: 'Vitamin e 500ui',
		unit: 'Lọ',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'Úc',
		costPrice: 300,
		expiryDate: 1634342400000,
		retailPrice: 430,
	},
	{
		brandName: 'E đỏ nga',
		substance: 'Vitamin e 400mg',
		unit: 'Lọ',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'Nga',
		costPrice: 160,
		expiryDate: 1687996800000,
		retailPrice: 230,
	},
	{
		brandName: 'hút mũi',
		substance: 'dụng cụ',
		unit: 'Chiếc',
		group: 'Khác',
		route: 'Khác',
		source: 'VN',
		costPrice: 18,
		expiryDate: 1632700800000,
		retailPrice: 25,
	},
	{
		brandName: 'terpin codein',
		substance: 'terpin hydrat+ codein',
		unit: 'Vỉ',
		group: 'Hô hấp',
		route: 'Uống',
		source: 'VN',
		costPrice: 8.5,
		expiryDate: 1670803200000,
		retailPrice: 20,
	},
	{
		brandName: 'agiclovir 400mg',
		substance: 'Acyclovir 400mg',
		unit: 'Vỉ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: '',
		costPrice: 20,
		expiryDate: 1670803200000,
		retailPrice: 60,
	},
	{
		brandName: 'effe codein',
		substance: 'Paracetamol+ codein',
		unit: 'Viên',
		group: 'Giảm Đau - Hạ Sốt - NSAID',
		route: 'Uống',
		source: '',
		costPrice: 4.25,
		expiryDate: 1670803200000,
		retailPrice: 10,
	},
	{
		brandName: 'novita ',
		substance: 'multivitamin',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'VN',
		costPrice: 90,
		expiryDate: -27080352000000,
		retailPrice: 120,
	},
	{
		brandName: 'Ostelin kids Calcium vit D3 LIQUID',
		substance: 'CALCI 100MG, D3',
		unit: 'Chai',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Australia',
		costPrice: 255,
		expiryDate: 1635724800000,
		retailPrice: 350,
	},
	{
		brandName: 'HIDRASEC 30MG',
		substance: 'Racecadotril 30mg',
		unit: 'Gói',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'Pháp',
		costPrice: 5.4,
		expiryDate: 1639267200000,
		retailPrice: 7,
	},
	{
		brandName: 'INFOSGO',
		substance: 'CHẤT XƠ',
		unit: 'Gói',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'VN',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 0,
	},
	{
		brandName: 'FLUCISTAD',
		substance: 'ACID FUCIDIC',
		unit: 'Tuýp',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Bôi',
		source: 'VN',
		costPrice: 27,
		expiryDate: 1702339200000,
		retailPrice: 40,
	},
	{
		brandName: 'GEL BẠC',
		substance: 'Nano bạc',
		unit: 'Tuýp',
		group: 'Da Liễu',
		route: 'Bôi',
		source: 'VN',
		costPrice: 30,
		expiryDate: 1702339200000,
		retailPrice: 60,
	},
	{
		brandName: 'KEM NẺ DEXERY',
		substance: 'DƯỠNG ẨM',
		unit: 'Tuýp',
		group: 'Da Liễu',
		route: 'Bôi',
		source: 'Pháp',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 160,
	},
	{
		brandName: 'Vita gummies- nature\'s way vit C , Kẽm',
		substance: 'vit C +kẽm',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Australia',
		costPrice: 165,
		expiryDate: 1638921600000,
		retailPrice: 240,
	},
	{
		brandName: 'akudinir 300mg',
		substance: 'cefdinir 300mg',
		unit: 'Vỉ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Ấn Độ',
		costPrice: 48,
		expiryDate: 1702339200000,
		retailPrice: 100,
	},
	{
		brandName: 'Fleming 1g ',
		substance: 'Amoxicillin + clavulanic',
		unit: 'Hộp',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Ấn độ',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 130,
	},
	{
		brandName: 'PROGERMILA ',
		substance: 'Bacillus clausi',
		unit: 'Ống',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'Vn',
		costPrice: 5.75,
		expiryDate: 1639526400000,
		retailPrice: 7,
	},
	{
		brandName: 'Bông ngoáy tai sơ sinh',
		substance: 'Bông',
		unit: 'Lọ',
		group: 'Khác',
		route: 'Khác',
		source: 'Vn',
		costPrice: 30,
		expiryDate: 1635724800000,
		retailPrice: 35,
	},
	{
		brandName: 'Bông ngoáy tai ',
		substance: 'Bông',
		unit: 'Lọ',
		group: 'Khác',
		route: 'Khác',
		source: 'Vn',
		costPrice: 20,
		expiryDate: 1635292800000,
		retailPrice: 30,
	},
	{
		brandName: 'Gadopax',
		substance: 'Betaglucan',
		unit: 'Lọ',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'Slovenia',
		costPrice: 165,
		expiryDate: 1638921600000,
		retailPrice: 280,
	},
	{
		brandName: 'Vitamin d3k2 đức',
		substance: 'D3 200ui k2 10ug',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'Đức',
		costPrice: 260,
		expiryDate: 1635724800000,
		retailPrice: 340,
	},
	{
		brandName: 'Muối uống coldcalm ',
		substance: 'Vi lượng đồng căn',
		unit: 'Ống',
		group: 'Hô hấp',
		route: 'Uống',
		source: 'Mỹ',
		costPrice: 7.833,
		expiryDate: 1635724800000,
		retailPrice: 320,
	},
	{
		brandName: 'Nhỏ mũi fysoline vàng kháng viêm',
		substance: 'Thảo dược',
		unit: 'Ống',
		group: 'Khác',
		route: 'Nhỏ Giọt',
		source: 'Pháp',
		costPrice: 5,
		expiryDate: 1635724800000,
		retailPrice: 160,
	},
	{
		brandName: 'Moxieye',
		substance: 'Moxifloxacin',
		unit: 'Lọ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Nhỏ Giọt',
		source: 'Cpc1',
		costPrice: 0,
		expiryDate: 1635724800000,
		retailPrice: 90,
	},
	{
		brandName: 'Fosmitic',
		substance: 'Fomycin',
		unit: 'Lọ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Nhỏ Giọt',
		source: 'Cpc1',
		costPrice: 45,
		expiryDate: 1635724800000,
		retailPrice: 70,
	},
	{
		brandName: 'Sachi eye',
		substance: 'VitaminA,taurin,lutein,dầu đậu núi',
		unit: 'Hộp',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'Vn',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 160,
	},
	{
		brandName: 'Xịt sâu răng midkid',
		substance: '',
		unit: 'Lọ',
		group: 'Khác',
		route: 'Uống',
		source: 'Vn',
		costPrice: 135,
		expiryDate: 1636761600000,
		retailPrice: 190,
	},
	{
		brandName: 'Cefaclor 125mg/5ml',
		substance: 'Cefaclor',
		unit: 'Lọ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Malaysia',
		costPrice: 80,
		expiryDate: 1636761600000,
		retailPrice: 120,
	},
	{
		brandName: 'Dutixim 200mg',
		substance: 'Cefpodoxime 200mg',
		unit: 'Vỉ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Vn',
		costPrice: 50,
		expiryDate: 1636761600000,
		retailPrice: 100,
	},
	{
		brandName: 'Basultam 2g',
		substance: 'Cefoperazol 1g +sulbactam 1g',
		unit: 'Ống',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Tiêm',
		source: '',
		costPrice: 35,
		expiryDate: 1636761600000,
		retailPrice: 75,
	},
	{
		brandName: 'Bacsulfo 1g ',
		substance: 'Cefoperazol 1g',
		unit: 'Ống',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Tiêm',
		source: '',
		costPrice: 25,
		expiryDate: 1636761600000,
		retailPrice: 50,
	},
	{
		brandName: 'Son dưỡng môi nhật ( micky)',
		substance: '',
		unit: 'Viên',
		group: '',
		route: 'Uống',
		source: '',
		costPrice: 65,
		expiryDate: 1638921600000,
		retailPrice: 0,
	},
	{
		brandName: 'Son bioderma',
		substance: '',
		unit: 'Tuýp',
		group: 'Khác',
		route: 'Bôi',
		source: 'Pháp',
		costPrice: 36,
		expiryDate: 1638921600000,
		retailPrice: 70,
	},
	{
		brandName: 'Klamentin 875/125',
		substance: 'Amoxicilin 875+ acid klavulanic 125',
		unit: 'Vỉ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Vn',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 70,
	},
	{
		brandName: 'Diacerein 50mg',
		substance: 'Diacerein 50mg',
		unit: 'Viên',
		group: 'Cơ Xương Khớp',
		route: 'Uống',
		source: 'Vn',
		costPrice: 3.2,
		expiryDate: 1638921600000,
		retailPrice: 5,
	},
	{
		brandName: 'Gabcure',
		substance: 'Gabapentin 300mg ',
		unit: 'Viên',
		group: 'Thần Kinh',
		route: 'Uống',
		source: '',
		costPrice: 4,
		expiryDate: 1638921600000,
		retailPrice: 7,
	},
	{
		brandName: 'Soslac',
		substance: 'Dipolac',
		unit: 'Tuýp',
		group: 'Da Liễu',
		route: 'Bôi',
		source: 'Vn',
		costPrice: 17,
		expiryDate: 1638921600000,
		retailPrice: 30,
	},
	{
		brandName: 'Neomezol ',
		substance: 'Neomycin+ betamethasone',
		unit: 'Lọ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Nhỏ Giọt',
		source: 'Vn',
		costPrice: 16,
		expiryDate: 1638921600000,
		retailPrice: 30,
	},
	{
		brandName: 'Sát khuẩn tay',
		substance: 'Cồn',
		unit: 'Lọ',
		group: 'Khác',
		route: 'Khác',
		source: 'Vn',
		costPrice: 65,
		expiryDate: 1639526400000,
		retailPrice: 90,
	},
	{
		brandName: 'Khẩu trang người lớn darin',
		substance: 'Kt',
		unit: 'Hộp',
		group: 'Khác',
		route: 'Khác',
		source: 'Vn',
		costPrice: 28,
		expiryDate: 1639526400000,
		retailPrice: 40,
	},
	{
		brandName: 'Khẩu trang trẻ em darin',
		substance: 'Kt',
		unit: 'Hộp',
		group: 'Khác',
		route: 'Khác',
		source: 'Vn',
		costPrice: 27,
		expiryDate: 1639526400000,
		retailPrice: 40,
	},
	{
		brandName: 'Khẩu trang người lớn ami',
		substance: 'Kt',
		unit: 'Hộp',
		group: 'Khác',
		route: 'Khác',
		source: 'Vn',
		costPrice: 30,
		expiryDate: 1639526400000,
		retailPrice: 45,
	},
	{
		brandName: 'Ocean d3 k2',
		substance: 'D3 400Ui, k2 25ug',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Xịt',
		source: 'Turkey',
		costPrice: 185,
		expiryDate: 1639526400000,
		retailPrice: 295,
	},
	{
		brandName: 'Son trẻ em',
		substance: 'dưỡng ẩm môi',
		unit: 'Tuýp',
		group: 'Khác',
		route: 'Bôi',
		source: 'Nhật Bản',
		costPrice: 65,
		expiryDate: 1639526400000,
		retailPrice: 100,
	},
	{
		brandName: 'imubron',
		substance: '13 loại vi khuẩn',
		unit: 'Vỉ',
		group: 'Khác',
		route: 'Uống',
		source: 'Đức',
		costPrice: 110,
		expiryDate: 1640649600000,
		retailPrice: 150,
	},
	{
		brandName: 'smart air 4mg',
		substance: 'Montelukast 4mg',
		unit: 'Hộp',
		group: 'Khác',
		route: 'Uống',
		source: 'mỹ',
		costPrice: 50,
		expiryDate: 1640649600000,
		retailPrice: 70,
	},
	{
		brandName: 'niflad es',
		substance: 'amoxicillin 600mg + 42.5 clavilanic',
		unit: 'Viên',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'việt nam',
		costPrice: 7.3,
		expiryDate: 1726272000000,
		retailPrice: 10,
	},
	{
		brandName: 'bilclmos 312mg/5ml',
		substance: 'amoxicilin 250mg+ clavulanic 62.5mg',
		unit: 'Lọ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Ấn Độ',
		costPrice: 120,
		expiryDate: -27080352000000,
		retailPrice: 180,
	},
	{
		brandName: 'Tedavi 457mg/5ml',
		substance: 'amoxicilin 400mg+ clavulanic 57mg',
		unit: 'Lọ',
		group: 'Kháng sinh - Kháng Virus',
		route: 'Uống',
		source: 'Ấn Độ',
		costPrice: 120,
		expiryDate: 1756512000000,
		retailPrice: 190,
	},
	{
		brandName: 'natrulax',
		substance: 'sorbitol+ FOS+thảo dược',
		unit: 'Ống',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'việt nam',
		costPrice: 3.9,
		expiryDate: 1742860800000,
		retailPrice: 7,
	},
	{
		brandName: 'BUONA Nebial 3%',
		substance: 'muối 3%',
		unit: 'Ống',
		group: 'Khác',
		route: 'Nhỏ Giọt',
		source: 'italya',
		costPrice: 9,
		expiryDate: -27080352000000,
		retailPrice: 12,
	},
	{
		brandName: 'BUONA circadiem( ngủ ngon)',
		substance: 'melatoin 1mg/4 giọt',
		unit: 'Lọ',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'italya',
		costPrice: 187,
		expiryDate: -27080352000000,
		retailPrice: 260,
	},
	{
		brandName: 'pemolip (cefditoren 50mg)',
		substance: 'cefditoren 50mg',
		unit: 'Gói',
		group: 'Kháng sinh - Kháng Virus',
		route: '',
		source: 'việt nam',
		costPrice: 9,
		expiryDate: 1712707200000,
		retailPrice: 15,
	},
	{
		brandName: 'PEGinpol',
		substance: 'macrogol 3350',
		unit: 'Gói',
		group: 'Tiêu Hóa',
		route: 'Uống',
		source: 'italya',
		costPrice: 11,
		expiryDate: 1745971200000,
		retailPrice: 13,
	},
	{
		brandName: 'BUONA ferroduo ( sắt)',
		substance: 'sắt 1mg/1 giọt',
		unit: 'Lọ',
		group: '',
		route: 'Uống',
		source: 'italya',
		costPrice: 181,
		expiryDate: 1748563200000,
		retailPrice: 215,
	},
	{
		brandName: 'imochild d3k2dha',
		substance: '400UI d3 + k222.5ug+ dha 5ug',
		unit: 'Lọ',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'pháp',
		costPrice: 200,
		expiryDate: 1759190400000,
		retailPrice: 300,
	},
	{
		brandName: 'ostelin d3 liquid',
		substance: '200ui d3/ 0,5ml',
		unit: 'Lọ',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'úc',
		costPrice: 95,
		expiryDate: 1714435200000,
		retailPrice: 150,
	},
	{
		brandName: 'gummies vita calci+d',
		substance: '100mg calci+ 200 UI d3 / viên',
		unit: 'Lọ',
		group: 'Thực Phẩm Chức Năng',
		route: 'Uống',
		source: 'úc',
		costPrice: 175,
		expiryDate: 1688083200000,
		retailPrice: 240,
	},
	{
		brandName: 'calci lunik',
		substance: '(calici 547.4mg+ magnes 50mg+ d3 3.75mcg+k2 20mcg)/10ml',
		unit: 'Lọ',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'italya',
		costPrice: 0,
		expiryDate: null,
		retailPrice: 395,
	},
	{
		brandName: 'Montenuzyd 10mg',
		substance: 'montelukast 10mg',
		unit: 'Vỉ',
		group: 'Hô hấp',
		route: 'Uống',
		source: 'Ấn Độ',
		costPrice: 0,
		expiryDate: -27080352000000,
		retailPrice: 100,
	},
	{
		brandName: 'AT ZinC',
		substance: 'kẽm gluconate 20mg/10ml',
		unit: 'Ống',
		group: 'Dinh Dưỡng',
		route: 'Uống',
		source: 'việt nam',
		costPrice: 0,
		expiryDate: -27080352000000,
		retailPrice: 10,
	},
]
