export * from './product/product.operation'

export * from './receipt/receipt-cancel.operation'
export * from './receipt/receipt-draft.operation'
export * from './receipt/receipt-pay-debt.operation'
export * from './receipt/receipt-prepayment.operation'
export * from './receipt/receipt-refund-prepayment.operation'
export * from './receipt/receipt-send-product-and-payment.operation'

export * from './statistic/statistic-receipt.operation'
export * from './statistic/statistic.operation'

export * from './ticket-base/ticket-pay-debt.operation'
export * from './ticket-base/ticket-payment-and-close.operation'
export * from './ticket-base/ticket-prepayment.operation'
export * from './ticket-base/ticket-refund-money.operation'
export * from './ticket-base/ticket-send-product.operation'
export * from './ticket-base/ticket-statistic.operation'

export * from './ticket-clinic/ticket-clinic-reopen.operation'
export * from './ticket-clinic/ticket-clinic-return-product.operation'
export * from './ticket-clinic/ticket-clinic-update-items-money.operation'
export * from './ticket-clinic/ticket-clinic-update-ticket-laboratory-list.operation'
export * from './ticket-clinic/ticket-clinic-update-ticket-procedure-list.operation'
export * from './ticket-clinic/ticket-clinic-update-ticket-product-list.operation'
export * from './ticket-clinic/ticket-clinic-update-ticket-radiology-list.operation'

export * from './ticket-order/ticket-order-cancel.operation'
export * from './ticket-order/ticket-order-debt-success-update.operation'
export * from './ticket-order/ticket-order-draft-approved.operation'
export * from './ticket-order/ticket-order-draft.operation'
export * from './ticket-order/ticket-order-return.operation'
