import { Expose } from 'class-transformer'
import { Column, Entity, Index } from 'typeorm'
import { BaseEntity } from '../common/base.entity'

export enum OrganizationSettingType {
	SYSTEM_SETTING = 'SYSTEM_SETTING',

	PRODUCT_GROUP = 'PRODUCT_GROUP',
	PRODUCT_UNIT = 'PRODUCT_UNIT',
	PRODUCT_ROUTE = 'PRODUCT_ROUTE',
	PRODUCT_HINT_USAGE = 'PRODUCT_HINT_USAGE',

	PROCEDURE_GROUP = 'PROCEDURE_GROUP',

	INVOICE_SURCHARGE_DETAIL = 'INVOICE_SURCHARGE_DETAIL',
	INVOICE_EXPENSES_DETAIL = 'INVOICE_EXPENSES_DETAIL',

	SCREEN_PRODUCT_LIST = 'SCREEN_PRODUCT_LIST',
	SCREEN_PRODUCT_DETAIL = 'SCREEN_PRODUCT_DETAIL',
	SCREEN_PRODUCT_UPSERT = 'SCREEN_PRODUCT_UPSERT',

	SCREEN_RECEIPT_LIST = 'SCREEN_RECEIPT_LIST',
	SCREEN_RECEIPT_DETAIL = 'SCREEN_RECEIPT_DETAIL',
	SCREEN_RECEIPT_UPSERT = 'SCREEN_RECEIPT_UPSERT',

	SCREEN_INVOICE_LIST = 'SCREEN_INVOICE_LIST',
	SCREEN_INVOICE_DETAIL = 'SCREEN_INVOICE_DETAIL',
	SCREEN_INVOICE_PREVIEW = 'SCREEN_INVOICE_PREVIEW',
	SCREEN_INVOICE_UPSERT = 'SCREEN_INVOICE_UPSERT',

	SCREEN_CUSTOMER_LIST = 'SCREEN_CUSTOMER_LIST',
	SCREEN_CUSTOMER_DETAIL = 'SCREEN_CUSTOMER_DETAIL',
	SCREEN_CUSTOMER_UPSERT = 'SCREEN_CUSTOMER_UPSERT',

	SCREEN_DISTRIBUTOR_LIST = 'SCREEN_DISTRIBUTOR_LIST',
	SCREEN_DISTRIBUTOR_DETAIL = 'SCREEN_DISTRIBUTOR_DETAIL',
	SCREEN_DISTRIBUTOR_UPSERT = 'SCREEN_DISTRIBUTOR_UPSERT',

	SCREEN_PROCEDURE_LIST = 'SCREEN_PROCEDURE_LIST',
	SCREEN_PROCEDURE_DETAIL = 'SCREEN_PROCEDURE_DETAIL',
	SCREEN_PROCEDURE_UPSERT = 'SCREEN_PROCEDURE_UPSERT',
}

@Entity('organization_setting')
@Index('IDX_ORG_SETTING_TYPE', ['oid', 'type'], { unique: true })
export default class OrganizationSetting extends BaseEntity {
	@Column({ name: 'type', type: 'varchar' })
	@Expose({ name: 'type' })
	type: OrganizationSettingType

	@Column({ name: 'data', type: 'text' })
	@Expose({ name: 'data' })
	data: string                              // Dạng JSON
}
