export * from './ticket-add-ticket-radiology-list.body'
export * from './ticket-change-radiology.params'
export * from './ticket-clinic-update-priority-ticket-radiology.body'
export * from './ticket-radiology-cancel-result.request'
export * from './ticket-radiology-update-result.request'
export * from './ticket-update-ticket-radiology.body'
