export * from './ticket-add-ticket-radiology-list.body'
export * from './ticket-cancel-result-ticket-radiology.request'
export * from './ticket-change-radiology.params'
export * from './ticket-update-priority-ticket-radiology.body'
export * from './ticket-update-request-ticket-radiology.body'
export * from './ticket-update-result-ticket-radiology.request'
