import { Injectable } from '@nestjs/common'
import Permission, { PermissionId } from '../../../../_libs/database/entities/permission.entity'
import { OrganizationRepository } from '../../../../_libs/database/repository/organization/organization.repository'
import { PermissionRepository } from '../../../../_libs/database/repository/permission/permission.repository'
import { PermissionGetManyQuery } from './request'

@Injectable()
export class ApiPermissionService {
  constructor(
    private readonly permissionRepository: PermissionRepository,
    private readonly organizationRepository: OrganizationRepository
  ) {}

  async getMany(query: PermissionGetManyQuery) {
    const { limit, filter, sort } = query

    // const organization = await this.organizationRepository.findOneById(oid)
    // const permissionIds: number[] = JSON.parse(organization.permissionIds)
    const data = await this.permissionRepository.findMany({
      condition: {
        // id: { IN: permissionIds },
        level: filter?.level,
      },
      limit,
      sort,
    })
    return { data }
  }

  async initData() {
    const permissionOrganization: Permission[] = [
      {
        id: PermissionId.ORGANIZATION,
        level: 1,
        code: PermissionId[PermissionId.ORGANIZATION],
        isActive: 1,
        pathId: `${PermissionId.ORGANIZATION}`,
        name: 'Quản lý cơ sở (Admin)',
        parentId: 0,
        rootId: PermissionId.ORGANIZATION,
      },
      {
        id: PermissionId.ORGANIZATION_UPDATE_INFO,
        level: 2,
        code: PermissionId[PermissionId.ORGANIZATION_UPDATE_INFO],
        isActive: 1,
        pathId: `${PermissionId.ORGANIZATION}.${PermissionId.ORGANIZATION_UPDATE_INFO}`,
        name: 'Sửa thông tin cơ sở',
        parentId: PermissionId.ORGANIZATION,
        rootId: PermissionId.ORGANIZATION,
      },
      {
        id: PermissionId.ORGANIZATION_SETTING_SCREEN,
        level: 2,
        code: PermissionId[PermissionId.ORGANIZATION_SETTING_SCREEN],
        isActive: 1,
        pathId: `${PermissionId.ORGANIZATION}.${PermissionId.ORGANIZATION_SETTING_SCREEN}`,
        name: 'Cài đặt màn hình',
        parentId: PermissionId.ORGANIZATION,
        rootId: PermissionId.ORGANIZATION,
      },
    ]
    const permissionRole: Permission[] = [
      {
        id: PermissionId.ROLE,
        level: 1,
        code: PermissionId[PermissionId.ROLE],
        isActive: 1,
        pathId: `${PermissionId.ROLE}`,
        name: 'Quản lý vai trò',
        parentId: 0,
        rootId: PermissionId.ROLE,
      },
      {
        id: PermissionId.ROLE_READ,
        level: 2,
        code: PermissionId[PermissionId.ROLE_READ],
        isActive: 1,
        pathId: `${PermissionId.ROLE}.${PermissionId.ROLE_READ}`,
        name: 'Xem vai trò',
        parentId: PermissionId.ROLE,
        rootId: PermissionId.ROLE,
      },
      {
        id: PermissionId.ROLE_CREATE,
        level: 2,
        code: PermissionId[PermissionId.ROLE_CREATE],
        isActive: 1,
        pathId: `${PermissionId.ROLE}.${PermissionId.ROLE_CREATE}`,
        name: 'Thêm vai trò',
        parentId: PermissionId.ROLE,
        rootId: PermissionId.ROLE,
      },
      {
        id: PermissionId.ROLE_UPDATE,
        level: 2,
        code: PermissionId[PermissionId.ROLE_UPDATE],
        isActive: 1,
        pathId: `${PermissionId.ROLE}.${PermissionId.ROLE_UPDATE}`,
        name: 'Sửa vai trò',
        parentId: PermissionId.ROLE,
        rootId: PermissionId.ROLE,
      },
      {
        id: PermissionId.ROLE_DELETE,
        level: 2,
        code: PermissionId[PermissionId.ROLE_DELETE],
        isActive: 1,
        pathId: `${PermissionId.ROLE}.${PermissionId.ROLE_DELETE}`,
        name: 'Xóa vai trò',
        parentId: PermissionId.ROLE,
        rootId: PermissionId.ROLE,
      },
    ]
    const permissionUser: Permission[] = [
      {
        id: PermissionId.USER,
        level: 1,
        code: PermissionId[PermissionId.USER],
        isActive: 1,
        pathId: `${PermissionId.USER}`,
        name: 'Quản lý nhân viên',
        parentId: 0,
        rootId: PermissionId.USER,
      },
      {
        id: PermissionId.USER_READ,
        level: 2,
        code: PermissionId[PermissionId.USER_READ],
        isActive: 1,
        pathId: `${PermissionId.USER}.${PermissionId.USER_READ}`,
        name: 'Xem nhân viên',
        parentId: PermissionId.USER,
        rootId: PermissionId.USER,
      },
      {
        id: PermissionId.USER_CREATE,
        level: 2,
        code: PermissionId[PermissionId.USER_CREATE],
        isActive: 1,
        pathId: `${PermissionId.USER}.${PermissionId.USER_CREATE}`,
        name: 'Thêm nhân viên',
        parentId: PermissionId.USER,
        rootId: PermissionId.USER,
      },
      {
        id: PermissionId.USER_UPDATE,
        level: 2,
        code: PermissionId[PermissionId.USER_UPDATE],
        isActive: 1,
        pathId: `${PermissionId.USER}.${PermissionId.USER_UPDATE}`,
        name: 'Sửa nhân viên',
        parentId: PermissionId.USER,
        rootId: PermissionId.USER,
      },
      {
        id: PermissionId.USER_DELETE,
        level: 2,
        code: PermissionId[PermissionId.USER_DELETE],
        isActive: 1,
        pathId: `${PermissionId.USER}.${PermissionId.USER_DELETE}`,
        name: 'Xóa nhân viên',
        parentId: PermissionId.USER,
        rootId: PermissionId.USER,
      },
      {
        id: PermissionId.USER_DEVICE_LOGOUT,
        level: 2,
        code: PermissionId[PermissionId.USER_DEVICE_LOGOUT],
        isActive: 1,
        pathId: `${PermissionId.USER}.${PermissionId.USER_DEVICE_LOGOUT}`,
        name: 'Đăng xuất thiết bị',
        parentId: PermissionId.USER,
        rootId: PermissionId.USER,
      },
    ]
    const permissionProduct: Permission[] = [
      {
        id: PermissionId.PRODUCT,
        level: 1,
        code: PermissionId[PermissionId.PRODUCT],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}`,
        name: 'Quản lý sản phẩm',
        parentId: 0,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.PRODUCT_READ,
        level: 2,
        code: PermissionId[PermissionId.PRODUCT_READ],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.PRODUCT_READ}`,
        name: 'Xem sản phẩm',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.PRODUCT_CREATE,
        level: 2,
        code: PermissionId[PermissionId.PRODUCT_CREATE],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.PRODUCT_CREATE}`,
        name: 'Thêm sản phẩm',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.PRODUCT_UPDATE,
        level: 2,
        code: PermissionId[PermissionId.PRODUCT_UPDATE],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.PRODUCT_UPDATE}`,
        name: 'Sửa sản phẩm',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.PRODUCT_DELETE,
        level: 2,
        code: PermissionId[PermissionId.PRODUCT_DELETE],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.PRODUCT_DELETE}`,
        name: 'Xóa sản phẩm',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.BATCH_READ,
        level: 2,
        code: PermissionId[PermissionId.BATCH_READ],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.BATCH_READ}`,
        name: 'Xem lô hàng',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.BATCH_CREATE,
        level: 2,
        code: PermissionId[PermissionId.BATCH_CREATE],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.BATCH_CREATE}`,
        name: 'Thêm lô hàng',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.BATCH_UPDATE,
        level: 2,
        code: PermissionId[PermissionId.BATCH_UPDATE],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.BATCH_UPDATE}`,
        name: 'Sửa lô hàng',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.BATCH_DELETE,
        level: 2,
        code: PermissionId[PermissionId.BATCH_DELETE],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.BATCH_DELETE}`,
        name: 'Xóa lô hàng',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.READ_COST_PRICE,
        level: 2,
        code: PermissionId[PermissionId.READ_COST_PRICE],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.READ_COST_PRICE}`,
        name: 'Xem giá nhập',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.READ_MOVEMENT,
        level: 2,
        code: PermissionId[PermissionId.READ_MOVEMENT],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.READ_MOVEMENT}`,
        name: 'Xem lịch sử nhập xuất',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
    ]
    const permissionDistributor: Permission[] = [
      {
        id: PermissionId.DISTRIBUTOR,
        level: 1,
        code: PermissionId[PermissionId.DISTRIBUTOR],
        isActive: 1,
        pathId: `${PermissionId.DISTRIBUTOR}`,
        name: 'Quản lý nhà cung cấp',
        parentId: 0,
        rootId: PermissionId.DISTRIBUTOR,
      },
      {
        id: PermissionId.DISTRIBUTOR_READ,
        level: 2,
        code: PermissionId[PermissionId.DISTRIBUTOR_READ],
        isActive: 1,
        pathId: `${PermissionId.DISTRIBUTOR}.${PermissionId.DISTRIBUTOR_READ}`,
        name: 'Xem nhà cung cấp',
        parentId: PermissionId.DISTRIBUTOR,
        rootId: PermissionId.DISTRIBUTOR,
      },
      {
        id: PermissionId.DISTRIBUTOR_CREATE,
        level: 2,
        code: PermissionId[PermissionId.DISTRIBUTOR_CREATE],
        isActive: 1,
        pathId: `${PermissionId.DISTRIBUTOR}.${PermissionId.DISTRIBUTOR_CREATE}`,
        name: 'Thêm nhà cung cấp',
        parentId: PermissionId.DISTRIBUTOR,
        rootId: PermissionId.DISTRIBUTOR,
      },
      {
        id: PermissionId.DISTRIBUTOR_UPDATE,
        level: 2,
        code: PermissionId[PermissionId.DISTRIBUTOR_UPDATE],
        isActive: 1,
        pathId: `${PermissionId.DISTRIBUTOR}.${PermissionId.DISTRIBUTOR_UPDATE}`,
        name: 'Sửa nhà cung cấp',
        parentId: PermissionId.DISTRIBUTOR,
        rootId: PermissionId.DISTRIBUTOR,
      },
      {
        id: PermissionId.DISTRIBUTOR_DELETE,
        level: 2,
        code: PermissionId[PermissionId.DISTRIBUTOR_DELETE],
        isActive: 1,
        pathId: `${PermissionId.DISTRIBUTOR}.${PermissionId.DISTRIBUTOR_DELETE}`,
        name: 'Xóa nhà cung cấp',
        parentId: PermissionId.DISTRIBUTOR,
        rootId: PermissionId.DISTRIBUTOR,
      },
      {
        id: PermissionId.DISTRIBUTOR_PAYMENT_READ,
        level: 2,
        code: PermissionId[PermissionId.DISTRIBUTOR_PAYMENT_READ],
        isActive: 1,
        pathId: `${PermissionId.DISTRIBUTOR}.${PermissionId.DISTRIBUTOR_PAYMENT_READ}`,
        name: 'Xem lịch sử thanh toán',
        parentId: PermissionId.DISTRIBUTOR,
        rootId: PermissionId.DISTRIBUTOR,
      },
      {
        id: PermissionId.DISTRIBUTOR_PAYMENT_PAY_DEBT,
        level: 2,
        code: PermissionId[PermissionId.DISTRIBUTOR_PAYMENT_PAY_DEBT],
        isActive: 1,
        pathId: `${PermissionId.DISTRIBUTOR}.${PermissionId.DISTRIBUTOR_PAYMENT_PAY_DEBT}`,
        name: 'Thực hiện trả nợ',
        parentId: PermissionId.DISTRIBUTOR,
        rootId: PermissionId.DISTRIBUTOR,
      },
    ]
    const permissionCustomer: Permission[] = [
      {
        id: PermissionId.CUSTOMER,
        level: 1,
        code: PermissionId[PermissionId.CUSTOMER],
        isActive: 1,
        pathId: `${PermissionId.CUSTOMER}`,
        name: 'Quản lý khách hàng',
        parentId: 0,
        rootId: PermissionId.CUSTOMER,
      },
      {
        id: PermissionId.CUSTOMER_READ,
        level: 2,
        code: PermissionId[PermissionId.CUSTOMER_READ],
        isActive: 1,
        pathId: `${PermissionId.CUSTOMER}.${PermissionId.CUSTOMER_READ}`,
        name: 'Xem khách hàng',
        parentId: PermissionId.CUSTOMER,
        rootId: PermissionId.CUSTOMER,
      },
      {
        id: PermissionId.CUSTOMER_CREATE,
        level: 2,
        code: PermissionId[PermissionId.CUSTOMER_CREATE],
        isActive: 1,
        pathId: `${PermissionId.CUSTOMER}.${PermissionId.CUSTOMER_CREATE}`,
        name: 'Thêm khách hàng',
        parentId: PermissionId.CUSTOMER,
        rootId: PermissionId.CUSTOMER,
      },
      {
        id: PermissionId.CUSTOMER_UPDATE,
        level: 2,
        code: PermissionId[PermissionId.CUSTOMER_UPDATE],
        isActive: 1,
        pathId: `${PermissionId.CUSTOMER}.${PermissionId.CUSTOMER_UPDATE}`,
        name: 'Sửa khách hàng',
        parentId: PermissionId.CUSTOMER,
        rootId: PermissionId.CUSTOMER,
      },
      {
        id: PermissionId.CUSTOMER_DELETE,
        level: 2,
        code: PermissionId[PermissionId.CUSTOMER_DELETE],
        isActive: 1,
        pathId: `${PermissionId.CUSTOMER}.${PermissionId.CUSTOMER_DELETE}`,
        name: 'Xóa khách hàng',
        parentId: PermissionId.CUSTOMER,
        rootId: PermissionId.CUSTOMER,
      },
      {
        id: PermissionId.CUSTOMER_PAYMENT_READ,
        level: 2,
        code: PermissionId[PermissionId.CUSTOMER_PAYMENT_READ],
        isActive: 1,
        pathId: `${PermissionId.CUSTOMER}.${PermissionId.CUSTOMER_PAYMENT_READ}`,
        name: 'Xem lịch sử thanh toán',
        parentId: PermissionId.CUSTOMER,
        rootId: PermissionId.CUSTOMER,
      },
      {
        id: PermissionId.CUSTOMER_PAYMENT_PAY_DEBT,
        level: 2,
        code: PermissionId[PermissionId.CUSTOMER_PAYMENT_PAY_DEBT],
        isActive: 1,
        pathId: `${PermissionId.CUSTOMER}.${PermissionId.CUSTOMER_PAYMENT_PAY_DEBT}`,
        name: 'Thực hiện trả nợ',
        parentId: PermissionId.CUSTOMER,
        rootId: PermissionId.CUSTOMER,
      },
    ]
    const permissionProcedure: Permission[] = [
      {
        id: PermissionId.PROCEDURE,
        level: 1,
        code: PermissionId[PermissionId.PROCEDURE],
        isActive: 1,
        pathId: `${PermissionId.PROCEDURE}`,
        name: 'Quản lý dịch vụ',
        parentId: 0,
        rootId: PermissionId.PROCEDURE,
      },
      {
        id: PermissionId.PROCEDURE_READ,
        level: 2,
        code: PermissionId[PermissionId.PROCEDURE_READ],
        isActive: 1,
        pathId: `${PermissionId.PROCEDURE}.${PermissionId.PROCEDURE_READ}`,
        name: 'Xem dịch vụ',
        parentId: PermissionId.PROCEDURE,
        rootId: PermissionId.PROCEDURE,
      },
      {
        id: PermissionId.PROCEDURE_CREATE,
        level: 2,
        code: PermissionId[PermissionId.PROCEDURE_CREATE],
        isActive: 1,
        pathId: `${PermissionId.PROCEDURE}.${PermissionId.PROCEDURE_CREATE}`,
        name: 'Thêm dịch vụ',
        parentId: PermissionId.PROCEDURE,
        rootId: PermissionId.PROCEDURE,
      },
      {
        id: PermissionId.PROCEDURE_UPDATE,
        level: 2,
        code: PermissionId[PermissionId.PROCEDURE_UPDATE],
        isActive: 1,
        pathId: `${PermissionId.PROCEDURE}.${PermissionId.PROCEDURE_UPDATE}`,
        name: 'Sửa dịch vụ',
        parentId: PermissionId.PROCEDURE,
        rootId: PermissionId.PROCEDURE,
      },
      {
        id: PermissionId.PROCEDURE_DELETE,
        level: 2,
        code: PermissionId[PermissionId.PROCEDURE_DELETE],
        isActive: 1,
        pathId: `${PermissionId.PROCEDURE}.${PermissionId.PROCEDURE_DELETE}`,
        name: 'Xóa dịch vụ',
        parentId: PermissionId.PROCEDURE,
        rootId: PermissionId.PROCEDURE,
      },
    ]
    const permissionReceipt: Permission[] = [
      {
        id: PermissionId.RECEIPT,
        level: 1,
        code: PermissionId[PermissionId.RECEIPT],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}`,
        name: 'Quản lý phiếu nhập',
        parentId: 0,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_READ,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_READ],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_READ}`,
        name: 'Xem phiếu nhập',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_CREATE_DRAFT,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_CREATE_DRAFT],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_CREATE_DRAFT}`,
        name: 'Tạo phiếu nhập nháp',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_UPDATE_DRAFT,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_UPDATE_DRAFT],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_UPDATE_DRAFT}`,
        name: 'Sửa phiếu nhập nháp',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_PREPAYMENT,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_PREPAYMENT],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_PREPAYMENT}`,
        name: 'Thanh toán trước',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_SHIP,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_SHIP],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_SHIP}`,
        name: 'Nhận hàng',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_PAY_DEBT,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_PAY_DEBT],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_PAY_DEBT}`,
        name: 'Trả nợ phiếu nhập',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_REFUND,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_REFUND],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_REFUND}`,
        name: 'Hoàn trả',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_DELETE,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_DELETE],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_DELETE}`,
        name: 'Xóa phiếu nhập',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
    ]
    const permissionInvoice: Permission[] = [
      {
        id: PermissionId.INVOICE,
        level: 1,
        code: PermissionId[PermissionId.INVOICE],
        isActive: 1,
        pathId: `${PermissionId.INVOICE}`,
        name: 'Quản lý hóa đơn',
        parentId: 0,
        rootId: PermissionId.INVOICE,
      },
      {
        id: PermissionId.INVOICE_READ,
        level: 2,
        code: PermissionId[PermissionId.INVOICE_READ],
        isActive: 1,
        pathId: `${PermissionId.INVOICE}.${PermissionId.INVOICE_READ}`,
        name: 'Xem hóa đơn',
        parentId: PermissionId.INVOICE,
        rootId: PermissionId.INVOICE,
      },
      {
        id: PermissionId.INVOICE_CREATE_DRAFT,
        level: 2,
        code: PermissionId[PermissionId.INVOICE_CREATE_DRAFT],
        isActive: 1,
        pathId: `${PermissionId.INVOICE}.${PermissionId.INVOICE_CREATE_DRAFT}`,
        name: 'Tạo hóa đơn nháp',
        parentId: PermissionId.INVOICE,
        rootId: PermissionId.INVOICE,
      },
      {
        id: PermissionId.INVOICE_UPDATE_DRAFT,
        level: 2,
        code: PermissionId[PermissionId.INVOICE_UPDATE_DRAFT],
        isActive: 1,
        pathId: `${PermissionId.INVOICE}.${PermissionId.INVOICE_UPDATE_DRAFT}`,
        name: 'Sửa hóa đơn nháp',
        parentId: PermissionId.INVOICE,
        rootId: PermissionId.INVOICE,
      },
      {
        id: PermissionId.INVOICE_PREPAYMENT,
        level: 2,
        code: PermissionId[PermissionId.INVOICE_PREPAYMENT],
        isActive: 1,
        pathId: `${PermissionId.INVOICE}.${PermissionId.INVOICE_PREPAYMENT}`,
        name: 'Thanh toán trước',
        parentId: PermissionId.INVOICE,
        rootId: PermissionId.INVOICE,
      },
      {
        id: PermissionId.INVOICE_SHIP,
        level: 2,
        code: PermissionId[PermissionId.INVOICE_SHIP],
        isActive: 1,
        pathId: `${PermissionId.INVOICE}.${PermissionId.INVOICE_SHIP}`,
        name: 'Gửi hàng',
        parentId: PermissionId.INVOICE,
        rootId: PermissionId.INVOICE,
      },
      {
        id: PermissionId.INVOICE_PAY_DEBT,
        level: 2,
        code: PermissionId[PermissionId.INVOICE_PAY_DEBT],
        isActive: 1,
        pathId: `${PermissionId.INVOICE}.${PermissionId.INVOICE_PAY_DEBT}`,
        name: 'Trả nợ hóa đơn',
        parentId: PermissionId.INVOICE,
        rootId: PermissionId.INVOICE,
      },
      {
        id: PermissionId.INVOICE_REFUND,
        level: 2,
        code: PermissionId[PermissionId.INVOICE_REFUND],
        isActive: 1,
        pathId: `${PermissionId.INVOICE}.${PermissionId.INVOICE_REFUND}`,
        name: 'Hoàn trả',
        parentId: PermissionId.INVOICE,
        rootId: PermissionId.INVOICE,
      },
      {
        id: PermissionId.INVOICE_DELETE,
        level: 2,
        code: PermissionId[PermissionId.INVOICE_DELETE],
        isActive: 1,
        pathId: `${PermissionId.INVOICE}.${PermissionId.INVOICE_DELETE}`,
        name: 'Xóa hóa đơn',
        parentId: PermissionId.INVOICE,
        rootId: PermissionId.INVOICE,
      },
    ]
    const permissionStatistic: Permission[] = [
      {
        id: PermissionId.STATISTIC,
        level: 1,
        code: PermissionId[PermissionId.STATISTIC],
        isActive: 1,
        pathId: `${PermissionId.STATISTIC}`,
        name: 'Quản lý thống kê',
        parentId: 0,
        rootId: PermissionId.STATISTIC,
      },
      {
        id: PermissionId.STATISTIC_PRODUCT,
        level: 2,
        code: PermissionId[PermissionId.STATISTIC_PRODUCT],
        isActive: 1,
        pathId: `${PermissionId.STATISTIC}.${PermissionId.STATISTIC_PRODUCT}`,
        name: 'Xem thống kê sản phẩm',
        parentId: PermissionId.STATISTIC,
        rootId: PermissionId.STATISTIC,
      },
      {
        id: PermissionId.STATISTIC_PROCEDURE,
        level: 2,
        code: PermissionId[PermissionId.STATISTIC_PROCEDURE],
        isActive: 1,
        pathId: `${PermissionId.STATISTIC}.${PermissionId.STATISTIC_PROCEDURE}`,
        name: 'Xem thống kê dịch vụ',
        parentId: PermissionId.STATISTIC,
        rootId: PermissionId.STATISTIC,
      },
      {
        id: PermissionId.STATISTIC_CUSTOMER,
        level: 2,
        code: PermissionId[PermissionId.STATISTIC_CUSTOMER],
        isActive: 1,
        pathId: `${PermissionId.STATISTIC}.${PermissionId.STATISTIC_CUSTOMER}`,
        name: 'Xem thống kê khách hàng',
        parentId: PermissionId.STATISTIC,
        rootId: PermissionId.STATISTIC,
      },
      {
        id: PermissionId.STATISTIC_RECEIPT,
        level: 2,
        code: PermissionId[PermissionId.STATISTIC_RECEIPT],
        isActive: 1,
        pathId: `${PermissionId.STATISTIC}.${PermissionId.STATISTIC_RECEIPT}`,
        name: 'Xem thống kê phiếu nhập',
        parentId: PermissionId.STATISTIC,
        rootId: PermissionId.STATISTIC,
      },
      {
        id: PermissionId.STATISTIC_INVOICE,
        level: 2,
        code: PermissionId[PermissionId.STATISTIC_INVOICE],
        isActive: 1,
        pathId: `${PermissionId.STATISTIC}.${PermissionId.STATISTIC_INVOICE}`,
        name: 'Xem thống kê hóa đơn',
        parentId: PermissionId.STATISTIC,
        rootId: PermissionId.STATISTIC,
      },
    ]
    const permissionArrival: Permission[] = [
      {
        id: PermissionId.ARRIVAL,
        level: 1,
        code: PermissionId[PermissionId.ARRIVAL],
        isActive: 1,
        pathId: `${PermissionId.ARRIVAL}`,
        name: 'Quản lý khám bệnh',
        parentId: 0,
        rootId: PermissionId.ARRIVAL,
      },
      {
        id: PermissionId.ARRIVAL_READ,
        level: 2,
        code: PermissionId[PermissionId.ARRIVAL_READ],
        isActive: 1,
        pathId: `${PermissionId.ARRIVAL}.${PermissionId.ARRIVAL_READ}`,
        name: 'Xem phiếu khám',
        parentId: PermissionId.ARRIVAL,
        rootId: PermissionId.ARRIVAL,
      },
      {
        id: PermissionId.ARRIVAL_CREATE,
        level: 2,
        code: PermissionId[PermissionId.ARRIVAL_CREATE],
        isActive: 1,
        pathId: `${PermissionId.ARRIVAL}.${PermissionId.ARRIVAL_CREATE}`,
        name: 'Tạo phiếu khám',
        parentId: PermissionId.ARRIVAL,
        rootId: PermissionId.ARRIVAL,
      },
      {
        id: PermissionId.ARRIVAL_UPDATE,
        level: 2,
        code: PermissionId[PermissionId.ARRIVAL_UPDATE],
        isActive: 1,
        pathId: `${PermissionId.ARRIVAL}.${PermissionId.ARRIVAL_UPDATE}`,
        name: 'Sửa phiếu khám',
        parentId: PermissionId.ARRIVAL,
        rootId: PermissionId.ARRIVAL,
      },
    ]
    const { idsEffect } = await this.permissionRepository.upsert([
      ...permissionOrganization,
      ...permissionRole,
      ...permissionUser,
      ...permissionProduct,
      ...permissionDistributor,
      ...permissionCustomer,
      ...permissionProcedure,
      ...permissionReceipt,
      ...permissionInvoice,
      ...permissionStatistic,
      ...permissionArrival,
    ])
    this.permissionRepository.setNewest(true)

    return { data: { idsEffect } }
  }
}
