/* eslint-disable max-len */
import { Injectable } from '@nestjs/common'
import Permission, { PermissionId } from '../../../../_libs/database/entities/permission.entity'
import { PermissionRepository } from '../../../../_libs/database/repository/permission/permission.repository'
import { CacheDataService } from '../../../../_libs/transporter/cache-manager/cache-data.service'
import { PermissionGetManyQuery } from './request'

@Injectable()
export class ApiPermissionService {
  constructor(
    private readonly permissionRepository: PermissionRepository,
    private readonly cacheDataService: CacheDataService
  ) { }

  async getMany(query: PermissionGetManyQuery) {
    const { limit, filter, sort } = query

    // const organization = await this.organizationRepository.findOneById(oid)
    // const permissionIds: number[] = JSON.parse(organization.permissionIds)
    const data = await this.permissionRepository.findMany({
      condition: {
        // id: { IN: permissionIds },
        level: filter?.level,
      },
      limit,
      sort,
    })
    return { data }
  }

  async initData() {
    const permissionOrganization: Permission[] = [
      {
        id: PermissionId.ORGANIZATION,
        level: 1,
        code: PermissionId[PermissionId.ORGANIZATION],
        isActive: 1,
        pathId: `${PermissionId.ORGANIZATION}`,
        name: 'Quản lý cơ sở (Admin)',
        parentId: 0,
        rootId: PermissionId.ORGANIZATION,
      },
      {
        id: PermissionId.ORGANIZATION_UPDATE_INFO,
        level: 2,
        code: PermissionId[PermissionId.ORGANIZATION_UPDATE_INFO],
        isActive: 1,
        pathId: `${PermissionId.ORGANIZATION}.${PermissionId.ORGANIZATION_UPDATE_INFO}`,
        name: 'Sửa thông tin cơ sở',
        parentId: PermissionId.ORGANIZATION,
        rootId: PermissionId.ORGANIZATION,
      },
      {
        id: PermissionId.SETTING_UPSERT,
        level: 2,
        code: PermissionId[PermissionId.SETTING_UPSERT],
        isActive: 1,
        pathId: `${PermissionId.ORGANIZATION}.${PermissionId.SETTING_UPSERT}`,
        name: 'Chỉnh sửa cài đặt',
        parentId: PermissionId.ORGANIZATION,
        rootId: PermissionId.ORGANIZATION,
      },
    ]
    const permissionRole: Permission[] = [
      {
        id: PermissionId.ROLE,
        level: 1,
        code: PermissionId[PermissionId.ROLE],
        isActive: 1,
        pathId: `${PermissionId.ROLE}`,
        name: 'Quản lý vai trò (Admin)',
        parentId: 0,
        rootId: PermissionId.ROLE,
      },
      {
        id: PermissionId.ROLE_READ,
        level: 2,
        code: PermissionId[PermissionId.ROLE_READ],
        isActive: 1,
        pathId: `${PermissionId.ROLE}.${PermissionId.ROLE_READ}`,
        name: 'Xem vai trò',
        parentId: PermissionId.ROLE,
        rootId: PermissionId.ROLE,
      },
      {
        id: PermissionId.ROLE_CREATE,
        level: 2,
        code: PermissionId[PermissionId.ROLE_CREATE],
        isActive: 1,
        pathId: `${PermissionId.ROLE}.${PermissionId.ROLE_CREATE}`,
        name: 'Thêm vai trò',
        parentId: PermissionId.ROLE,
        rootId: PermissionId.ROLE,
      },
      {
        id: PermissionId.ROLE_UPDATE,
        level: 2,
        code: PermissionId[PermissionId.ROLE_UPDATE],
        isActive: 1,
        pathId: `${PermissionId.ROLE}.${PermissionId.ROLE_UPDATE}`,
        name: 'Sửa vai trò',
        parentId: PermissionId.ROLE,
        rootId: PermissionId.ROLE,
      },
      {
        id: PermissionId.ROLE_DELETE,
        level: 2,
        code: PermissionId[PermissionId.ROLE_DELETE],
        isActive: 1,
        pathId: `${PermissionId.ROLE}.${PermissionId.ROLE_DELETE}`,
        name: 'Xóa vai trò',
        parentId: PermissionId.ROLE,
        rootId: PermissionId.ROLE,
      },
    ]
    const permissionUser: Permission[] = [
      {
        id: PermissionId.USER,
        level: 1,
        code: PermissionId[PermissionId.USER],
        isActive: 1,
        pathId: `${PermissionId.USER}`,
        name: 'Quản lý nhân viên (Admin)',
        parentId: 0,
        rootId: PermissionId.USER,
      },
      {
        id: PermissionId.USER_READ,
        level: 2,
        code: PermissionId[PermissionId.USER_READ],
        isActive: 1,
        pathId: `${PermissionId.USER}.${PermissionId.USER_READ}`,
        name: 'Xem nhân viên',
        parentId: PermissionId.USER,
        rootId: PermissionId.USER,
      },
      {
        id: PermissionId.USER_CREATE,
        level: 2,
        code: PermissionId[PermissionId.USER_CREATE],
        isActive: 1,
        pathId: `${PermissionId.USER}.${PermissionId.USER_CREATE}`,
        name: 'Thêm nhân viên',
        parentId: PermissionId.USER,
        rootId: PermissionId.USER,
      },
      {
        id: PermissionId.USER_UPDATE,
        level: 2,
        code: PermissionId[PermissionId.USER_UPDATE],
        isActive: 1,
        pathId: `${PermissionId.USER}.${PermissionId.USER_UPDATE}`,
        name: 'Sửa nhân viên',
        parentId: PermissionId.USER,
        rootId: PermissionId.USER,
      },
      {
        id: PermissionId.USER_DELETE,
        level: 2,
        code: PermissionId[PermissionId.USER_DELETE],
        isActive: 1,
        pathId: `${PermissionId.USER}.${PermissionId.USER_DELETE}`,
        name: 'Xóa nhân viên',
        parentId: PermissionId.USER,
        rootId: PermissionId.USER,
      },
      {
        id: PermissionId.USER_DEVICE_LOGOUT,
        level: 2,
        code: PermissionId[PermissionId.USER_DEVICE_LOGOUT],
        isActive: 1,
        pathId: `${PermissionId.USER}.${PermissionId.USER_DEVICE_LOGOUT}`,
        name: 'Đăng xuất thiết bị',
        parentId: PermissionId.USER,
        rootId: PermissionId.USER,
      },
    ]
    const permissionProduct: Permission[] = [
      {
        id: PermissionId.PRODUCT,
        level: 1,
        code: PermissionId[PermissionId.PRODUCT],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}`,
        name: 'Quản lý sản phẩm',
        parentId: 0,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.PRODUCT_READ,
        level: 2,
        code: PermissionId[PermissionId.PRODUCT_READ],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.PRODUCT_READ}`,
        name: 'Xem sản phẩm',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.PRODUCT_CREATE,
        level: 2,
        code: PermissionId[PermissionId.PRODUCT_CREATE],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.PRODUCT_CREATE}`,
        name: 'Thêm sản phẩm',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.PRODUCT_UPDATE,
        level: 2,
        code: PermissionId[PermissionId.PRODUCT_UPDATE],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.PRODUCT_UPDATE}`,
        name: 'Sửa sản phẩm',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.PRODUCT_DELETE,
        level: 2,
        code: PermissionId[PermissionId.PRODUCT_DELETE],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.PRODUCT_DELETE}`,
        name: 'Xóa sản phẩm',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.BATCH_READ,
        level: 2,
        code: PermissionId[PermissionId.BATCH_READ],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.BATCH_READ}`,
        name: 'Xem lô hàng',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.BATCH_CREATE,
        level: 2,
        code: PermissionId[PermissionId.BATCH_CREATE],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.BATCH_CREATE}`,
        name: 'Thêm lô hàng',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.BATCH_UPDATE,
        level: 2,
        code: PermissionId[PermissionId.BATCH_UPDATE],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.BATCH_UPDATE}`,
        name: 'Sửa lô hàng',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.BATCH_DELETE,
        level: 2,
        code: PermissionId[PermissionId.BATCH_DELETE],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.BATCH_DELETE}`,
        name: 'Xóa lô hàng',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.READ_COST_PRICE,
        level: 2,
        code: PermissionId[PermissionId.READ_COST_PRICE],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.READ_COST_PRICE}`,
        name: 'Xem giá nhập',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.READ_MOVEMENT,
        level: 2,
        code: PermissionId[PermissionId.READ_MOVEMENT],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.READ_MOVEMENT}`,
        name: 'Xem lịch sử nhập xuất',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
    ]
    const permissionDistributor: Permission[] = [
      {
        id: PermissionId.DISTRIBUTOR,
        level: 1,
        code: PermissionId[PermissionId.DISTRIBUTOR],
        isActive: 1,
        pathId: `${PermissionId.DISTRIBUTOR}`,
        name: 'Quản lý nhà cung cấp',
        parentId: 0,
        rootId: PermissionId.DISTRIBUTOR,
      },
      {
        id: PermissionId.DISTRIBUTOR_READ,
        level: 2,
        code: PermissionId[PermissionId.DISTRIBUTOR_READ],
        isActive: 1,
        pathId: `${PermissionId.DISTRIBUTOR}.${PermissionId.DISTRIBUTOR_READ}`,
        name: 'Xem nhà cung cấp',
        parentId: PermissionId.DISTRIBUTOR,
        rootId: PermissionId.DISTRIBUTOR,
      },
      {
        id: PermissionId.DISTRIBUTOR_CREATE,
        level: 2,
        code: PermissionId[PermissionId.DISTRIBUTOR_CREATE],
        isActive: 1,
        pathId: `${PermissionId.DISTRIBUTOR}.${PermissionId.DISTRIBUTOR_CREATE}`,
        name: 'Thêm nhà cung cấp',
        parentId: PermissionId.DISTRIBUTOR,
        rootId: PermissionId.DISTRIBUTOR,
      },
      {
        id: PermissionId.DISTRIBUTOR_UPDATE,
        level: 2,
        code: PermissionId[PermissionId.DISTRIBUTOR_UPDATE],
        isActive: 1,
        pathId: `${PermissionId.DISTRIBUTOR}.${PermissionId.DISTRIBUTOR_UPDATE}`,
        name: 'Sửa nhà cung cấp',
        parentId: PermissionId.DISTRIBUTOR,
        rootId: PermissionId.DISTRIBUTOR,
      },
      {
        id: PermissionId.DISTRIBUTOR_DELETE,
        level: 2,
        code: PermissionId[PermissionId.DISTRIBUTOR_DELETE],
        isActive: 1,
        pathId: `${PermissionId.DISTRIBUTOR}.${PermissionId.DISTRIBUTOR_DELETE}`,
        name: 'Xóa nhà cung cấp',
        parentId: PermissionId.DISTRIBUTOR,
        rootId: PermissionId.DISTRIBUTOR,
      },
      {
        id: PermissionId.DISTRIBUTOR_PAYMENT_READ,
        level: 2,
        code: PermissionId[PermissionId.DISTRIBUTOR_PAYMENT_READ],
        isActive: 1,
        pathId: `${PermissionId.DISTRIBUTOR}.${PermissionId.DISTRIBUTOR_PAYMENT_READ}`,
        name: 'Xem lịch sử thanh toán',
        parentId: PermissionId.DISTRIBUTOR,
        rootId: PermissionId.DISTRIBUTOR,
      },
      {
        id: PermissionId.DISTRIBUTOR_PAYMENT_PAY_DEBT,
        level: 2,
        code: PermissionId[PermissionId.DISTRIBUTOR_PAYMENT_PAY_DEBT],
        isActive: 1,
        pathId: `${PermissionId.DISTRIBUTOR}.${PermissionId.DISTRIBUTOR_PAYMENT_PAY_DEBT}`,
        name: 'Thực hiện trả nợ',
        parentId: PermissionId.DISTRIBUTOR,
        rootId: PermissionId.DISTRIBUTOR,
      },
    ]
    const permissionCustomer: Permission[] = [
      {
        id: PermissionId.CUSTOMER,
        level: 1,
        code: PermissionId[PermissionId.CUSTOMER],
        isActive: 1,
        pathId: `${PermissionId.CUSTOMER}`,
        name: 'Quản lý khách hàng',
        parentId: 0,
        rootId: PermissionId.CUSTOMER,
      },
      {
        id: PermissionId.CUSTOMER_READ,
        level: 2,
        code: PermissionId[PermissionId.CUSTOMER_READ],
        isActive: 1,
        pathId: `${PermissionId.CUSTOMER}.${PermissionId.CUSTOMER_READ}`,
        name: 'Xem khách hàng',
        parentId: PermissionId.CUSTOMER,
        rootId: PermissionId.CUSTOMER,
      },
      {
        id: PermissionId.CUSTOMER_CREATE,
        level: 2,
        code: PermissionId[PermissionId.CUSTOMER_CREATE],
        isActive: 1,
        pathId: `${PermissionId.CUSTOMER}.${PermissionId.CUSTOMER_CREATE}`,
        name: 'Thêm khách hàng',
        parentId: PermissionId.CUSTOMER,
        rootId: PermissionId.CUSTOMER,
      },
      {
        id: PermissionId.CUSTOMER_UPDATE,
        level: 2,
        code: PermissionId[PermissionId.CUSTOMER_UPDATE],
        isActive: 1,
        pathId: `${PermissionId.CUSTOMER}.${PermissionId.CUSTOMER_UPDATE}`,
        name: 'Sửa khách hàng',
        parentId: PermissionId.CUSTOMER,
        rootId: PermissionId.CUSTOMER,
      },
      {
        id: PermissionId.CUSTOMER_DELETE,
        level: 2,
        code: PermissionId[PermissionId.CUSTOMER_DELETE],
        isActive: 1,
        pathId: `${PermissionId.CUSTOMER}.${PermissionId.CUSTOMER_DELETE}`,
        name: 'Xóa khách hàng',
        parentId: PermissionId.CUSTOMER,
        rootId: PermissionId.CUSTOMER,
      },
      {
        id: PermissionId.CUSTOMER_PAYMENT_READ,
        level: 2,
        code: PermissionId[PermissionId.CUSTOMER_PAYMENT_READ],
        isActive: 1,
        pathId: `${PermissionId.CUSTOMER}.${PermissionId.CUSTOMER_PAYMENT_READ}`,
        name: 'Xem lịch sử thanh toán',
        parentId: PermissionId.CUSTOMER,
        rootId: PermissionId.CUSTOMER,
      },
      {
        id: PermissionId.CUSTOMER_PAY_DEBT,
        level: 2,
        code: PermissionId[PermissionId.CUSTOMER_PAY_DEBT],
        isActive: 1,
        pathId: `${PermissionId.CUSTOMER}.${PermissionId.CUSTOMER_PAY_DEBT}`,
        name: 'Thực hiện trả nợ',
        parentId: PermissionId.CUSTOMER,
        rootId: PermissionId.CUSTOMER,
      },
    ]
    const permissionProcedure: Permission[] = [
      {
        id: PermissionId.PROCEDURE,
        level: 1,
        code: PermissionId[PermissionId.PROCEDURE],
        isActive: 1,
        pathId: `${PermissionId.PROCEDURE}`,
        name: 'Quản lý dịch vụ',
        parentId: 0,
        rootId: PermissionId.PROCEDURE,
      },
      {
        id: PermissionId.PROCEDURE_READ,
        level: 2,
        code: PermissionId[PermissionId.PROCEDURE_READ],
        isActive: 1,
        pathId: `${PermissionId.PROCEDURE}.${PermissionId.PROCEDURE_READ}`,
        name: 'Xem dịch vụ',
        parentId: PermissionId.PROCEDURE,
        rootId: PermissionId.PROCEDURE,
      },
      {
        id: PermissionId.PROCEDURE_CREATE,
        level: 2,
        code: PermissionId[PermissionId.PROCEDURE_CREATE],
        isActive: 1,
        pathId: `${PermissionId.PROCEDURE}.${PermissionId.PROCEDURE_CREATE}`,
        name: 'Thêm dịch vụ',
        parentId: PermissionId.PROCEDURE,
        rootId: PermissionId.PROCEDURE,
      },
      {
        id: PermissionId.PROCEDURE_UPDATE,
        level: 2,
        code: PermissionId[PermissionId.PROCEDURE_UPDATE],
        isActive: 1,
        pathId: `${PermissionId.PROCEDURE}.${PermissionId.PROCEDURE_UPDATE}`,
        name: 'Sửa dịch vụ',
        parentId: PermissionId.PROCEDURE,
        rootId: PermissionId.PROCEDURE,
      },
      {
        id: PermissionId.PROCEDURE_DELETE,
        level: 2,
        code: PermissionId[PermissionId.PROCEDURE_DELETE],
        isActive: 1,
        pathId: `${PermissionId.PROCEDURE}.${PermissionId.PROCEDURE_DELETE}`,
        name: 'Xóa dịch vụ',
        parentId: PermissionId.PROCEDURE,
        rootId: PermissionId.PROCEDURE,
      },
    ]
    const permissionRadiology: Permission[] = [
      {
        id: PermissionId.RADIOLOGY,
        level: 1,
        code: PermissionId[PermissionId.RADIOLOGY],
        isActive: 1,
        pathId: `${PermissionId.RADIOLOGY}`,
        name: 'Quản lý chẩn đoán hình ảnh',
        parentId: 0,
        rootId: PermissionId.RADIOLOGY,
      },
      {
        id: PermissionId.RADIOLOGY_READ,
        level: 2,
        code: PermissionId[PermissionId.RADIOLOGY_READ],
        isActive: 1,
        pathId: `${PermissionId.RADIOLOGY}.${PermissionId.RADIOLOGY_READ}`,
        name: 'Xem chẩn đoán hình ảnh',
        parentId: PermissionId.RADIOLOGY,
        rootId: PermissionId.RADIOLOGY,
      },
      {
        id: PermissionId.RADIOLOGY_CREATE,
        level: 2,
        code: PermissionId[PermissionId.RADIOLOGY_CREATE],
        isActive: 1,
        pathId: `${PermissionId.RADIOLOGY}.${PermissionId.RADIOLOGY_CREATE}`,
        name: 'Thêm chẩn đoán hình ảnh',
        parentId: PermissionId.RADIOLOGY,
        rootId: PermissionId.RADIOLOGY,
      },
      {
        id: PermissionId.RADIOLOGY_UPDATE,
        level: 2,
        code: PermissionId[PermissionId.RADIOLOGY_UPDATE],
        isActive: 1,
        pathId: `${PermissionId.RADIOLOGY}.${PermissionId.RADIOLOGY_UPDATE}`,
        name: 'Sửa chẩn đoán hình ảnh',
        parentId: PermissionId.RADIOLOGY,
        rootId: PermissionId.RADIOLOGY,
      },
      {
        id: PermissionId.RADIOLOGY_DELETE,
        level: 2,
        code: PermissionId[PermissionId.RADIOLOGY_DELETE],
        isActive: 1,
        pathId: `${PermissionId.RADIOLOGY}.${PermissionId.RADIOLOGY_DELETE}`,
        name: 'Xóa chẩn đoán hình ảnh',
        parentId: PermissionId.RADIOLOGY,
        rootId: PermissionId.RADIOLOGY,
      },
    ]
    const permissionReceipt: Permission[] = [
      {
        id: PermissionId.RECEIPT,
        level: 1,
        code: PermissionId[PermissionId.RECEIPT],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}`,
        name: 'Quản lý phiếu nhập hàng',
        parentId: 0,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_READ,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_READ],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_READ}`,
        name: 'Xem phiếu nhập hàng',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_CREATE_DRAFT,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_CREATE_DRAFT],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_CREATE_DRAFT}`,
        name: 'Tạo phiếu nhập hàng nháp',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_PREPAYMENT,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_PREPAYMENT],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_PREPAYMENT}`,
        name: 'Tạm ứng',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_REFUND_PREPAYMENT,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_REFUND_PREPAYMENT],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_REFUND_PREPAYMENT}`,
        name: 'Hoàn trả tiền tạm ứng',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_SEND_PRODUCT,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_SEND_PRODUCT],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_SEND_PRODUCT}`,
        name: 'Nhập hàng',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_PAY_DEBT,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_PAY_DEBT],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_PAY_DEBT}`,
        name: 'Trả nợ phiếu nhập hàng',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_UPDATE_RECEIPT_DRAFT_AND_RECEIPT_PREPAYMENT,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_UPDATE_RECEIPT_DRAFT_AND_RECEIPT_PREPAYMENT],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_UPDATE_RECEIPT_DRAFT_AND_RECEIPT_PREPAYMENT}`,
        name: 'Sửa phiếu nhập hàng nháp và phiếu nhập hàng tạm ứng',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_UPDATE_RECEIPT_DEBT_AND_RECEIPT_SUCCESS,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_UPDATE_RECEIPT_DEBT_AND_RECEIPT_SUCCESS],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_UPDATE_RECEIPT_DEBT_AND_RECEIPT_SUCCESS}`,
        name: 'Sửa phiếu nhập hàng nợ và phiếu nhập hàng đã hoàn thành',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_RETURN_PRODUCT,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_RETURN_PRODUCT],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_RETURN_PRODUCT}`,
        name: 'Trả hàng',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_DELETE,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_DELETE],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_DELETE}`,
        name: 'Xóa phiếu nhập hàng',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
    ]
    const permissionOrderTicket: Permission[] = [
      {
        id: PermissionId.TICKET_ORDER,
        level: 1,
        code: PermissionId[PermissionId.TICKET_ORDER],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}`,
        name: 'Quản lý bán hàng',
        parentId: 0,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_READ,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_READ],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_READ}`,
        name: 'Xem hóa đơn',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_CREATE_DRAFT,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_CREATE_DRAFT],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_CREATE_DRAFT}`,
        name: 'Tạo hóa đơn nháp',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_UPDATE_DRAFT_APPROVED,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_UPDATE_DRAFT_APPROVED],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_UPDATE_DRAFT_APPROVED}`,
        name: 'Sửa hóa đơn nháp, hóa đơn tạm ứng',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_DESTROY_DRAFT,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_DESTROY_DRAFT],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_DESTROY_DRAFT}`,
        name: 'Xóa hóa đơn nháp',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_CREATE_DEBT_SUCCESS,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_CREATE_DEBT_SUCCESS],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_CREATE_DEBT_SUCCESS}`,
        name: 'Tạo hóa đơn bán hàng nhanh',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_UPDATE_DEBT_SUCCESS,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_UPDATE_DEBT_SUCCESS],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_UPDATE_DEBT_SUCCESS}`,
        name: 'Sửa hóa đơn bán hàng nhanh',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_PREPAYMENT,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_PREPAYMENT],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_PREPAYMENT}`,
        name: 'Tạm ứng',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_REFUND_OVERPAID,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_REFUND_OVERPAID],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_REFUND_OVERPAID}`,
        name: 'Hoàn trả tiền thừa',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_SEND_PRODUCT,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_SEND_PRODUCT],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_SEND_PRODUCT}`,
        name: 'Gửi hàng',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_RETURN_PRODUCT,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_RETURN_PRODUCT],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_RETURN_PRODUCT}`,
        name: 'Hoàn trả hàng',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_PAYMENT_AND_CLOSE,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_PAYMENT_AND_CLOSE],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_PAYMENT_AND_CLOSE}`,
        name: 'Đóng phiếu',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_PAY_DEBT,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_PAY_DEBT],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_PAY_DEBT}`,
        name: 'Trả nợ',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_REOPEN,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_REOPEN],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_REOPEN}`,
        name: 'Mở lại phiếu',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_CANCEL,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_CANCEL],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_CANCEL}`,
        name: 'Hủy đơn',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
    ]

    const permissionClinicTicket: Permission[] = [
      {
        id: PermissionId.TICKET_CLINIC,
        level: 1,
        code: PermissionId[PermissionId.TICKET_CLINIC],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}`,
        name: 'Quản lý khám bệnh',
        parentId: 0,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_READ,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_READ],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_READ}`,
        name: 'Xem phiếu khám',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_REGISTER_NEW,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_REGISTER_NEW],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_REGISTER_NEW}`,
        name: 'Tạo phiếu khám mới',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_START_CHECKUP,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_START_CHECKUP],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_START_CHECKUP}`,
        name: 'Bắt đầu vào khám',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_UPDATE_DIAGNOSIS,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_UPDATE_DIAGNOSIS],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_UPDATE_DIAGNOSIS}`,
        name: 'Khám bệnh và chẩn đoán',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_CHANGE_TICKET_PROCEDURE_LIST,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_CHANGE_TICKET_PROCEDURE_LIST],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_CHANGE_TICKET_PROCEDURE_LIST}`,
        name: 'Chỉ định dịch vụ',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_READ_TICKET_RADIOLOGY,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_READ_TICKET_RADIOLOGY],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_READ_TICKET_RADIOLOGY}`,
        name: 'Xem kết quả CĐHA',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_CHANGE_TICKET_RADIOLOGY_LIST,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_CHANGE_TICKET_RADIOLOGY_LIST],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_CHANGE_TICKET_RADIOLOGY_LIST}`,
        name: 'Chỉ định CĐHA',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_UPSERT_TICKET_RADIOLOGY_RESULT,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_UPSERT_TICKET_RADIOLOGY_RESULT],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_UPSERT_TICKET_RADIOLOGY_RESULT}`,
        name: 'Thực hiện và kết luận phiếu CĐHA',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_CHANGE_PRESCRIPTION,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_CHANGE_PRESCRIPTION],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_CHANGE_PRESCRIPTION}`,
        name: 'Kê đơn thuốc',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },

      {
        id: PermissionId.TICKET_CLINIC_CHANGE_ITEMS_MONEY,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_CHANGE_ITEMS_MONEY],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_CHANGE_ITEMS_MONEY}`,
        name: 'Sửa số lượng và chiết khấu',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_PREPAYMENT,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_PREPAYMENT],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_PREPAYMENT}`,
        name: 'Tạm ứng',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_REFUND_OVERPAID,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_REFUND_OVERPAID],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_REFUND_OVERPAID}`,
        name: 'Hoàn trả tiền thừa',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_PAY_DEBT,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_PAY_DEBT],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_PAY_DEBT}`,
        name: 'Trả nợ',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_SEND_PRODUCT,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_SEND_PRODUCT],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_SEND_PRODUCT}`,
        name: 'Xuất thuốc',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_RETURN_PRODUCT,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_RETURN_PRODUCT],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_RETURN_PRODUCT}`,
        name: 'Hoàn trả thuốc',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_CLOSE,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_CLOSE],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_CLOSE}`,
        name: 'Đóng phiếu khám',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_REOPEN,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_REOPEN],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_REOPEN}`,
        name: 'Mở lại phiếu khám',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
    ]

    const permissionStatistic: Permission[] = [
      {
        id: PermissionId.STATISTIC,
        level: 1,
        code: PermissionId[PermissionId.STATISTIC],
        isActive: 1,
        pathId: `${PermissionId.STATISTIC}`,
        name: 'Quản lý thống kê',
        parentId: 0,
        rootId: PermissionId.STATISTIC,
      },
      {
        id: PermissionId.STATISTIC_PRODUCT,
        level: 2,
        code: PermissionId[PermissionId.STATISTIC_PRODUCT],
        isActive: 1,
        pathId: `${PermissionId.STATISTIC}.${PermissionId.STATISTIC_PRODUCT}`,
        name: 'Xem thống kê sản phẩm',
        parentId: PermissionId.STATISTIC,
        rootId: PermissionId.STATISTIC,
      },
      {
        id: PermissionId.STATISTIC_PROCEDURE,
        level: 2,
        code: PermissionId[PermissionId.STATISTIC_PROCEDURE],
        isActive: 1,
        pathId: `${PermissionId.STATISTIC}.${PermissionId.STATISTIC_PROCEDURE}`,
        name: 'Xem thống kê dịch vụ',
        parentId: PermissionId.STATISTIC,
        rootId: PermissionId.STATISTIC,
      },
      {
        id: PermissionId.STATISTIC_CUSTOMER,
        level: 2,
        code: PermissionId[PermissionId.STATISTIC_CUSTOMER],
        isActive: 1,
        pathId: `${PermissionId.STATISTIC}.${PermissionId.STATISTIC_CUSTOMER}`,
        name: 'Xem thống kê khách hàng',
        parentId: PermissionId.STATISTIC,
        rootId: PermissionId.STATISTIC,
      },
      {
        id: PermissionId.STATISTIC_RECEIPT,
        level: 2,
        code: PermissionId[PermissionId.STATISTIC_RECEIPT],
        isActive: 1,
        pathId: `${PermissionId.STATISTIC}.${PermissionId.STATISTIC_RECEIPT}`,
        name: 'Xem thống kê phiếu nhập',
        parentId: PermissionId.STATISTIC,
        rootId: PermissionId.STATISTIC,
      },
      {
        id: PermissionId.STATISTIC_TICKET,
        level: 2,
        code: PermissionId[PermissionId.STATISTIC_TICKET],
        isActive: 1,
        pathId: `${PermissionId.STATISTIC}.${PermissionId.STATISTIC_TICKET}`,
        name: 'Xem thống kê phiếu thu',
        parentId: PermissionId.STATISTIC,
        rootId: PermissionId.STATISTIC,
      },
    ]

    await this.permissionRepository.delete({})

    const { idsEffect } = await this.permissionRepository.upsert([
      ...permissionOrganization,
      ...permissionRole,
      ...permissionUser,
      ...permissionProduct,
      ...permissionDistributor,
      ...permissionCustomer,
      ...permissionProcedure,
      ...permissionRadiology,
      ...permissionReceipt,
      ...permissionOrderTicket,
      ...permissionClinicTicket,
      ...permissionStatistic,
    ])

    this.cacheDataService.reloadPermission()

    return { data: { idsEffect } }
  }
}
