/* eslint-disable max-len */
import { Injectable } from '@nestjs/common'
import { CacheDataService } from '../../../../_libs/common/cache-data/cache-data.service'
import Permission, { PermissionId } from '../../../../_libs/database/entities/permission.entity'
import { PermissionRepository } from '../../../../_libs/database/repository/permission/permission.repository'
import { PermissionGetManyQuery } from './request'

@Injectable()
export class ApiPermissionService {
  constructor(
    private readonly cacheDataService: CacheDataService,
    private readonly permissionRepository: PermissionRepository
  ) { }

  async getMany(query: PermissionGetManyQuery) {
    const { limit, filter, sort } = query

    // const organization = await this.organizationRepository.findOneById(oid)
    // const permissionIds: number[] = JSON.parse(organization.permissionIds)
    const data = await this.permissionRepository.findMany({
      condition: {
        // id: { IN: permissionIds },
        level: filter?.level,
        rootId: filter?.rootId,
      },
      limit,
      sort,
    })
    return { data }
  }

  async initData() {
    const permissionOrganization: Permission[] = [
      {
        id: PermissionId.ORGANIZATION,
        level: 1,
        code: PermissionId[PermissionId.ORGANIZATION],
        isActive: 1,
        pathId: `${PermissionId.ORGANIZATION}`,
        name: 'Quản lý cơ sở (Admin)',
        parentId: 0,
        rootId: PermissionId.ORGANIZATION,
      },
      {
        id: PermissionId.ORGANIZATION_UPDATE_INFO,
        level: 2,
        code: PermissionId[PermissionId.ORGANIZATION_UPDATE_INFO],
        isActive: 1,
        pathId: `${PermissionId.ORGANIZATION}.${PermissionId.ORGANIZATION_UPDATE_INFO}`,
        name: 'Sửa thông tin cơ sở',
        parentId: PermissionId.ORGANIZATION,
        rootId: PermissionId.ORGANIZATION,
      },
      {
        id: PermissionId.ORGANIZATION_SETTING_UPSERT,
        level: 2,
        code: PermissionId[PermissionId.ORGANIZATION_SETTING_UPSERT],
        isActive: 1,
        pathId: `${PermissionId.ORGANIZATION}.${PermissionId.ORGANIZATION_SETTING_UPSERT}`,
        name: 'Chỉnh sửa cài đặt',
        parentId: PermissionId.ORGANIZATION,
        rootId: PermissionId.ORGANIZATION,
      },
      {
        id: PermissionId.ORGANIZATION_VERIFY_EMAIL,
        level: 2,
        code: PermissionId[PermissionId.ORGANIZATION_VERIFY_EMAIL],
        isActive: 1,
        pathId: `${PermissionId.ORGANIZATION}.${PermissionId.ORGANIZATION_VERIFY_EMAIL}`,
        name: 'Sửa và kích hoạt email',
        parentId: PermissionId.ORGANIZATION,
        rootId: PermissionId.ORGANIZATION,
      },
    ]

    const permissionRole: Permission[] = [
      {
        id: PermissionId.ROLE,
        level: 1,
        code: PermissionId[PermissionId.ROLE],
        isActive: 1,
        pathId: `${PermissionId.ROLE}`,
        name: 'Quản lý vai trò (Admin)',
        parentId: 0,
        rootId: PermissionId.ROLE,
      },
      {
        id: PermissionId.ROLE_READ,
        level: 2,
        code: PermissionId[PermissionId.ROLE_READ],
        isActive: 1,
        pathId: `${PermissionId.ROLE}.${PermissionId.ROLE_READ}`,
        name: 'Xem vai trò',
        parentId: PermissionId.ROLE,
        rootId: PermissionId.ROLE,
      },
      {
        id: PermissionId.ROLE_CREATE,
        level: 2,
        code: PermissionId[PermissionId.ROLE_CREATE],
        isActive: 1,
        pathId: `${PermissionId.ROLE}.${PermissionId.ROLE_CREATE}`,
        name: 'Thêm vai trò',
        parentId: PermissionId.ROLE,
        rootId: PermissionId.ROLE,
      },
      {
        id: PermissionId.ROLE_UPDATE,
        level: 2,
        code: PermissionId[PermissionId.ROLE_UPDATE],
        isActive: 1,
        pathId: `${PermissionId.ROLE}.${PermissionId.ROLE_UPDATE}`,
        name: 'Sửa vai trò',
        parentId: PermissionId.ROLE,
        rootId: PermissionId.ROLE,
      },
      {
        id: PermissionId.ROLE_DELETE,
        level: 2,
        code: PermissionId[PermissionId.ROLE_DELETE],
        isActive: 1,
        pathId: `${PermissionId.ROLE}.${PermissionId.ROLE_DELETE}`,
        name: 'Xóa vai trò',
        parentId: PermissionId.ROLE,
        rootId: PermissionId.ROLE,
      },
    ]

    const permissionUser: Permission[] = [
      {
        id: PermissionId.USER,
        level: 1,
        code: PermissionId[PermissionId.USER],
        isActive: 1,
        pathId: `${PermissionId.USER}`,
        name: 'Quản lý nhân viên (Admin)',
        parentId: 0,
        rootId: PermissionId.USER,
      },
      {
        id: PermissionId.USER_READ,
        level: 2,
        code: PermissionId[PermissionId.USER_READ],
        isActive: 1,
        pathId: `${PermissionId.USER}.${PermissionId.USER_READ}`,
        name: 'Xem nhân viên',
        parentId: PermissionId.USER,
        rootId: PermissionId.USER,
      },
      {
        id: PermissionId.USER_CREATE,
        level: 2,
        code: PermissionId[PermissionId.USER_CREATE],
        isActive: 1,
        pathId: `${PermissionId.USER}.${PermissionId.USER_CREATE}`,
        name: 'Thêm nhân viên',
        parentId: PermissionId.USER,
        rootId: PermissionId.USER,
      },
      {
        id: PermissionId.USER_UPDATE,
        level: 2,
        code: PermissionId[PermissionId.USER_UPDATE],
        isActive: 1,
        pathId: `${PermissionId.USER}.${PermissionId.USER_UPDATE}`,
        name: 'Sửa nhân viên',
        parentId: PermissionId.USER,
        rootId: PermissionId.USER,
      },
      {
        id: PermissionId.USER_DELETE,
        level: 2,
        code: PermissionId[PermissionId.USER_DELETE],
        isActive: 1,
        pathId: `${PermissionId.USER}.${PermissionId.USER_DELETE}`,
        name: 'Xóa nhân viên',
        parentId: PermissionId.USER,
        rootId: PermissionId.USER,
      },
      {
        id: PermissionId.USER_DEVICE_LOGOUT,
        level: 2,
        code: PermissionId[PermissionId.USER_DEVICE_LOGOUT],
        isActive: 1,
        pathId: `${PermissionId.USER}.${PermissionId.USER_DEVICE_LOGOUT}`,
        name: 'Đăng xuất thiết bị',
        parentId: PermissionId.USER,
        rootId: PermissionId.USER,
      },
    ]

    const permissionStatistic: Permission[] = [
      {
        id: PermissionId.STATISTIC,
        level: 1,
        code: PermissionId[PermissionId.STATISTIC],
        isActive: 1,
        pathId: `${PermissionId.STATISTIC}`,
        name: 'Quản lý thống kê',
        parentId: 0,
        rootId: PermissionId.STATISTIC,
      },
      {
        id: PermissionId.STATISTIC_PRODUCT,
        level: 2,
        code: PermissionId[PermissionId.STATISTIC_PRODUCT],
        isActive: 1,
        pathId: `${PermissionId.STATISTIC}.${PermissionId.STATISTIC_PRODUCT}`,
        name: 'Xem thống kê sản phẩm',
        parentId: PermissionId.STATISTIC,
        rootId: PermissionId.STATISTIC,
      },
      {
        id: PermissionId.STATISTIC_PROCEDURE,
        level: 2,
        code: PermissionId[PermissionId.STATISTIC_PROCEDURE],
        isActive: 1,
        pathId: `${PermissionId.STATISTIC}.${PermissionId.STATISTIC_PROCEDURE}`,
        name: 'Xem thống kê dịch vụ',
        parentId: PermissionId.STATISTIC,
        rootId: PermissionId.STATISTIC,
      },
      {
        id: PermissionId.STATISTIC_CUSTOMER,
        level: 2,
        code: PermissionId[PermissionId.STATISTIC_CUSTOMER],
        isActive: 1,
        pathId: `${PermissionId.STATISTIC}.${PermissionId.STATISTIC_CUSTOMER}`,
        name: 'Xem thống kê khách hàng',
        parentId: PermissionId.STATISTIC,
        rootId: PermissionId.STATISTIC,
      },
      {
        id: PermissionId.STATISTIC_RECEIPT,
        level: 2,
        code: PermissionId[PermissionId.STATISTIC_RECEIPT],
        isActive: 1,
        pathId: `${PermissionId.STATISTIC}.${PermissionId.STATISTIC_RECEIPT}`,
        name: 'Xem thống kê phiếu nhập',
        parentId: PermissionId.STATISTIC,
        rootId: PermissionId.STATISTIC,
      },
      {
        id: PermissionId.STATISTIC_TICKET,
        level: 2,
        code: PermissionId[PermissionId.STATISTIC_TICKET],
        isActive: 1,
        pathId: `${PermissionId.STATISTIC}.${PermissionId.STATISTIC_TICKET}`,
        name: 'Xem thống kê lượt đón tiếp',
        parentId: PermissionId.STATISTIC,
        rootId: PermissionId.STATISTIC,
      },
    ]

    const permissionMasterData: Permission[] = [
      {
        id: PermissionId.MASTER_DATA,
        level: 1,
        code: PermissionId[PermissionId.MASTER_DATA],
        isActive: 1,
        pathId: `${PermissionId.MASTER_DATA}`,
        name: 'Quản lý danh mục',
        parentId: 0,
        rootId: PermissionId.MASTER_DATA,
      },
      {
        id: PermissionId.MASTER_DATA_WAREHOUSE,
        level: 2,
        code: PermissionId[PermissionId.MASTER_DATA_WAREHOUSE],
        isActive: 1,
        pathId: `${PermissionId.MASTER_DATA}.${PermissionId.MASTER_DATA_WAREHOUSE}`,
        name: 'Quản lý danh sách kho',
        parentId: PermissionId.MASTER_DATA,
        rootId: PermissionId.MASTER_DATA,
      },
      {
        id: PermissionId.MASTER_DATA_PROCEDURE,
        level: 2,
        code: PermissionId[PermissionId.MASTER_DATA_PROCEDURE],
        isActive: 1,
        pathId: `${PermissionId.MASTER_DATA}.${PermissionId.MASTER_DATA_PROCEDURE}`,
        name: 'Quản lý dịch vụ',
        parentId: PermissionId.MASTER_DATA,
        rootId: PermissionId.MASTER_DATA,
      },
      {
        id: PermissionId.MASTER_DATA_LABORATORY,
        level: 2,
        code: PermissionId[PermissionId.MASTER_DATA_LABORATORY],
        isActive: 1,
        pathId: `${PermissionId.MASTER_DATA}.${PermissionId.MASTER_DATA_LABORATORY}`,
        name: 'Quản lý phiếu xét nghiệm',
        parentId: PermissionId.MASTER_DATA,
        rootId: PermissionId.MASTER_DATA,
      },
      {
        id: PermissionId.MASTER_DATA_RADIOLOGY,
        level: 2,
        code: PermissionId[PermissionId.MASTER_DATA_RADIOLOGY],
        isActive: 1,
        pathId: `${PermissionId.MASTER_DATA}.${PermissionId.MASTER_DATA_RADIOLOGY}`,
        name: 'Quản lý phiếu CĐHA',
        parentId: PermissionId.MASTER_DATA,
        rootId: PermissionId.MASTER_DATA,
      },
      {
        id: PermissionId.MASTER_DATA_TICKET_SOURCE,
        level: 2,
        code: PermissionId[PermissionId.MASTER_DATA_TICKET_SOURCE],
        isActive: 1,
        pathId: `${PermissionId.MASTER_DATA}.${PermissionId.MASTER_DATA_TICKET_SOURCE}`,
        name: 'Quản lý nguồn khách hàng',
        parentId: PermissionId.MASTER_DATA,
        rootId: PermissionId.MASTER_DATA,
      },
      {
        id: PermissionId.MASTER_DATA_PRINT_HTML,
        level: 2,
        code: PermissionId[PermissionId.MASTER_DATA_PRINT_HTML],
        isActive: 1,
        pathId: `${PermissionId.MASTER_DATA}.${PermissionId.MASTER_DATA_PRINT_HTML}`,
        name: 'Quản lý danh sách mẫu in',
        parentId: PermissionId.MASTER_DATA,
        rootId: PermissionId.MASTER_DATA,
      },
      {
        id: PermissionId.MASTER_DATA_PRESCRIPTION_SAMPLE,
        level: 2,
        code: PermissionId[PermissionId.MASTER_DATA_PRESCRIPTION_SAMPLE],
        isActive: 1,
        pathId: `${PermissionId.MASTER_DATA}.${PermissionId.MASTER_DATA_PRESCRIPTION_SAMPLE}`,
        name: 'Quản lý đơn thuốc mẫu',
        parentId: PermissionId.MASTER_DATA,
        rootId: PermissionId.MASTER_DATA,
      },
    ]

    const permissionProduct: Permission[] = [
      {
        id: PermissionId.PRODUCT,
        level: 1,
        code: PermissionId[PermissionId.PRODUCT],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}`,
        name: 'Quản lý sản phẩm',
        parentId: 0,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.PRODUCT_READ,
        level: 2,
        code: PermissionId[PermissionId.PRODUCT_READ],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.PRODUCT_READ}`,
        name: 'Xem sản phẩm',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.PRODUCT_CREATE,
        level: 2,
        code: PermissionId[PermissionId.PRODUCT_CREATE],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.PRODUCT_CREATE}`,
        name: 'Thêm sản phẩm',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.PRODUCT_UPDATE,
        level: 2,
        code: PermissionId[PermissionId.PRODUCT_UPDATE],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.PRODUCT_UPDATE}`,
        name: 'Sửa sản phẩm',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.PRODUCT_DELETE,
        level: 2,
        code: PermissionId[PermissionId.PRODUCT_DELETE],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.PRODUCT_DELETE}`,
        name: 'Xóa sản phẩm',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.PRODUCT_DOWNLOAD_EXCEL,
        level: 2,
        code: PermissionId[PermissionId.PRODUCT_DOWNLOAD_EXCEL],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.PRODUCT_DOWNLOAD_EXCEL}`,
        name: 'Tải file Excel tất cả sản phẩm',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.BATCH_READ,
        level: 2,
        code: PermissionId[PermissionId.BATCH_READ],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.BATCH_READ}`,
        name: 'Xem lô hàng',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.BATCH_CREATE,
        level: 2,
        code: PermissionId[PermissionId.BATCH_CREATE],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.BATCH_CREATE}`,
        name: 'Thêm lô hàng',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.BATCH_UPDATE,
        level: 2,
        code: PermissionId[PermissionId.BATCH_UPDATE],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.BATCH_UPDATE}`,
        name: 'Sửa lô hàng',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.BATCH_DELETE,
        level: 2,
        code: PermissionId[PermissionId.BATCH_DELETE],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.BATCH_DELETE}`,
        name: 'Xóa lô hàng',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.READ_COST_PRICE,
        level: 2,
        code: PermissionId[PermissionId.READ_COST_PRICE],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.READ_COST_PRICE}`,
        name: 'Xem giá nhập',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
      {
        id: PermissionId.READ_MOVEMENT,
        level: 2,
        code: PermissionId[PermissionId.READ_MOVEMENT],
        isActive: 1,
        pathId: `${PermissionId.PRODUCT}.${PermissionId.READ_MOVEMENT}`,
        name: 'Xem lịch sử nhập xuất',
        parentId: PermissionId.PRODUCT,
        rootId: PermissionId.PRODUCT,
      },
    ]

    const permissionDistributor: Permission[] = [
      {
        id: PermissionId.DISTRIBUTOR,
        level: 1,
        code: PermissionId[PermissionId.DISTRIBUTOR],
        isActive: 1,
        pathId: `${PermissionId.DISTRIBUTOR}`,
        name: 'Quản lý nhà cung cấp',
        parentId: 0,
        rootId: PermissionId.DISTRIBUTOR,
      },
      {
        id: PermissionId.DISTRIBUTOR_READ,
        level: 2,
        code: PermissionId[PermissionId.DISTRIBUTOR_READ],
        isActive: 1,
        pathId: `${PermissionId.DISTRIBUTOR}.${PermissionId.DISTRIBUTOR_READ}`,
        name: 'Xem nhà cung cấp',
        parentId: PermissionId.DISTRIBUTOR,
        rootId: PermissionId.DISTRIBUTOR,
      },
      {
        id: PermissionId.DISTRIBUTOR_CREATE,
        level: 2,
        code: PermissionId[PermissionId.DISTRIBUTOR_CREATE],
        isActive: 1,
        pathId: `${PermissionId.DISTRIBUTOR}.${PermissionId.DISTRIBUTOR_CREATE}`,
        name: 'Thêm nhà cung cấp',
        parentId: PermissionId.DISTRIBUTOR,
        rootId: PermissionId.DISTRIBUTOR,
      },
      {
        id: PermissionId.DISTRIBUTOR_UPDATE,
        level: 2,
        code: PermissionId[PermissionId.DISTRIBUTOR_UPDATE],
        isActive: 1,
        pathId: `${PermissionId.DISTRIBUTOR}.${PermissionId.DISTRIBUTOR_UPDATE}`,
        name: 'Sửa nhà cung cấp',
        parentId: PermissionId.DISTRIBUTOR,
        rootId: PermissionId.DISTRIBUTOR,
      },
      {
        id: PermissionId.DISTRIBUTOR_DELETE,
        level: 2,
        code: PermissionId[PermissionId.DISTRIBUTOR_DELETE],
        isActive: 1,
        pathId: `${PermissionId.DISTRIBUTOR}.${PermissionId.DISTRIBUTOR_DELETE}`,
        name: 'Xóa nhà cung cấp',
        parentId: PermissionId.DISTRIBUTOR,
        rootId: PermissionId.DISTRIBUTOR,
      },
      {
        id: PermissionId.DISTRIBUTOR_PAYMENT_READ,
        level: 2,
        code: PermissionId[PermissionId.DISTRIBUTOR_PAYMENT_READ],
        isActive: 1,
        pathId: `${PermissionId.DISTRIBUTOR}.${PermissionId.DISTRIBUTOR_PAYMENT_READ}`,
        name: 'Xem lịch sử thanh toán',
        parentId: PermissionId.DISTRIBUTOR,
        rootId: PermissionId.DISTRIBUTOR,
      },
      {
        id: PermissionId.DISTRIBUTOR_PAYMENT_PAY_DEBT,
        level: 2,
        code: PermissionId[PermissionId.DISTRIBUTOR_PAYMENT_PAY_DEBT],
        isActive: 1,
        pathId: `${PermissionId.DISTRIBUTOR}.${PermissionId.DISTRIBUTOR_PAYMENT_PAY_DEBT}`,
        name: 'Thực hiện trả nợ',
        parentId: PermissionId.DISTRIBUTOR,
        rootId: PermissionId.DISTRIBUTOR,
      },
    ]

    const permissionCustomer: Permission[] = [
      {
        id: PermissionId.CUSTOMER,
        level: 1,
        code: PermissionId[PermissionId.CUSTOMER],
        isActive: 1,
        pathId: `${PermissionId.CUSTOMER}`,
        name: 'Quản lý khách hàng',
        parentId: 0,
        rootId: PermissionId.CUSTOMER,
      },
      {
        id: PermissionId.CUSTOMER_READ,
        level: 2,
        code: PermissionId[PermissionId.CUSTOMER_READ],
        isActive: 1,
        pathId: `${PermissionId.CUSTOMER}.${PermissionId.CUSTOMER_READ}`,
        name: 'Xem khách hàng',
        parentId: PermissionId.CUSTOMER,
        rootId: PermissionId.CUSTOMER,
      },
      {
        id: PermissionId.CUSTOMER_CREATE,
        level: 2,
        code: PermissionId[PermissionId.CUSTOMER_CREATE],
        isActive: 1,
        pathId: `${PermissionId.CUSTOMER}.${PermissionId.CUSTOMER_CREATE}`,
        name: 'Thêm khách hàng',
        parentId: PermissionId.CUSTOMER,
        rootId: PermissionId.CUSTOMER,
      },
      {
        id: PermissionId.CUSTOMER_UPDATE,
        level: 2,
        code: PermissionId[PermissionId.CUSTOMER_UPDATE],
        isActive: 1,
        pathId: `${PermissionId.CUSTOMER}.${PermissionId.CUSTOMER_UPDATE}`,
        name: 'Sửa khách hàng',
        parentId: PermissionId.CUSTOMER,
        rootId: PermissionId.CUSTOMER,
      },
      {
        id: PermissionId.CUSTOMER_DELETE,
        level: 2,
        code: PermissionId[PermissionId.CUSTOMER_DELETE],
        isActive: 1,
        pathId: `${PermissionId.CUSTOMER}.${PermissionId.CUSTOMER_DELETE}`,
        name: 'Xóa khách hàng',
        parentId: PermissionId.CUSTOMER,
        rootId: PermissionId.CUSTOMER,
      },
      {
        id: PermissionId.CUSTOMER_DOWNLOAD_EXCEL,
        level: 2,
        code: PermissionId[PermissionId.CUSTOMER_DOWNLOAD_EXCEL],
        isActive: 1,
        pathId: `${PermissionId.CUSTOMER}.${PermissionId.CUSTOMER_DOWNLOAD_EXCEL}`,
        name: 'Tải file Excel tất cả khách hàng',
        parentId: PermissionId.CUSTOMER,
        rootId: PermissionId.CUSTOMER,
      },
      {
        id: PermissionId.CUSTOMER_PAYMENT_READ,
        level: 2,
        code: PermissionId[PermissionId.CUSTOMER_PAYMENT_READ],
        isActive: 1,
        pathId: `${PermissionId.CUSTOMER}.${PermissionId.CUSTOMER_PAYMENT_READ}`,
        name: 'Xem lịch sử thanh toán',
        parentId: PermissionId.CUSTOMER,
        rootId: PermissionId.CUSTOMER,
      },
      {
        id: PermissionId.CUSTOMER_PAY_DEBT,
        level: 2,
        code: PermissionId[PermissionId.CUSTOMER_PAY_DEBT],
        isActive: 1,
        pathId: `${PermissionId.CUSTOMER}.${PermissionId.CUSTOMER_PAY_DEBT}`,
        name: 'Thực hiện trả nợ',
        parentId: PermissionId.CUSTOMER,
        rootId: PermissionId.CUSTOMER,
      },
    ]

    const permissionReceipt: Permission[] = [
      {
        id: PermissionId.RECEIPT,
        level: 1,
        code: PermissionId[PermissionId.RECEIPT],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}`,
        name: 'Quản lý phiếu nhập hàng',
        parentId: 0,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_READ,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_READ],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_READ}`,
        name: 'Xem phiếu nhập hàng',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_CREATE_DRAFT,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_CREATE_DRAFT],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_CREATE_DRAFT}`,
        name: 'Tạo phiếu nháp',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_UPDATE_DRAFT_PREPAYMENT,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_UPDATE_DRAFT_PREPAYMENT],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_UPDATE_DRAFT_PREPAYMENT}`,
        name: 'Sửa phiếu nhập hàng nháp và phiếu nhập hàng tạm ứng',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_DESTROY_DRAFT,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_DESTROY_DRAFT],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_DESTROY_DRAFT}`,
        name: 'Xóa phiếu nháp',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_PAYMENT,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_PAYMENT],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_PAYMENT}`,
        name: 'Thanh toán',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_REFUND_PAYMENT,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_REFUND_PAYMENT],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_REFUND_PAYMENT}`,
        name: 'Hoàn trả tiền',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_PAY_DEBT,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_PAY_DEBT],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_PAY_DEBT}`,
        name: 'Trả nợ',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_SEND_PRODUCT,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_SEND_PRODUCT],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_SEND_PRODUCT}`,
        name: 'Nhập hàng',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
      {
        id: PermissionId.RECEIPT_CANCEL,
        level: 2,
        code: PermissionId[PermissionId.RECEIPT_CANCEL],
        isActive: 1,
        pathId: `${PermissionId.RECEIPT}.${PermissionId.RECEIPT_CANCEL}`,
        name: 'Hủy phiếu',
        parentId: PermissionId.RECEIPT,
        rootId: PermissionId.RECEIPT,
      },
    ]

    const permissionAppointment: Permission[] = [
      {
        id: PermissionId.APPOINTMENT,
        level: 1,
        code: PermissionId[PermissionId.APPOINTMENT],
        isActive: 1,
        pathId: `${PermissionId.APPOINTMENT}`,
        name: 'Quản lý hẹn khám',
        parentId: 0,
        rootId: PermissionId.APPOINTMENT,
      },
      {
        id: PermissionId.APPOINTMENT_READ,
        level: 2,
        code: PermissionId[PermissionId.APPOINTMENT_READ],
        isActive: 1,
        pathId: `${PermissionId.APPOINTMENT}.${PermissionId.APPOINTMENT_READ}`,
        name: 'Xem lịch hẹn khám',
        parentId: PermissionId.APPOINTMENT,
        rootId: PermissionId.APPOINTMENT,
      },
      {
        id: PermissionId.APPOINTMENT_CREATE,
        level: 2,
        code: PermissionId[PermissionId.APPOINTMENT_CREATE],
        isActive: 1,
        pathId: `${PermissionId.APPOINTMENT}.${PermissionId.APPOINTMENT_CREATE}`,
        name: 'Tạo lịch hẹn mới',
        parentId: PermissionId.APPOINTMENT,
        rootId: PermissionId.APPOINTMENT,
      },
      {
        id: PermissionId.APPOINTMENT_UPDATE,
        level: 2,
        code: PermissionId[PermissionId.APPOINTMENT_UPDATE],
        isActive: 1,
        pathId: `${PermissionId.APPOINTMENT}.${PermissionId.APPOINTMENT_UPDATE}`,
        name: 'Sửa lịch hẹn',
        parentId: PermissionId.APPOINTMENT,
        rootId: PermissionId.APPOINTMENT,
      },
      {
        id: PermissionId.APPOINTMENT_DELETE,
        level: 2,
        code: PermissionId[PermissionId.APPOINTMENT_DELETE],
        isActive: 1,
        pathId: `${PermissionId.APPOINTMENT}.${PermissionId.APPOINTMENT_DELETE}`,
        name: 'Xóa lịch hẹn',
        parentId: PermissionId.APPOINTMENT,
        rootId: PermissionId.APPOINTMENT,
      },
      {
        id: PermissionId.APPOINTMENT_REGISTER_TICKET,
        level: 2,
        code: PermissionId[PermissionId.APPOINTMENT_REGISTER_TICKET],
        isActive: 1,
        pathId: `${PermissionId.APPOINTMENT}.${PermissionId.APPOINTMENT_REGISTER_TICKET}`,
        name: 'Đón khách hàng đến và tạo phiếu đón tiếp',
        parentId: PermissionId.APPOINTMENT,
        rootId: PermissionId.APPOINTMENT,
      },
    ]

    const permissionTicketProcedureResult: Permission[] = [
      {
        id: PermissionId.TICKET_PROCEDURE_RESULT,
        level: 1,
        code: PermissionId[PermissionId.TICKET_PROCEDURE_RESULT],
        isActive: 1,
        pathId: `${PermissionId.TICKET_PROCEDURE_RESULT}`,
        name: 'Quản lý trả kết quả phiếu dịch vụ',
        parentId: 0,
        rootId: PermissionId.TICKET_PROCEDURE_RESULT,
      },
    ]

    const permissionTicketLaboratoryResult: Permission[] = [
      {
        id: PermissionId.TICKET_LABORATORY_RESULT,
        level: 1,
        code: PermissionId[PermissionId.TICKET_LABORATORY_RESULT],
        isActive: 1,
        pathId: `${PermissionId.TICKET_LABORATORY_RESULT}`,
        name: 'Quản lý trả kết quả phiếu xét nghiệm',
        parentId: 0,
        rootId: PermissionId.TICKET_LABORATORY_RESULT,
      },
    ]

    const permissionTicketRadiologyResult: Permission[] = [
      {
        id: PermissionId.TICKET_RADIOLOGY_RESULT,
        level: 1,
        code: PermissionId[PermissionId.TICKET_RADIOLOGY_RESULT],
        isActive: 1,
        pathId: `${PermissionId.TICKET_RADIOLOGY_RESULT}`,
        name: 'Quản lý trả kết quả phiếu CĐHA',
        parentId: 0,
        rootId: PermissionId.TICKET_RADIOLOGY_RESULT,
      },
    ]

    const permissionTicketOrder: Permission[] = [
      {
        id: PermissionId.TICKET_ORDER,
        level: 1,
        code: PermissionId[PermissionId.TICKET_ORDER],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}`,
        name: 'Quản lý bán hàng',
        parentId: 0,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_READ,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_READ],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_READ}`,
        name: 'Xem hóa đơn',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_CREATE_DRAFT,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_CREATE_DRAFT],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_CREATE_DRAFT}`,
        name: 'Tạo hóa đơn nháp',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_UPDATE_DRAFT_APPROVED,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_UPDATE_DRAFT_APPROVED],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_UPDATE_DRAFT_APPROVED}`,
        name: 'Sửa hóa đơn nháp, hóa đơn tạm ứng',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_DESTROY_DRAFT,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_DESTROY_DRAFT],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_DESTROY_DRAFT}`,
        name: 'Xóa hóa đơn nháp',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_CREATE_DEBT_SUCCESS,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_CREATE_DEBT_SUCCESS],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_CREATE_DEBT_SUCCESS}`,
        name: 'Tạo hóa đơn bán hàng nhanh',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_UPDATE_DEBT_SUCCESS,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_UPDATE_DEBT_SUCCESS],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_UPDATE_DEBT_SUCCESS}`,
        name: 'Sửa hóa đơn bán hàng nhanh',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_PREPAYMENT,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_PREPAYMENT],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_PREPAYMENT}`,
        name: 'Tạm ứng',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_REFUND_OVERPAID,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_REFUND_OVERPAID],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_REFUND_OVERPAID}`,
        name: 'Hoàn trả tiền thừa',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_SEND_PRODUCT,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_SEND_PRODUCT],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_SEND_PRODUCT}`,
        name: 'Gửi hàng',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_RETURN_PRODUCT,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_RETURN_PRODUCT],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_RETURN_PRODUCT}`,
        name: 'Hoàn trả hàng',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_PAYMENT_AND_CLOSE,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_PAYMENT_AND_CLOSE],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_PAYMENT_AND_CLOSE}`,
        name: 'Đóng phiếu',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_PAY_DEBT,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_PAY_DEBT],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_PAY_DEBT}`,
        name: 'Trả nợ',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_REOPEN,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_REOPEN],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_REOPEN}`,
        name: 'Mở lại phiếu',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
      {
        id: PermissionId.TICKET_ORDER_CANCEL,
        level: 2,
        code: PermissionId[PermissionId.TICKET_ORDER_CANCEL],
        isActive: 1,
        pathId: `${PermissionId.TICKET_ORDER}.${PermissionId.TICKET_ORDER_CANCEL}`,
        name: 'Hủy đơn',
        parentId: PermissionId.TICKET_ORDER,
        rootId: PermissionId.TICKET_ORDER,
      },
    ]

    const permissionTicketClinic: Permission[] = [
      {
        id: PermissionId.TICKET_CLINIC,
        level: 1,
        code: PermissionId[PermissionId.TICKET_CLINIC],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}`,
        name: 'Quản lý phòng khám',
        parentId: 0,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_READ,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_READ],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_READ}`,
        name: 'Xem phiếu khám',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_CREATE,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_CREATE],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_CREATE}`,
        name: 'Đăng ký khám mới',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_DESTROY_DRAFT_SCHEDULE,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_DESTROY_DRAFT_SCHEDULE],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_DESTROY_DRAFT_SCHEDULE}`,
        name: 'Xóa phiếu khám',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_START_CHECKUP,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_START_CHECKUP],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_START_CHECKUP}`,
        name: 'Bắt đầu vào khám',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_UPDATE_TICKET_PROCEDURE_LIST,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_UPDATE_TICKET_PROCEDURE_LIST],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_UPDATE_TICKET_PROCEDURE_LIST}`,
        name: 'Chỉ định dịch vụ',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_UPDATE_TICKET_LABORATORY_LIST,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_UPDATE_TICKET_LABORATORY_LIST],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_UPDATE_TICKET_LABORATORY_LIST}`,
        name: 'Chỉ định Xét nghiệm',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_UPDATE_TICKET_RADIOLOGY_LIST,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_UPDATE_TICKET_RADIOLOGY_LIST],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_UPDATE_TICKET_RADIOLOGY_LIST}`,
        name: 'Chỉ định CĐHA',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_UPDATE_TICKET_PRODUCT_CONSUMABLE,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_UPDATE_TICKET_PRODUCT_CONSUMABLE],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_UPDATE_TICKET_PRODUCT_CONSUMABLE}`,
        name: 'Sửa danh sách vật tư tiêu hao',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_UPDATE_TICKET_PRODUCT_PRESCRIPTION,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_UPDATE_TICKET_PRODUCT_PRESCRIPTION],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_UPDATE_TICKET_PRODUCT_PRESCRIPTION}`,
        name: 'Kê đơn thuốc',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_UPDATE_ITEMS_MONEY,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_UPDATE_ITEMS_MONEY],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_UPDATE_ITEMS_MONEY}`,
        name: 'Sửa số lượng và chiết khấu',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_PREPAYMENT,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_PREPAYMENT],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_PREPAYMENT}`,
        name: 'Tạm ứng',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_REFUND_OVERPAID,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_REFUND_OVERPAID],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_REFUND_OVERPAID}`,
        name: 'Hoàn trả tiền thừa',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_PAY_DEBT,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_PAY_DEBT],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_PAY_DEBT}`,
        name: 'Trả nợ',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_SEND_PRODUCT,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_SEND_PRODUCT],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_SEND_PRODUCT}`,
        name: 'Xuất thuốc',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_RETURN_PRODUCT,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_RETURN_PRODUCT],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_RETURN_PRODUCT}`,
        name: 'Hoàn trả thuốc',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_CLOSE,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_CLOSE],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_CLOSE}`,
        name: 'Đóng phiếu khám',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_REOPEN,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_REOPEN],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_REOPEN}`,
        name: 'Mở lại phiếu khám',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },

      {
        id: PermissionId.TICKET_CLINIC_UPDATE_DIAGNOSIS_BASIC,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_UPDATE_DIAGNOSIS_BASIC],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_UPDATE_DIAGNOSIS_BASIC}`,
        name: 'Khám và chẩn đoán',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
      {
        id: PermissionId.TICKET_CLINIC_UPDATE_DIAGNOSIS_SPECIAL,
        level: 2,
        code: PermissionId[PermissionId.TICKET_CLINIC_UPDATE_DIAGNOSIS_SPECIAL],
        isActive: 1,
        pathId: `${PermissionId.TICKET_CLINIC}.${PermissionId.TICKET_CLINIC_UPDATE_DIAGNOSIS_SPECIAL}`,
        name: 'Khám chuyên sâu',
        parentId: PermissionId.TICKET_CLINIC,
        rootId: PermissionId.TICKET_CLINIC,
      },
    ]

    await this.permissionRepository.delete({})

    const { idsEffect } = await this.permissionRepository.upsert([
      ...permissionOrganization,
      ...permissionRole,
      ...permissionUser,
      ...permissionStatistic,
      ...permissionMasterData,

      ...permissionProduct,
      ...permissionDistributor,
      ...permissionCustomer,
      ...permissionReceipt,

      ...permissionAppointment,
      ...permissionTicketProcedureResult,
      ...permissionTicketLaboratoryResult,
      ...permissionTicketRadiologyResult,

      ...permissionTicketOrder,
      ...permissionTicketClinic,
    ])

    this.cacheDataService.reloadPermissionAll()

    return { data: { idsEffect } }
  }
}
