export const distributorData = [
	{ otherId: 'XSnGj4XxeFcpeZ1WYRtR', fullName: 'A Long Inno' },
	{ otherId: 'SY9y3q7z2w9lJLsWgZvD', fullName: 'Abc' },
	{ otherId: 'B8z3yiCczVeuwtu4LtgZ', fullName: 'Anh quyền skintech' },
	{ otherId: 'HKGr54i2fcbGdLR20iG0', fullName: 'Bioderma' },
	{ otherId: 'T2hGVDaB8Xmb3QDuM3Gc', fullName: 'Bs Hoa' },
	{ otherId: 'yYxuMknDiWy5zJ5r0SXb', fullName: 'Bs Hoàng Hường' },
	{ otherId: 'AaFe6wtEPJ9IxfAA4JBn', fullName: 'Bs Hà Lê' },
	{ otherId: 'Wvbpud8lBpfTTUqhcMGh', fullName: 'Bs Hằng' },
	{ otherId: 'wgBnnNby5ZUNpzsrBych', fullName: 'Bs Linh SG' },
	{ otherId: 'zSnSFocGuipe2YidHcjh', fullName: 'Bs Mai anh' },
	{ otherId: 'Gvntpu1cBRz9PvryU0ct', fullName: 'Bs Nam' },
	{ otherId: 'eXdavAE1vT2ZWKIVFFyY', fullName: 'Bs Nga' },
	{ otherId: '0w4WEmt0NaB6KBDCh0VN', fullName: 'Bs Nghĩa' },
	{ otherId: 'puSU8qIOkDwHsBdWNE0c', fullName: 'Bs Thiên Hương' },
	{ otherId: '3g3qpD3C65VXS1isGOoA', fullName: 'Bs Thuỳ Linh' },
	{ otherId: 'lI6LRFBWfpceuzSqwK4Q', fullName: 'Bs Thuỷ Bấy' },
	{ otherId: 'sy8eLfsCEGtrpNdmRm7a', fullName: 'Bs Thảo' },
	{ otherId: 'LL0xZUPHtJbpf4p7Apag', fullName: 'Bs Thắm da liễu' },
	{ otherId: 'omiOwIZ9OhYLzAKG1Kzr', fullName: 'Bs Trần Hùng' },
	{ otherId: '2JGH5MTAMIQxrzuWKnK3', fullName: 'Bs Đào' },
	{ otherId: 'kFYLGOW8zwgUSMc1uTCm', fullName: 'Chị Thuận Inno' },
	{ otherId: '42ofylWEuuEGJJK2AVAJ', fullName: 'Cty Nhật Khang' },
	{ otherId: 'BAMRQjcNjgaBYygRHcIZ', fullName: 'Cty ava' },
	{ otherId: 'vyJ5MjGNnAdS7HyaVC8V', fullName: 'Cty beta' },
	{ otherId: 'iofUTnGipg1hnXSTn3ea', fullName: 'Dr Anh' },
	{ otherId: 'KRq9042S3P5qEd8voG8y', fullName: 'Dr Thuỳ Trang' },
	{ otherId: 'Ujx6YhXSUN7vSNwTrwG1', fullName: 'Dương Hương' },
	{ otherId: 'HCe2DN2sFFmGSf6YqKwv', fullName: 'Em Hảo tỉ' },
	{ otherId: 'R6FuQ7kjptXHssb7dVTc', fullName: 'Hiệu thuốc Phi' },
	{ otherId: 'Rz9jXEJghXCcJrwEdZiW', fullName: 'Huy GSv' },
	{ otherId: 'InxrWFPU1Z4W9dOoKFUq', fullName: 'Huê san san' },
	{ otherId: '0HjfmU4YmqW8Sh53Sw7O', fullName: 'Huệ Oxy' },
	{ otherId: 'OYsJODvBFuK2ZCtitp8e', fullName: 'Nga usolab' },
	{ otherId: 'SDcSk43B4eNp7S9G0eNX', fullName: 'Nhập lại đơn hoàn' },
	{ otherId: 'Til6WqZM7hXwWuizC5kX', fullName: 'Nhập xót' },
	{ otherId: 'CKkcG4KIeREvaggCINBz', fullName: 'Phượng HUP' },
	{ otherId: '2xPdHqUwfWMtwZiFbwsv', fullName: 'Shopee' },
	{ otherId: 'm501ywyeAn74hz5lLMn8', fullName: 'Thuận' },
	{ otherId: 'apKbUltEm0mh0fVQgnp2', fullName: 'Thắm' },
	{ otherId: 'nHXfkWCoTzpyLyByZfLf', fullName: 'Đức image' },
]
