export const distributorData = [
	{ otherId: 'XSnGj4XxeFcpeZ1WYRtR', fullNameVi: 'A Long Inno' },
	{ otherId: 'SY9y3q7z2w9lJLsWgZvD', fullNameVi: 'Abc' },
	{ otherId: 'B8z3yiCczVeuwtu4LtgZ', fullNameVi: 'Anh quyền skintech' },
	{ otherId: 'HKGr54i2fcbGdLR20iG0', fullNameVi: 'Bioderma' },
	{ otherId: 'T2hGVDaB8Xmb3QDuM3Gc', fullNameVi: 'Bs Hoa' },
	{ otherId: 'yYxuMknDiWy5zJ5r0SXb', fullNameVi: 'Bs Hoàng Hường' },
	{ otherId: 'AaFe6wtEPJ9IxfAA4JBn', fullNameVi: 'Bs Hà Lê' },
	{ otherId: 'Wvbpud8lBpfTTUqhcMGh', fullNameVi: 'Bs Hằng' },
	{ otherId: 'wgBnnNby5ZUNpzsrBych', fullNameVi: 'Bs Linh SG' },
	{ otherId: 'zSnSFocGuipe2YidHcjh', fullNameVi: 'Bs Mai anh' },
	{ otherId: 'Gvntpu1cBRz9PvryU0ct', fullNameVi: 'Bs Nam' },
	{ otherId: 'eXdavAE1vT2ZWKIVFFyY', fullNameVi: 'Bs Nga' },
	{ otherId: '0w4WEmt0NaB6KBDCh0VN', fullNameVi: 'Bs Nghĩa' },
	{ otherId: 'puSU8qIOkDwHsBdWNE0c', fullNameVi: 'Bs Thiên Hương' },
	{ otherId: '3g3qpD3C65VXS1isGOoA', fullNameVi: 'Bs Thuỳ Linh' },
	{ otherId: 'lI6LRFBWfpceuzSqwK4Q', fullNameVi: 'Bs Thuỷ Bấy' },
	{ otherId: 'sy8eLfsCEGtrpNdmRm7a', fullNameVi: 'Bs Thảo' },
	{ otherId: 'LL0xZUPHtJbpf4p7Apag', fullNameVi: 'Bs Thắm da liễu' },
	{ otherId: 'omiOwIZ9OhYLzAKG1Kzr', fullNameVi: 'Bs Trần Hùng' },
	{ otherId: '2JGH5MTAMIQxrzuWKnK3', fullNameVi: 'Bs Đào' },
	{ otherId: 'kFYLGOW8zwgUSMc1uTCm', fullNameVi: 'Chị Thuận Inno' },
	{ otherId: '42ofylWEuuEGJJK2AVAJ', fullNameVi: 'Cty Nhật Khang' },
	{ otherId: 'BAMRQjcNjgaBYygRHcIZ', fullNameVi: 'Cty ava' },
	{ otherId: 'vyJ5MjGNnAdS7HyaVC8V', fullNameVi: 'Cty beta' },
	{ otherId: 'iofUTnGipg1hnXSTn3ea', fullNameVi: 'Dr Anh' },
	{ otherId: 'KRq9042S3P5qEd8voG8y', fullNameVi: 'Dr Thuỳ Trang' },
	{ otherId: 'Ujx6YhXSUN7vSNwTrwG1', fullNameVi: 'Dương Hương' },
	{ otherId: 'HCe2DN2sFFmGSf6YqKwv', fullNameVi: 'Em Hảo tỉ' },
	{ otherId: 'R6FuQ7kjptXHssb7dVTc', fullNameVi: 'Hiệu thuốc Phi' },
	{ otherId: 'Rz9jXEJghXCcJrwEdZiW', fullNameVi: 'Huy GSv' },
	{ otherId: 'InxrWFPU1Z4W9dOoKFUq', fullNameVi: 'Huê san san' },
	{ otherId: '0HjfmU4YmqW8Sh53Sw7O', fullNameVi: 'Huệ Oxy' },
	{ otherId: 'OYsJODvBFuK2ZCtitp8e', fullNameVi: 'Nga usolab' },
	{ otherId: 'SDcSk43B4eNp7S9G0eNX', fullNameVi: 'Nhập lại đơn hoàn' },
	{ otherId: 'Til6WqZM7hXwWuizC5kX', fullNameVi: 'Nhập xót' },
	{ otherId: 'CKkcG4KIeREvaggCINBz', fullNameVi: 'Phượng HUP' },
	{ otherId: '2xPdHqUwfWMtwZiFbwsv', fullNameVi: 'Shopee' },
	{ otherId: 'm501ywyeAn74hz5lLMn8', fullNameVi: 'Thuận' },
	{ otherId: 'apKbUltEm0mh0fVQgnp2', fullNameVi: 'Thắm' },
	{ otherId: 'nHXfkWCoTzpyLyByZfLf', fullNameVi: 'Đức image' },
]
